### ISSUE TITLE
Project Activity Overview

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1024]
## Story

As a user, I want to be informed of activity on projects I follow (either because I work on them or because I am otherwise interested in them).

## Implementation

The UI currently has to poll multiple sources (core-service, KG, notebook service) to get notifications. We want to introduce and use an asynchronous notification mechanism

- The UI should subscribe for notifications for the currently view project (and unsubscribe when the project changes).
- Initially relevant notifications are those provided by gitlab and include push events, issue events and merge-request events. When the event / message queue is implemented, this list will grow.

See: 
- https://docs.gitlab.com/ee/user/project/integrations/webhooks.html
- [Proxy support](https://github.com/SwissDataScienceCenter/incubator-proxy/issues/8)
- https://developer.mozilla.org/en-US/docs/Web/API/Worker
- https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API

**Comment by lorenzo-cavazzi** [comment]
The first step in that direction was made with WebSocket.

We have a stub issue for deciding of further steps, taking advantage of the brand new message queue system: https://github.com/orgs/SwissDataScienceCenter/projects/44/views/14?pane=issue&itemId=17744509
