### ISSUE TITLE
Typo: emtpy

### ISSUE THREAD

**Issue by palrogg** [SwissDataScienceCenter/renku-ui#1032]
## Description

Small typo in [projects view](https://renkulab.io/projects): “em*tp*y” instead of “empty”

## Reproduce

1. Go to 'https://renkulab.io/projects
2. Right under the search form, look for the next element: `<small class="form-text text-muted">Leave emtpy to browse all projects or enter at least 3 characters to filter.</small>`

## Screenshot

![Capture d’écran 2020-09-07 à 23 07 05](https://user-images.githubusercontent.com/12730304/92416783-711af280-f15f-11ea-97a6-11ab3b9938e1.png)

**Comment by lorenzo-cavazzi** [comment]
Thanks for reporting this!
If fact, that word was misspelled in many places in the UI :grin: 
It will be fixed in the next release (see #1033).

**Comment by palrogg** [comment]
Great, thank you for the fix!
