### ISSUE TITLE
UI changes for all-projects KG

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-ui#1054]
# Description

**This work should go in a feature branch**

Now that KG applies security and visibility restrictions, al projects should go into the KG. This means:
- [X] Remove the `opt-out` option for private projects
- [ ] Changes the messages to explain that a project not being in the KG is a misconfiguration that should be remedied.

# Details

Remove this option and the code that supports it:

![image](https://user-images.githubusercontent.com/1196411/149293213-a8f4f183-c62a-4cc4-89a0-210f8029f83c.png)

This message should be changed:

![image](https://user-images.githubusercontent.com/1196411/149293390-1faf8181-44ee-4e40-accd-e70ffe611120.png)

It should be the same as the message for public projects.

[
other changes to be designed: 
- a banner on the project saying that the KG is not activated and this is a project misconfiguration
- a tool for finding projects that are not in the KG and bulk fixing them.
]

# Original Description

As a Renku user, I'd like any new project I create to get opted-in to the KG by default.

**Acceptance criteria:**
* any new private and internal project should follow the process for opting-in to the KG as it's currently done for public projects which means there's no possibility of not opting-in.

**Comment by rokroskar** [comment]
isn't this already the case?

**Comment by rokroskar** [comment]
no, the button is to opt out :)

**Comment by jachro** [comment]
Right. I wasn't aware of that change. Let me update the issue, then.

**Comment by ciyer** [comment]
Internal projects are also opted-in w/o the option to opt out. So, all you are asking for is removal of the "opt-out" check box for private projects?

**Comment by rokroskar** [comment]
But presumably this issue has a long list of dependencies before it should actually be implemented? We don't want to do this before the graph queries can conceal private data.
