### ISSUE TITLE
Add IDs to template and visibility selectors on the New Project page 

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-ui#1063]
##  Motivation

The acceptance tests need to have these IDs in order to accurately find the elements on the page and click them.
<img width="697" alt="Screen Shot 2020-10-06 at 11 02 06" src="https://user-images.githubusercontent.com/11528695/95181371-7c475980-07c3-11eb-9d07-3b4bfc3f710b.png">

**Comment by lorenzo-cavazzi** [comment]
Do you mean the HTML `<select>` elements ID? 
In that case, it's `visibility` for the visibility and `template` for the template. You can check other details by right-clicking the element in the browser and selecting "Inspect" (or "inspect element", depending on the browser).

**Comment by lorenzo-cavazzi** [comment]
Maybe you meant something else? Because those are already used in the acceptance tests.
https://github.com/SwissDataScienceCenter/renku/blob/4aeba4ba2cdae18ae3116e4a02a9f16458bcd2ba/acceptance-tests/src/test/scala/ch/renku/acceptancetests/pages/NewProjectPage.scala#L45

**Comment by ciyer** [comment]
That was actually my mistake. I was looking at RenkuLab, where these elements do not have ids, but you are right, it is fixed on dev. Closing the issue.
