### ISSUE TITLE
Support more compression formats when adding and extracting files to a dataset

### ISSUE THREAD

**Issue by m-alisafaee** [SwissDataScienceCenter/renku-ui#1072]
As a renku user, I want to be able to extract `.gz` files when adding them to a dataset (similar to `.zip` files).

**Comment by mohammad-sdsc** [comment]
It seems that the decompression library support gzip format and we need just to detect `.gz` files as compressed. I've tested this by changing extension of a `.gz` file to `.zip` and then I was able to upload and extract it.

**Comment by vfried** [comment]
@mohammad-sdsc @jsam this might need backend support, I tried to implement the upload of .tar.gz and it looks like the backend is not decompressing this files when i ask for it...

![image](https://user-images.githubusercontent.com/42647877/99956283-13716c00-2d86-11eb-81f0-6e4bc8697e55.png)

Request:
![image](https://user-images.githubusercontent.com/42647877/99956474-5fbcac00-2d86-11eb-9c12-42572ee4f4d1.png)


Response:
![image](https://user-images.githubusercontent.com/42647877/99956359-300da400-2d86-11eb-84cb-4af86d42fb0e.png)

**Comment by vfried** [comment]
@ciyer this needs backend support, i will remove it from this sprint

**Comment by ciyer** [comment]
> @ciyer this needs backend support, i will remove it from this sprint

**Comment by lorenzo-cavazzi** [comment]
The Datasets feature will be completely revised in the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
