### ISSUE TITLE
Cancel button in Modify Dataset page leads to a blank screen

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-ui#1073]
1. Go to any dataset page: https://dev.renku.ch/projects/mohammad.alisafaee/lego-analytics/datasets/sets/
2. Click on Modify
3. Scroll down and click on Cancel
4. A blank screen appears (instead of going back to dataset)

## Context

- macOS Catalina
- Safari 14.0

**Comment by ciyer** [comment]
This has been fixed by #965.
