### ISSUE TITLE
Project stats are not correct

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-ui#1074]
## Description

Project stats (Renku project page > Overview > Stats) are not correct when a project is modified. It seems that they will be eventually correct after couple of hours.

## Reproduce

1. Go to a project with some files in LFS: https://dev.renku.ch/projects/mohammad.alisafaee/lego-analytics/overview/stats
2. Clone the project
3. Go to the cloned project > Overview > Stats
4. See that **Storage stats** are not correct (even after gitlab pipeline finishes)

**Comment by lorenzo-cavazzi** [comment]
Thank you Mohammad for reporting this.
I investigated a bit and it seems that the stats from GitLab are not updated instantly. I get the same problem on the GitLab page.

Nevertheless, we don't query again for the stats when entering the stats tab, so we won't show the up-to-date stats anyway. This needs to be fixed.
I believe the logic on the Overview page navigation is broken. Clicking any tab (Description, Stats, Commits...) always triggers a query for the readme file content that is needed only for Description. Every tab should first refresh the resources it needs.
