### ISSUE TITLE
Improve the way error messages from the server are displayed in the generic form

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1078]
They should look like in the create dataset form...

https://github.com/SwissDataScienceCenter/renku-ui/pull/1071#pullrequestreview-510214790

**Comment by lorenzo-cavazzi** [comment]
I opened an issue in renku-python to standardize the error we are getting SwissDataScienceCenter/renku-python#1616 .
Should we close this issue since it's primarily about asking for a change in the core service?
