### ISSUE TITLE
Windows Testing

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1086]
We have been getting several complaints and bug reports about the experience on Windows. We should do some hands-on testing on windows.

1. Run through the hands on tutorial on Edge and Chrome on Windows
2. Do some small QA-type project on windows (create a project, upload a dataset [300 MB or more], and start an environment).

**Comment by lorenzo-cavazzi** [comment]
I tested on Windows using the following browsers:

* Chrome 86
* Edge 86
* Firefox 82

I didn't find any problem, everything worked fine (or at least as expected on the Linux/Mac counterparts 😄 ), both when working in RenkuLab and JupiterLab.
Features that require to interact with the local environment (like drag and drop) also work well.

I think we can close this issue.

I have opened a couple of minor QA issues/PR, but they are unrelated to Windows.

- #1119 
- #1120 
- SwissDataScienceCenter/renku#1675
