### ISSUE TITLE
Provide default image for environment launch 

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#1087]
Currently, when the UI determines that the correct image for an environment launch is not available, it still issues a POST request just as if that image was available. It is the notebook-service which picks a default image for this environment to launch from. In such situations, the the UI should read the default image to be used from the project configuration and include it in the post request.

**Comment by lorenzo-cavazzi** [comment]
Closing this in favor of #1105 even though the solution is slightly different (the UI always send the image information when set at the project level, not only when the image is not found from the notebook service)
