### ISSUE TITLE
File preview fails when the file is too big

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1094]
## Description

When trying to load a large file the file explorer fails.
We should decide if we want to allow the preview of such files and how we will handle this.

## Reproduce

There is an example here... https://renkulab.io/projects/divine.nsiama/wsbim1322-20200920/files/blob/data/portal_data_joined.csv

As an observation, gitlab allows the preview of this files but it first warns the user... maybe we could do something similar, or offer the option of downloading the file instead of previewing it in the browser.

![image](https://user-images.githubusercontent.com/42647877/97013110-f2301c80-1548-11eb-84b7-1a68290e7810.png)

**Comment by lorenzo-cavazzi** [comment]
The file takes a long time but it eventually loads (see screen below). I agree with implementing a strategy similar to GitLab.
We may consider not formatting the file in these cases when the user clicks on "load anyway" if this reduce the load time.
![Screenshot_20201023_160235](https://user-images.githubusercontent.com/43481553/97013382-49ce8800-1549-11eb-9382-863d1d9d7b11.png)

**Comment by vfried** [comment]
:o how long were you waiting? I waited but in my case it never loaded.

This is anyways a bad user experience so we should improve it as you say.

**Comment by ciyer** [comment]
Fixed by #1186.
