### ISSUE TITLE
Table is displayed as markdown table in the dataset description

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-ui#1099]
## Description

After inserting a table in the description of a dataset it is displayed first as normal table but after switching back and forth from the markdown display the table is never displayed as a normal table anymore, only as a markdown table.

![switching_markdown_removes_table_display](https://user-images.githubusercontent.com/6317721/97547961-c68cb680-19ce-11eb-9d58-75fdfe2087ae.png)

## Reproduce

1. Go to a project page and create a new dataset
2. In the description insert a table by clicking the table button in the tool bar
3. Click on the markdown switch button
4. Click again on the markdown switch button
5. See the table being displayed as markdown instead of a normal table

## Context

- https://dev.renku.ch/projects/renku-qa/coffee-orders/datasets/coffee-orders-%E2%98%95-by-location/
- linux ubuntu 20.4
- firefox 82.0 

<details><summary>Browser Output</summary>
<pre>
</pre>
</details>

**Comment by vfried** [comment]
David, could you give a bit more information about this... i see you say it first was displayed as a table but then it wasn't

I tried to do a table as you in gitlab and it's not rendered as a table there either...
![image](https://user-images.githubusercontent.com/42647877/97586657-cc988c80-19fa-11eb-8c0a-f0cc95e4f5d3.png)

If you do it like this is valid but **i think** you need the --- row
| header | header |
| ------ | ------ |

**Comment by lorenzo-cavazzi** [comment]
The visualization seems to be working fine now
![image](https://user-images.githubusercontent.com/43481553/205974495-3716e967-cfd8-44e1-9bb0-90a8e110301d.png)
