### ISSUE TITLE
Detect other types of references in contributions.

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#110]
_From @ableuler on February 9, 2018 9:49_

- Snippets should be treated as repo files.
- References to other issues / merge requests should be clickable links.
- References to web-URLs should be links (maybe iframes??)

_Copied from original issue: SwissDataScienceCenter/incubator-renga-ui#37_

**Comment by ciyer** [comment]
Putting on hold, since this may become obsolete by #1330.

**Comment by ciyer** [comment]
Made obsolete by #1330.
