### ISSUE TITLE
Lineage displaying a blank page

### ISSUE THREAD

**Issue by joke1196** [SwissDataScienceCenter/renku-ui#1101]
## Description

When trying to look for the lineage of a file I am redirected to a blank page. 
I used this file: https://dev.renku.ch/projects/renku-qa/coffee-orders/files/blob/data/output/potentialWinners.txt 

## Reproduce

1. Go to https://dev.renku.ch/projects/renku-qa/coffee-orders/files/blob/data/output/potentialWinners.txt
2. Click on Lineage View button
3. See the screenshot below

![blank lineage](https://user-images.githubusercontent.com/6317721/97681496-2bf8aa00-1a98-11eb-855c-e9b38a584f00.png)

## Context

- https://dev.renku.ch/projects/renku-qa/coffee-orders/
- Linux Ubuntu 20.4
- firefox 82.0

<details><summary>Browser Output</summary>
<pre>
TypeError: t is undefined
    ii Lineage.present.js:35
    r Lineage.present.js:46
    value Lineage.present.js:108
    value Lineage.present.js:107
    value Lineage.present.js:186
    React 7
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    Redux 3
    value Model.js:149
    value Model.js:237
    value Model.js:213
    value Project.state.js:117
    promise callback*value Project.state.js:109
    e Project.js:239
    l runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
    value main.759a9eed.chunk.js:2
    fetchGraphStatus Project.js:619
    e KnowledgeGraphStatus.container.js:49
    l runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
    value main.759a9eed.chunk.js:2
    value KnowledgeGraphStatus.container.js:37
    _l React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    r helpers.ts:85
instrument.ts:113:35
    le instrument.ts:113
    React 5
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 6
    Redux 3
    value Model.js:149
    value Model.js:237
    value Model.js:213
    value Project.state.js:117
    (Async: promise callback)
    value Project.state.js:109
    e Project.js:239
    l runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
    value main.759a9eed.chunk.js:2
    fetchGraphStatus Project.js:619
    e KnowledgeGraphStatus.container.js:49
    l runtime.js:45
    _invoke runtime.js:274
    t runtime.js:97
    Babel 4
    value main.759a9eed.chunk.js:2
    value KnowledgeGraphStatus.container.js:37
    _l React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    unstable_runWithPriority scheduler.production.min.js:18
    React 5
    r helpers.ts:85

</pre>
</details>

**Comment by ciyer** [comment]
Thanks for reporting this. It is easy to recreate:  https://dev.renku.ch/projects/renku-qa/coffee-orders/files/lineage/data/output/potentialWinners.txt
