### ISSUE TITLE
Support custom registry images when starting a new interactive environment

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1105]
## Motivation

SwissDataScienceCenter/renku-notebooks#304 will allow users to provide a custom registry image for interactive environments and the `GET servers` endpoint will return more information about the registry image that has been used. We can enhance the UI to support these features.

## Proposal

* [x] add an extra field for `image` before the list notebook options in the new environment page. The value should come from the `renku.ini` file. We don't need to display it when it's not available.
* [ ] adapt the code that checks the image availability. When the custom `image` is specified, the check should be similar to the one for non-owned repositories (i.e. don't check the job but only the image availability in the registry)
* [x] update the server list visualization to include the information about the custom image and the fallback to a default image
* [ ] [bonus] allow the user to manually overwrite the default image in the "start environment" page on selected renkulab environments (i.e. specify if it's possible on the values.yaml file). Not sure if this is useful/desirable at all...

As a follow up, it would be great to allow users to change the ini file settings in the UI (should we have an endpoint in `renku-core` for that?)

## Context

I can add a mockup for the 3rd point. Very likely, the information will be included in the commit's popover whenever relevant. When the environment is started using a fallback image, we may want to display a different icon (e.g. a warning sign) to make explicit to the user that things didn't go as expected.

**Comment by ciyer** [comment]
I think this is a good way to solve this.
