### ISSUE TITLE
Set up structured style sheets

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#111]
_From @ableuler on February 9, 2018 9:54_

Define reusable styles, colors, etc

_Copied from original issue: SwissDataScienceCenter/incubator-renga-ui#38_

**Comment by ciyer** [comment]
This was done in  pr #153 / issue #132. See https://github.com/SwissDataScienceCenter/renku-ui/tree/master/src/styles.
