### ISSUE TITLE
Better feedback to the users for autosaved content

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1113]
## Motivation

Users should know in advance when there is autosaved content for a specific branch/commit.

## Proposal

The UI should already have all the needed information to give proper feedback to the user.
I suggest adding a `*` next to the short SHA on the commit dropdown menu item for which we find autosaved content.
Once selected, we can show a `Label` explicitly saying that there is autosaved content, possibly with a link to the documentation.

It was also suggested to show the commnds to reset the changes (`git reset --hard <target-commit>`?).
We can add it in 2 places:
* on the info popup showing before we the environment starts
* on the documentation we link.

## Context

![Screenshot_20201105_134027](https://user-images.githubusercontent.com/43481553/98242919-72a14500-1f6d-11eb-898c-468cfdad53bd.png)

**Comment by rollicks-c** [comment]
Already in the next sprint? Yeah, you guys are fast!  Thx a lot for taking our feedback to the different topics and the very fast response times.

**Comment by rollicks-c** [comment]
> It was also suggested to show the commnds to reset the changes (git reset --hard <target-commit>?).

Thank you for the suggestions to address our request. I'd an experienced user already know how to reset the changed and might not need the command hint. While an unexperienced  user might not want to deal with "cli-stuff". What do you think about this: The popup that shows could maybe not only inform about the unsaved changes, but also offer the discard this changes (by removing the auto-save branch entirely). Something like: "you have unsaved changes. do you want to continue or discard them and start from a clean environment....".
What do you think?

**Comment by lorenzo-cavazzi** [comment]
That's indeed a good suggestion. A similar discussion came up at some point within the team.
The main pain-point we identified is that the user may not be aware of the changes that are going to be discarded, and we don't have anything in place in the UI to show a rich riff (yet).

We could temporarily take advantage of the GitLab comparison feature. This will open a new page outside the RenkuLab UI, not sure if it has a good impact on the user experience... Anyway, this is a raw mockup of those ideas

![Screenshot_20201119_134518](https://user-images.githubusercontent.com/43481553/99668090-92586300-2a6d-11eb-9015-f72f801a4159.png)

Clicking on the scary Discard button would throw away the autosaved content and start the environment.
Clicking on Compare would open a GitLab page similar to the following one

![Screenshot_20201119_133702](https://user-images.githubusercontent.com/43481553/99668110-98e6da80-2a6d-11eb-94d0-dd9c5cc53cb6.png)

Is this close to what you had in mind @rollicks-c ?

**Comment by lorenzo-cavazzi** [comment]
By the way, any discard button would require support from the backend and a bit of design.
If the UI solution implemented in #1134 is already an improvement, I'd like to merge that soon and move this discussion to a follow-up issue. I'll create the backend counterpart (very probably in renku-notebooks) when we define the details :smile:

**Comment by rollicks-c** [comment]
> Is this close to what you had in mind @rollicks-c ?

Absolutely! Sweet! The comparison feature is an extra. I think for us, it would already be a benefit with just the info about auto-saved work and the two options "continue" and "discard". If the user is not aware of any auto-saved changes, he probably also won't need it any more and the comparison feature might no be required at all cost. Anyway. I think your suggestions with the two options is nice!

**Comment by lorenzo-cavazzi** [comment]
>  I think for us, it would already be a benefit with just the info about auto-saved work and the two options "continue" and "discard".

Ok, great to hear that!

> If the user is not aware of any auto-saved changes, he probably also won't need it any more and the comparison feature might no be required at all cost.

Yeah, I guess you are right. I was worried about unexpected shutdowns (e.g. we terminate the environment after 24h of inactivity), and in that case, the user may not be sure about what he committed and pushed and what not.
I'll ping a couple of people who were involved in this discussion in the past to get feedback on this detail. Maybe a link in the second paragraph is enough instead of a button :thinking: 

Thanks for the very valuable feedback on this!

**Comment by lorenzo-cavazzi** [comment]
@rollicks-c I opened a new issue here #1143 that contains your proposal and further improvements. We will add an updated mockup soon. Feel free to chime in!
