### ISSUE TITLE
Edit the project settings from the UI

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1114]
##  Motivation

We are gradually storing more project settings in the `.renku/renku.ini` file. Since some of them are relevant only for the interactive environments, it would be nice to allow the user to change them directly from the UI.

## Proposal

* Move the clone commands and repository URL to an overview tab. I suggest renaming the `Stats` tab to `Information` (or `Info`) and move the content there. The preview is only a broad reference, some elements should be adjusted better.
![Screenshot_20201105_140914](https://user-images.githubusercontent.com/43481553/98245736-a9795a00-1f71-11eb-877e-50313f7e76e4.png)

* Divide the Settings page into 2 sections ~(similar to the `Cards` components used in the preview above), one with Renkulab settings (the current project Tags and Description)~ (EDIT: use subtabs as suggested in the next post) and a new one with the actual project settings.
We should show the current settings and allow to edit or add them. Adding should suggest the available parameters (we have a limited set, custom options and custom image) but also allow the user to add new custom fields.
The best solution would be to have a backend service from renku-core to invoke the `renku settings` commands. [Preview: to be added]

# Progress

- [x] API Design (sprint-2020-12-04)
- [ ] UI implementation

**Comment by ciyer** [comment]
I propose putting this on a subtab of the settings page.

<img width="963" alt="image" src="https://user-images.githubusercontent.com/1196411/99834233-8d75db00-2b63-11eb-8d65-23fd14ec62eb.png">

**Comment by lorenzo-cavazzi** [comment]
I think the mockup you proposed is on point!
A couple of small variations I would do:
1. Move the "Pinned image" on top, just after the "Default for new pods" to keep it in line with the Environments page.
2. Add the possibility to set custom values for know fields (e.g. 16G of RAM, or any other random string) and new fields. When doing that, the value should be underlined in red/yellow with a note saying the value may not by valid in this RenkuLab deployment. We can get the list of available options and values from the `GET /notebooks/server_options` API.

The cleanest solution requires APIs from renku-core to expose `renku-config`. Technically, implementing a custom UI solution isn't difficult, but I would avoid doing that to prevent potential discrepancies between UI/renku-python

## API structure

Here is a proposal for API: https://app.swaggerhub.com/apis-docs/lorenzo-sdsc/renku-core/0.1.0
It's basically 3 commands to:
1. get the list of key/value pairs
2. set a new key or edit an existing one
3. delete an existing key

## Mockup

{TODO} -- The 2 mockups above should be enough for this issue

**Comment by ciyer** [comment]
> 1. Move the "Pinned image" on top, just after the "Default for new pods" to keep it in line with the Environments page.

I think it makes sense to keep "Pinned image" lower down because we would like to keep it hidden by default. I think this is a feature that is not relevant for many users, and we can keep the UI simpler by initially showing only the more commonly modified settings.

> 2. Add the possibility to set custom values for know fields (e.g. 16G of RAM, or any other random string) and new fields. When doing that, the value should be underlined in red/yellow with a note saying the value may not by valid in this RenkuLab deployment. We can get the list of available options and values from the `GET /notebooks/server_options` API.

That's a nice idea, but it could be down in a follow-up from my perspective. I think the more common case will be to define settings that will be valid for the instance that user is on.

**Comment by ciyer** [comment]
> ## API structure
> Here is a proposal for API: https://app.swaggerhub.com/apis-docs/lorenzo-sdsc/renku-core/0.1.0
> It's basically 3 commands to:
> 
> 1. get the list of key/value pairs
> 2. set a new key or edit an existing one
> 3. delete an existing key

Does it make sense to support setting/editing/deleting a collection of keys at once? With the current design, when the user clicks "Save", the UI might need to make multiple calls to the backend to update the settings.

**Comment by lorenzo-cavazzi** [comment]
> Does it make sense to support setting/editing/deleting a collection of keys at once? With the current design, when the user clicks "Save", the UI might need to make multiple calls to the backend to update the settings.

Ah yes, that's a good point! I have updated the APIs: https://app.swaggerhub.com/apis/lorenzo-cavazzi/renku-core/0.1.1

> > 2. Add the possibility to set custom values for know fields [...]
>
> That's a nice idea, but it could be down in a follow-up from my perspective. I think the more common case will be to define settings that will be valid for the instance that user is on.

If that's still desirable in the longer term, I think it's a limited extra effort to do all at once.
But yeah, we can put this in a follow up issue.
