### ISSUE TITLE
Minor changes to the issues components

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1119]
I was going through the First Steps tutorial again and I noticed a couple of minor details we may want to change in the UI in the "Issues" tab.

- On "create issue" we leave some blank space on the right side. If we reduce it, the markdown editor will show more options
<kbd>
  <img src="https://user-images.githubusercontent.com/43481553/98676135-7e20b180-235b-11eb-9a00-f07cde8b5c90.png">
</kbd>
-

- When we reply to a discussion, it would be great to use the same markdown editor we have for the issue creation. There is another blank space to the right that we may want to remove
<kbd>
  <img src="https://user-images.githubusercontent.com/43481553/98676823-65fd6200-235c-11eb-964f-47642ef4a7ff.png">
</kbd>
-

- When we reply to an empty discussion, the left space looks weird (it's fine when there are other replays though, see the case above). We could either remove that space when we are posting the first reply or add the current user image. The second solution may not be easy if we add the editor as suggested in the first point
<kbd>
  <img src="https://user-images.githubusercontent.com/43481553/98677347-31d67100-235d-11eb-9831-b941bb29353e.png">
</kbd>
-

**Comment by ciyer** [comment]
Made obsolete by #1361
