### ISSUE TITLE
Add project overview information

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#112]
_From @ableuler on February 9, 2018 12:24_

- Number of kus
- Number of notebooks
...

---
_Copied from original issue: SwissDataScienceCenter/incubator-renga-ui#39_

addresses https://github.com/SwissDataScienceCenter/renga/issues/135 https://github.com/SwissDataScienceCenter/renga/issues/146

**Comment by ciyer** [comment]
Merged with #365.
