### ISSUE TITLE
images not rendering in readme

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#1124]
using the usual markdown image syntax doesn't seem to render local images, e.g.

```
![alt-text](../path/to/image.png)
```

see e.g. https://dev.renku.ch/projects/rokroskar/test-vscode

**Comment by rokroskar** [comment]
This seems to have resolved itself after a refresh/reload...

**Comment by lorenzo-cavazzi** [comment]
I tried a few times with different browsers and I always get the image.
Should we close the issue or can you replicate it?

![Screenshot_20201116_083434](https://user-images.githubusercontent.com/43481553/99224465-a6d6fa00-27e6-11eb-98e3-027c3c988aac.png)

**Comment by ciyer** [comment]
Fixed by #1339.
