### ISSUE TITLE
latex rendering problems

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#1125]
The file preview seems to encounter render errors - compare gitlab:

<img width="940" alt="image" src="https://user-images.githubusercontent.com/3353586/99134584-aee43d80-261e-11eb-8226-bf44c5d47c5e.png">

with renkulab-rendered version:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/3353586/99134600-c4596780-261e-11eb-86a8-7cd7dec5cd6a.png">

Reference: at the bottom of this file: https://renkulab.io/projects/eng209/eng209-pandas/files/blob/notebooks/NumPy-Commandes.ipynb

**Comment by lorenzo-cavazzi** [comment]
Could you link the project/file with this error?

**Comment by rokroskar** [comment]
It's at the bottom of this file: https://renkulab.io/projects/eng209/eng209-pandas/files/blob/notebooks/NumPy-Commandes.ipynb

**Comment by lorenzo-cavazzi** [comment]
The linked projects are not available anymore, but we are tracking these problems here #1719
