### ISSUE TITLE
Support projects that want to use branches more extensively

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1131]
## Motivation

https://renku.discourse.group/t/pull-requests-via-renku-ui/193/2

> One feature that might come in handy, is the possibility to select target branch in a merge request. Currently this seem hard coded to “master”.

## Proposal

This is a reasonable request. One of the central goals of Renku is to make simple git-based workflows easy to carry out. Where possible, we also try to support more advanced use of the tools, but when these goals are in conflict, we focus on the simple cases and direct more advanced users to GitLab.

In this case, though, it should be easy to default the target branch to master and give users the option to select something else.

## Questions

Not yet understood is if this is a notebook-driven scenario, where notebooks are the only files that need to be diffed, or a more general scenario, where it is necessary to see diffs of all files.

**Comment by rollicks-c** [comment]
> Not yet understood is if this is a notebook-driven scenario, where notebooks are the only files that need to be diffed, or a more general scenario, where it is necessary to see diffs of all files.

I'd say anything that is beyond a simple merge (like fast-forward) should be done in gitlab. As soon as some git-flow knowledge is required, the user in charge will also be familiar with gitlab.

But in our use case, it would be a major benefit, if our non-technical users could just select the target branch for a merge request on the renku-lab. This would allow for scenarios with let's say a stable branch and an integration branch.

**Comment by lorenzo-cavazzi** [comment]
[Renku 2.0](https://blog.renkulab.io/renku-2) will disentangle Projects and Repositories.
