### ISSUE TITLE
Add template link and docker file version to migrations status

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1132]
After this is closed https://github.com/SwissDataScienceCenter/renku-python/issues/1729 we will be able to add a link to the template repository

i.e
![image](https://user-images.githubusercontent.com/42647877/99404869-682b6780-28ec-11eb-90bb-b7627b0b85f1.png)

And also we will get the docker version info that we can add as well.

# Late additions

We will also need a link to somewhere where the user can see the changes to the dockerfile, so they can decide if they want to upgrade or not (in case it is optional).

**Comment by lorenzo-cavazzi** [comment]
We now show the relevant information
