### ISSUE TITLE
Add volume size to server options selection for interactive environments

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#1136]
[This issue](https://github.com/SwissDataScienceCenter/renku-notebooks/issues/464) will give users the possibility (or force them ;) to choose the amount of disk space that they want to have available in their interactive environments. The UI should get the allowed range / options from the server-options endpoint, display an appropriate selection tool, and include the selected value in the `POST` request to the server.

**Comment by rokroskar** [comment]
Note that this option already exists in server options, it's just not used atm.

**Comment by ciyer** [comment]
I think this has been resolved in the meantime (amount of storage).

![image](https://user-images.githubusercontent.com/1196411/147932099-7e537c56-f80b-4379-bc50-3461eb4d33a1.png)
