### ISSUE TITLE
Support UI Plugins

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1140]
# Description

It will not always be possible to handle all content in the way all deployments want. To extend the possibilities, we should add a plugin mechanism. 

# Requirements
- Plugins are registered in the helm chart
- It is possible to add a plugin to the project page
- It is possible to add a plugin to the file view

**Comment by lorenzo-cavazzi** [comment]
The idea of extending the UI through plugins is still very interesting.
We might want to revive this at some point, but it should go through a ShapeUp pitch instead of a UI issue
