### ISSUE TITLE
feat(dataset): UI for editing dataset marquee image

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1142]
# Description

Once the core supports associating an image with a dataset, the UI should provide a way of editing/setting the image.

# Mock-up

![image](https://user-images.githubusercontent.com/1196411/101903842-3046d580-3bb5-11eb-9fe1-32854bf96fa4.png)

# Behavior

The UI lets the user enter a URL for an image. The field should behave like our issue comment editor: if they start typing a path, we try to resolve the path in the repository, giving help as a dropdown list.

If the URL is empty, then we let them pick an image from a list of stock images we have by scrolling through the list.

The selected image should be displayed in the image field.

# Progress

- [x] API Design (sprint-2020-01-08)
- [ ] UI Implementation

**Comment by vfried** [comment]
Check API design here...

https://github.com/SwissDataScienceCenter/renku-python/issues/1707#issuecomment-762296782
