### ISSUE TITLE
Fix react-router-dom behavior when a file name ends in a number

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1148]
I spent a bit of time checking the reason, then I remembered we already had a similar problem with URLs ending with numbers (probably when we used numeric ids for the projects).
We even left a comment here https://github.com/SwissDataScienceCenter/renku-ui/blob/e766ba1ce3e48757e01fb46fbe4ea944fd4ae825/client/src/App.js#L75

This is `react-router-dom`'s fault.

I tried a couple of solutions on the fly to remove the problem. The easiest would be fixing the API error that triggers the UI error feedback, but that's a nasty workaround because the UI would actually reload completely.
I can try to dig deeper and look for a better solution

_Originally posted by @lorenzo-cavazzi in https://github.com/SwissDataScienceCenter/renku-ui/issues/1137#issuecomment-731221699_

**Comment by vfried** [comment]
I found a solution for this i think... i just add the "/" before redirecting a user to a URL that finishes with a number.

If i want to redirect a user to file0 i will redirect the user to file0/ 

This might not be exact but i think it's what i decided to do when i had this issue

**Comment by vfried** [comment]
The refresh happens because the user is redirected to 

file0 and then in App.js it gets redirected to file0/ skipping the first redirection solves the problem

**Comment by ciyer** [comment]
The line in question is now here: https://github.com/SwissDataScienceCenter/renku-ui/blob/c7dce1f7e3394d3b4c486c64c0568be20b78b7da/client/src/App.js#L86
