### ISSUE TITLE
UX (project / dataset) :   make more visual

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1153]
# Description

The appearance of renku is very dry and text heavy. We want to be able to present the entities (projects, datasets) in a more visual way.

**Comment by lorenzo-cavazzi** [comment]
We made efforts in that direction since the issue was opened.
I'm closing this, but we should open specific issues if we have something planned, or have a discussion with POD and identify more precisely where/how to intervene.
