### ISSUE TITLE
Display fork status in the project status screen

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1156]
## Motivation

It's sometimes hard to know that something changed in the base project of a forked project and update it.

## Proposal

It would be useful to have in the project status screen a new section that tells the user that there are new changes in the project that they could pull to their project and a button that performs this operation if there are no conflicts.

**Comment by ciyer** [comment]
I agree 100% with the main point that it would be useful to know if an upstream project of a fork has changed.

We should think a bit about how we want to communicate that. The status tab is one potential location to put this, but it could also fit under collaboration as well.

**Comment by lorenzo-cavazzi** [comment]
[Renku 2.0](https://blog.renkulab.io/renku-2) will disentangle Projects and Repositories.
