### ISSUE TITLE
Gitlab subgroup support in the UI

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-ui#1157]
The UI currently mostly works with gitlab groups, e.g.

https://dev.renku.ch/projects/test_subgroup/test_subsbugroup/test_subsubsubgroup/subgroup_project correctly shows the project

https://dev.renku.ch/projects/test_subgroup/ shows a page for the group with a link to gitlab

But https://dev.renku.ch/projects/test_subgroup/test_subsbugroup/ results in a 404 page. It should probable show the same page about groups as above.

**Comment by ciyer** [comment]
Can you clarify how you got to this page? Was there a link to it somewhere, or did you get there by manually constructing the URL? If it is the first case, we can fix this. If it is the second case, we see it as a subset of #784, and we will close this issue since it will be handled as part of that one.

**Comment by Panaetius** [comment]
I think it was manually constructing it. And while playing around I thought it'd be nice if the different parts in the path here
![image](https://user-images.githubusercontent.com/664486/103915305-548dc780-510b-11eb-84f2-6b460934f82c.png)
were clickable.

**Comment by lorenzo-cavazzi** [comment]
[Renku 2.0](https://blog.renkulab.io/renku-2) will disentangle Projects and Repositories. There are plans to support (the new concept of) groups soon https://www.notion.so/renku/User-and-Group-Homepages-b43f877259584a30aaac4e5ea93b3e47
I'm closing this issue. The build team will open more specific issues
