### ISSUE TITLE
UX : design refresh

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1161]
# Description

Apply the changes to the look and feel specified by the graphic designer.

**Comment by ciyer** [comment]
One question to resolve is how we want to interact with Bootstrap. Bootstrap will be version 5 soon, and it's not clear if Reactstrap will support v5. React-Bootstrap now supports v4 and seems to have more momentum, so that might be an option. Or we can just use bootstrap directly / make our own wrappers.

- https://getbootstrap.com/docs/5.0/getting-started/introduction/
- https://github.com/reactstrap/reactstrap/issues/1748
- https://github.com/react-bootstrap/react-bootstrap/issues/5174

**Comment by lorenzo-cavazzi** [comment]
We updated to bootstrap 5
