### ISSUE TITLE
UX (collaboration): Support interactions with other branches and forks

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1162]
# Story

As a data scientist, I want to be able to explore branches other than the main branch of a project.

# Description

When working with others, we want to encourage use of branches and forks so data scientists can work without getting in each other's way. For this to work well, we need to support browsing, comparing, and merging across branches and forks.

**Comment by lorenzo-cavazzi** [comment]
This is being moved to a ShapeUp project https://www.notion.so/Branch-based-Project-Explorer-90a0fcbe1b254e3d8121c0c7e9831cd6
It is only a stub and it mainly focuses on branches. Please feel free to add any helpful content/information.

The pitch focuses on branches, while we don't have anything formalized for forks. There are other (less comprehensive) efforts in that direction https://github.com/SwissDataScienceCenter/renku-ui/issues/2168
