### ISSUE TITLE
feat(dataset): Display marquee image inside dataset

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1177]
## Motivation

This is a step towards making presentation of entities more visual.

## Mock-ups / Design

[coming]

## Stock Images
- Stock images will be kept as resources in the UI

## Questions

- We should show a special image if there is a marquee image for the dataset, but it cannot be resolved/retrieved.

# Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation for datasets inside the project
- [ ] UI Implementation for datasets outside of the project

**Comment by vfried** [comment]
Check API design here...

https://github.com/SwissDataScienceCenter/renku-python/issues/1707#issuecomment-762296782

**Comment by lorenzo-cavazzi** [comment]
We now show avatars for datasets, and a default when there is no user uploaded avatar.
