### ISSUE TITLE
Move DatasetListModel to global store

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1182]
`DatasetListModel` (in "client/src/dataset/list/DatasetList.state.js") defines a custom redux store. It's very similar to `ProjectListModel` and is should be moved in a similar way to the global redux store, while the functions should go to a new datasets coordinator. I'd suggest to wait for #1181 to be completed to leverage possible similarities.

Since datasets are used also in the project page, where data are saved in another custom store (`ProjectModel`) that needs to be moved, it could be a good idea to re-use the same coordinator (and possibly the same schema). As a reference, a similar approach is already used by "Environments".

Not sure about the required effort for this (pinging @vfried ) and how easy it would be to integrate the hook approach with the global redux store + coordinator.

**Comment by vfried** [comment]
I think this should be possible, and it could be a good example to move out of the "old react" on the project and other pages... I know that there are hooks for redux (useDispatch, useSelector) and I think that we should be able to find a hybrid solution for this. I could take a look at how this should work if you need me to.

https://react-redux.js.org/api/hooks
https://thoughtbot.com/blog/using-redux-with-react-hooks

**Comment by lorenzo-cavazzi** [comment]
We plan refactoring datasets to use RTK; this is not relevant anymore
