### ISSUE TITLE
Allow encoding data in the URL to automatically fill in new project fields

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1194]
## Motivation
Some users asked about the possibility to include encoded information in a new project URL to be applied immediately (e.g. repository URL and reference, template-id, visibility level, variables...)

## Proposal
We could include these data in the URL using query parameters, save the data from there to the redux store, and change the URL back to the standard one.

The main pain points of this approach are:
- How to include strings with reserved chars (e.g. a template URL): we could base64 encode the data, potentially even using a single parameter containing a JSON formatted structure. That would require clear instructions on how to create a proper URL.
- How to fill in dynamic fields not immediately available: most of the fields in the "new project" page are dynamically created based on the fetched content and/or on the other selected options. This means setting the `description` field requires to 1) fetch the templates, 2) select a specific template, 3) fill in the input. All operations require the previous to be finished, so they must complete in order. Even worse, some fields may be available immediately, but the choice will be limited when changing other fields (e.g. the visibility may be limited by the selected namespace, which is fetched and not available immediately).
The user could further mess up by manually changing a field in the meantime.
A possible strategy is to show a temporary page while fetching all the data and filling in the give values. That requires having clear precedences between the different fields, deciding a strategy to follow when something fails (e.g. can't fetch a resource, or a field that should be filled in doesn't exist).

- [x] Design (sprint-2021-01-29)
- [ ] Implementation

**Comment by lorenzo-cavazzi** [comment]
## Design

### Providing data
- We should allow the users to provide data to pre-compile any editable field. A reasonable would be to encode a json object and provide it through the `data` parameter (`btoa(JSON.stringify(data)`).
- We should get the `data` from the URL, store them in the redux store, and move from `/projects/new?data=(encoded)` to `/projects/new`. Otherwise, the user may believe he can modify a few fields and copy/paste the current URL to share the current data.
- The possible fields of the `data` object are: 
  ```
  data: {
    title, namespace, visibility, source, ref, template,
    variables: {
      <var_name_1>, <var_name_2>, ...
    }
  }
  ```
  Mind that 3 fields are missing
  * `identifier`: the user can't currently edit it
  * `template source`: we know it's selected when we get a `source` and a `ref`
  * `kg opt-out`: that field is going away soon
- To simplify the link generation, we can add a button to generate a sharable link with the current user input. I suggest changing the "Create project" button into a dropdown button with an extra field "Generate sharable link" (see the first screenshot). That should copy the URL in the clipboard and show a popover to inform the user about that.
  An alternative solution would be showing the link in a read-only input at the end, possibly hidden by default (see the second screenshot)

### Filling in the inputs:
- Some fields have pre-requirements: this means we can't just fill in everything, but we should do that gradually. We should disable any user input until all the provided fields are filled (or a step failed). A possible solution would be showing a modal (or an overly) informing about what is going on while fetching the required data (See the third screenshot).
- The easiest solution would be to fetch any extra data after the basic fields are available (i.e. wait for namespaces and basic templates to be fetched, then fetch whatever is required). This would avoid conflicts and allow the user to change everything without unexpected behaviors.
- The precedences are as follows:
  * `title` --> no precedence
  * `namespace` --> after fetching the namespaces
  * `visibility` --> after fetching the namespace visibilities
  * `template` --> after fetching the templates (or the custom templates when `source` + `ref` are provided)
  * `<template_variable>` --> after selecting the templates

### Refactory?
- The components would benefit from moving to the React hooks, but we have recently refactored this page. If we want to include it in the issue, we should consider a `+2` in the time estimation. I would skip this step for now.

### Screenshots
1. 
<kbd>
  <img src="https://user-images.githubusercontent.com/43481553/107262918-6da6d280-6a41-11eb-860a-8a7a8fbe858b.png">
</kbd>

---
2. 
<kbd>
  <img src="https://user-images.githubusercontent.com/43481553/107262988-80210c00-6a41-11eb-94fa-1b0bfd1c9355.png">
</kbd>

---
3.
<kbd>
  <img src="https://user-images.githubusercontent.com/43481553/107262997-81eacf80-6a41-11eb-8ad5-90a23c87612f.png">
</kbd>

**Comment by ciyer** [comment]
This is a nice design. I prefer option 1, where the create project has an optional menu and it would contain a "Copy project creation link" menu item.

I still do not completely understand the use case for this. How will the links be provided to users? Would it not be simpler to create a template where all the fields were provided default values?

**Comment by rokroskar** [comment]
The use-case is to include a renku link from third-party sites to e.g. facilitate making a new project to import a dataset to or to create a new project based on a specific template that the users of the third-party site would need and expect. Specific examples are to link from [materials cloud](https://www.materialscloud.org/discover/menu) and use their [own template](https://github.com/SwissDataScienceCenter/contributed-project-templates/tree/main/aiida)) or providing an ["external tool"](https://guides.dataverse.org/en/latest/admin/external-tools.html) for Dataverse. In order to support the Dataverse use-case, we would additionally need a possibility to add datasets directly on project creation.
