### ISSUE TITLE
UX (KG) : knowledge-graph-assisted contents navigation

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1197]
# Story

As a user, I want to leverage the information in the KG to navigate and understand the contents of a project and what has been done with them.

# Motivation

The lineage display is just one way of viewing information in the knowledge graph, and in many cases not the best way. The file view should make it possible to filter to files that according to criteria such as:

- input in a workflow, output in a workflow, somewhere in a workflow
- dataset
- code

Additionally, it should be possible to see which workflows an outputs dataset contributes to.

# Mock-ups / Design

## Project front page with KG information

![image](https://user-images.githubusercontent.com/1196411/106929889-379de180-6715-11eb-8e0d-8fd80b68692c.png)

## File view with KG information

![image](https://user-images.githubusercontent.com/1196411/106929973-513f2900-6715-11eb-8f1e-cd1fd6739acb.png)

## Dataset with local KG information

![image](https://user-images.githubusercontent.com/1196411/105970831-13ddfa00-608a-11eb-8af1-cfa37f1ce4ae.png)

# Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation

**Comment by lorenzo-cavazzi** [comment]
The idea was translated to a pitch here https://www.notion.so/Improved-Cross-Entity-Browsing-b64db297e2c74d6098ec1489787a770b
I'm closing the issue, but any relevant content could go to the pitch -- there is a cross-reference there already
