### ISSUE TITLE
feat(dataset): Display marquee image inside dataset listing

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1205]
## Motivation

This is a step towards making presentation of entities more visual.

## Mock-ups / Design

[coming]

## Questions

- We should show a special image if there is a marquee image for the dataset, but it cannot be resolved/retrieved.

# Progress

- [ ] API Design (sprint-??)
- [ ] UI Implementation for datasets inside the project (datasets list)
- [ ] UI Implementation for datasets outside of the project (datasets search) --> this could be a new issue

**Comment by lorenzo-cavazzi** [comment]
Done
