### ISSUE TITLE
UX (session) : sessions in iframe

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1220]
## Motivation

We want to provide controls for a session to make them easier to use. The session should be embedded in an iframe and the controls will be around.

## Mock-ups / Design

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/1196411/116212471-24fbdd00-a745-11eb-85e2-76c8c42e3dd0.png">

## Progress

- [x] API Design (sprint-2021-01-29)
- [ ] Initial UI Implementation (#1344)
- [ ] Improvements
    - show commit message
    - dropdown to switch endpoints (e.g., from JL to RStudio)
    - cheatsheet integration

**Comment by lorenzo-cavazzi** [comment]
closed by #1344
