### ISSUE TITLE
Notification for relaunching environment from auto-saved branch

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-ui#1244]
## Motivation
When new users come to Renku, they might not realize how the auto-save feature works. If they know that it was auto-saved, they might not understand how to launch the environment from the last-saved state. 

## Proposal
If there is an auto-save branch, show a notification explaining that the environment was shut down but the state was saved and can be relaunched. Bonus: Add a button to automatically launch the environment from the auto-saved state.

**Comment by lorenzo-cavazzi** [comment]
We addressed this already.
The autosave feature will be overhauled soon.
