### ISSUE TITLE
Force user to decide whether they want to create or import a dataset

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-ui#1245]
## Motivation
I was trying to import a dataset using a DOI but I was on the "Create Dataset" form. I didn't realize that there was a separate form for importing existing datasets. It would be nice to have stronger visual queues to tell me I need to decide which one I want to do. 

## Mock-ups / Design
Ideally, I'd like to see two buttons which say "Create" and "Import" or something before I see any of the form fields. At this point, there could be an explanation (possibly hidden with a "?" button) telling me in which case I want to create vs. import. A a non-data scientist, I don't know when I would want to create vs import.

**Comment by ciyer** [comment]
This is what the form looks like:

![image](https://user-images.githubusercontent.com/1196411/110119579-4af7a780-7dbc-11eb-9f06-4c540bfceba6.png)

![image](https://user-images.githubusercontent.com/1196411/110119670-68c50c80-7dbc-11eb-956e-06cb33839207.png)

Is the problem that text of the explanation isn't large enough?
