### ISSUE TITLE
Add Dataset Form: Error message when file URL is invalid 

### ISSUE THREAD

**Issue by travissarles** [SwissDataScienceCenter/renku-ui#1246]
## Description
When I paste an invalid URL (in my case a DOI) and try to click "Add file from URL", nothing happened. I didn't realize that my URL was invalid. It could be useful to have an error message which says "Invalid URL". If possible, it could be useful to detect if it's a DOI and tell the user to use the Import form instead. 

## Reproduce

1. Go to the "Add datasets page"
2. Fill out the form 
3. Paste a DOI into the files field which says "Upload a file using a URL" 
4. Click "Add file from URL" 

## Context

- renkulab url: renkulab.io
- operating system and version: Mac OS 11
- browser and version: Chrome

**Comment by lorenzo-cavazzi** [comment]
Can't reproduce anymore
