### ISSUE TITLE
feat: impose a hard limit on file size when creating dataset through UI

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1251]
## Motivation

The new feature that allows users to upload files and create a dataset through the UI can fail if the file size is large. 

## Proposal

Ideally the UI should enforce a file size limit that prevents users from uploading content larger than 500 MB when uncompressed. This should limit the number of errors users get when using this features and not paying attention to the disclaimer that mentions the potential problems with different file sizes.

Uncompressed aggregate file size limit: 500MB
Compressed aggregate file size limit: 100MB (I am not sure what a realistic compression rate is and I think it depends on the file size - hopefully this is good enough). 

There are ways that one can use this feature for nefarious purposes and upload a really small file that extracts to a very large file. Not sure exactly how we can prevent this 100%.

## Context

https://renku.discourse.group/t/problem-creating-dataset-in-frontend/252/5
https://swiss-data-science.slack.com/archives/CSWB66QF6/p1613676265004600
https://github.com/SwissDataScienceCenter/renku-ui/issues/1249

**Comment by ciyer** [comment]
We can use the jszip library to solve this, but we will need to fork and include this PR that has not yet been merged: https://github.com/Stuk/jszip/pull/520

**Comment by lorenzo-cavazzi** [comment]
The Datasets feature will be completely revised in the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
