### ISSUE TITLE
Integrate gateway into renku

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#127]
A proxy should be used to validate a request with keycloak and - if permitted - exchange the token before forwarding the request to gitlab.

For a more detailed description of this, please see the issues in https://github.com/SwissDataScienceCenter/incubator-proxy

**Comment by rokroskar** [comment]
@ableuler and @3C111 can you please expand the description of this as the definition becomes more concrete? Perhaps the title should also be changed to something more along the lines of what has been discussed
