### ISSUE TITLE
renku config options don't appear properly on the UI

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1306]
## Description

In the file `./renku/renku.ini` there are options for `renku config`s. For example, setting the `default_url = "/vnc"` will direct the 'connect' button to the vnc:

![image](https://user-images.githubusercontent.com/22785147/114392116-a0cc2600-9b98-11eb-9d12-cd7e10b140ec.png)

However, other options are not picked up. For example, after running `renku config set interactive.mem_request "4G"` and `renku config set interactive.cpu_request "1"`, these defaults are not selected in the UI:

![image](https://user-images.githubusercontent.com/22785147/114392081-9742be00-9b98-11eb-90f7-a0f54ec2bd41.png)

## Reproduce

1. Create an empty project and run  `renku config set interactive.mem_request "4G"` and `renku config set interactive.cpu_request "1"` from the terminal
2. Wait for the image to build and go to the environments page
3. See that the defaults are not shown.

**Comment by lorenzo-cavazzi** [comment]
Thank you for reporting that!
I fear something changed here SwissDataScienceCenter/renku-python#1834 and the UI doesn't support this change yet. Fixing it should be easy.
