### ISSUE TITLE
New project custom template inputs not correctly validated

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1307]
## Description

The input to the New Project > Custom Template sub form is not correctly validated. The _Repository URL_ is validated, but I can put anything into the _Repository Reference_ field and it will work.

![image](https://user-images.githubusercontent.com/1196411/114404716-43d76c80-9ba6-11eb-8660-1d5716fcfdb1.png)

## Reproduce

1. Go to the New Project form https://dev.renku.ch/projects/new
2. Select a _Custom_  template source
3. Fill a valid repo into the URL field (e.g., https://github.com/SwissDataScienceCenter/renku-project-template)
4. Put some nonsense into the _Repository Reference_ field
5. Click _Fetch Templates_. This will work.

## Context
- renkulab dev.renku.ch

**Comment by lorenzo-cavazzi** [comment]
I think this should be moved to renku-python.
We used to get an error from the core service in that case, now we get a valid answer.

> https://dev.renku.ch/api/renku/templates.read_manifest?url=https://github.com/SwissDataScienceCenter/renku-project-template&ref=213123
```
{"result": {"templates": [{"variables": {"description": "short description added at the beginning of the readme file"}, "folder": "python-minimal", "name": "Basic Python (3.8) Project", "description": "The simplest Python-3.8-based renku project with a basic directory structure and necessary supporting files."}, {"variables": {"description": "short description added at the beginning of the readme file"}, "folder": "R-minimal", "name": "Basic R (4.0.4) Project", "description": "The simplest R-4.0.4-based renku project with a basic directory structure and necessary supporting files."}, {"variables": {"description": "short description added at the beginning of the readme file"}, "folder": "bioc-minimal", "name": "R-Bioconductor (3.12) Project", "description": "The simplest R bioconductor-3.12-based renku project with a basic directory structure and necessary supporting files."}, {"variables": {"description": "short description added at the beginning of the readme file"}, "folder": "julia-minimal", "name": "Basic Julia (1.4.2) Project", "description": "The simplest Julia 1.4.2-based renku project with a basic directory structure and necessary supporting files."}, {"variables": {}, "folder": "minimal", "name": "Minimal Renku", "description": "The simplest renku project template with files for renku CLI and launching projects on renkulab."}]}}
```

**Comment by ciyer** [comment]
Makes sense. I was surprised by this because I was pretty sure that I had tested that before, and it reported an error as expected.

**Comment by lorenzo-cavazzi** [comment]
The reference issue (which references another issue :grin: ) has been fixed.
Testing this on the UI on dev.renku.ch confirms it's working as expected. I'm closing the issue, but feel free to re-open it if you can still reproduce this


![Screenshot_20210906_141001](https://user-images.githubusercontent.com/43481553/132215547-79b39f5d-ea59-4b57-b02a-94c564360bb2.png)
