### ISSUE TITLE
File display improvements in new design

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1328]
- [ ] Improve the way the buttons look, make them a bit more similar between each other.
- [ ]  Fix the scrolling for big files
- [x]  Allow the users to expand and shrink the files list on the right

_Originally posted by @vfried in https://github.com/SwissDataScienceCenter/renku-ui/issues/1315#issuecomment-826833384_

**Comment by lorenzo-cavazzi** [comment]
We now have different plans for the file browser https://www.notion.so/Improved-Cross-Entity-Browsing-b64db297e2c74d6098ec1489787a770b
