### ISSUE TITLE
Switch to a two column layout in the sessions/notebooks/environments form.

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1329]
Switch to a 2-column layout for the form, as here:

  https://github.com/swissdatasciencecenter/renku-ui/issues/1152

![image](https://user-images.githubusercontent.com/1196411/116199633-a0ef2880-a737-11eb-82c1-1dae1d41209c.png)

If it is an easy fix, we can go ahead and do it now, otherwise, we can merge this PR and make that improvement in another PR.

_Originally posted by @ciyer in https://github.com/SwissDataScienceCenter/renku-ui/issues/1318#issuecomment-827367670_

**Comment by ciyer** [comment]
This was fixed in #1386
