### ISSUE TITLE
Set up a WebSocket channel between client and server

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1338]
The UI client should connect to a WebSocket channel with the abilities to:
- [x] _[design]_ define the payload, a strategy to store the data both server and client side
- [x] get push notifications for generic events (e.g. started/stopped sessions)
- [x] handle tokens expiration --> this requires notifying the client when the credentials expire
~~- [ ] get push notifications for specific events for which the UI can subscribe/unsubscribe (e.g. new commits pushed to a specific project the user is visualizing)~~

The last 2 points require a sort of communication dictionary in both directions.
Expired credentials could be notified by the server with:
```
{
    scope: "authentication",
    data: "expired"
}
```
Requests to subscribe to `target-namespace/target-project` events could be notified by the client with:
```
{
    scope: "project",
    target: "target-namespace/target-project",
    data: "subscribe:all"
}
```
This requires to be expanded to cover more cases.

A stub of the first point is available in #1331

**Comment by ciyer** [comment]
We decided to just make minimal changes to prove that this is working on the client, we will later make the more extensive changes when there is a good opportunity.
