### ISSUE TITLE
Fix image rendering for images with relative paths in markdown/readme files

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1339]
## Description

Readmes containing images with relative paths are not being rendered in readme files, we should fix this.

## Reproduce

Go to this project and see that the images aren't being rendered
https://dev.renku.ch/projects/lorenzo.cavazzi.tech/aiida-2

We had fix this issue here https://github.com/SwissDataScienceCenter/renku-ui/pull/1008 but it looks like something isn't working.

**Comment by lorenzo-cavazzi** [comment]
fixed by #1353
