### ISSUE TITLE
Improve error messages when fork fails

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1341]
## Motivation

The fork operation is a two step process: 
1. Fork the project in GitLab
2. Run the CI pipeline to build images

Sometimes the first succeeds, but the second fails. The error message currently just says `An error occurred while forking: Renku API error`. This does not tell the full story.

See https://renku.discourse.group/t/error-during-forking-process-but-it-actually-finished-correctly/321

## Proposal

If the error occurs with the CI pipeline, we should show a different (non-error) message.

`The project was forked, but the images were not be built. You may need to build images before starting an interactive session.`

**Comment by lorenzo-cavazzi** [comment]
closed by #1351
