### ISSUE TITLE
Prevent getting outdated result in dataset search

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1352]
When the user searches for a dataset, it may occasionally take a bit longer (few seconds) to get the results, and it's possible to change the search entry and click again on the search button before the result is shown.
The latest query result will be ignored, showing the outdated result.

We can either:
- Prevent a new search while loading the content (i.e. disable the button and the search input when `fetching`)
- Discard the old result and correctly trigger and accept the latest query
- _From @erbou suggestion_: prevent new search while loading but allow to click on a `cancel` button while that is ongoing

I would go for the first solution since it's much quicker to implement and it prevents spamming searches (this probably isn't a problem for users, but it may cause loops in the acceptance tests when the query is slow to respond).
EDIT: the 3rd solution seems a very good alternative, though it would be one of a kind in the dataset search instead of a pattern applied to all the searches.

# Design

Disable entering new search terms while a search is in progress, but add a stop button for the search.

![image](https://user-images.githubusercontent.com/1196411/140494506-92958370-bfd7-4429-8ccb-bbf9ddf806e6.png)

**Comment by erbou** [comment]
Other options:

* The first option with a `cancel search` button: prevent new search until content content is returned or until search is cancelled.
* A combination of first option and second option: prevent the search until a timeout, after timeout allow a new query that discards old results and correctly triggers and accepts the latest query.

My preference as a user tends toward the `cancel search` option.

**Comment by ciyer** [comment]
Implement solution outlined in #1505.
