### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#136]
Currently, the ui doesn't raise and catch exceptions properly in many places. This should be addressed

**Comment by ableuler** [comment]
Partially addressed by https://github.com/SwissDataScienceCenter/renga-ui/pull/197, yet some more thing should be done: 

- [ ] Replace alerts by a more subtle "Sorry, something went wrong page"
- [ ] Make sure no errors go unnoticed by using `window.onunhandledrejection` at the top level of the application.
- [ ] Looking into/implementing react error boundaries (https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html)
- [ ] ...

**Comment by ciyer** [comment]
This seems to be superseded by work that has gone on in the past 18 months. Create a new issue to address current specifics if necessary.
