### ISSUE TITLE
Refactor file viewing

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#138]
- Implement a generic FileViewer component which can be used for all file types, as "standalone" component or within kus.
- Decide which URL pattern should be used for files inside the repository. Following gitlab this could be (http://base_url/owner/project/blob/ref/path/to/file)?

**Comment by ciyer** [comment]
Will be made obsolete if we pursue #1330.

**Comment by ciyer** [comment]
Made obsolete by #1330.
