### ISSUE TITLE
UI FIXES

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1402]
# Minor UI fixes

## Project datasets should use tiles

![image](https://user-images.githubusercontent.com/1196411/123231551-97383600-d4d8-11eb-8b3e-8aef1984cb30.png)

#### Fix colors in the KG display

**Comment by ciyer** [comment]
# Project Datasets

They now look like this:

![image](https://user-images.githubusercontent.com/1196411/124571972-8c6e9100-de48-11eb-8653-89ce4285e5d0.png)
