### ISSUE TITLE
Full screen iframe on sessions

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1407]
## Motivation

Users working on big screens would benefit from expanding the running session at (almost) full-screen size, especially given the hard limits on the horizontal extension of the page content.

## Mock-ups / Design

_From #1370_

We could add an "expand" button that extends the surface dedicated to the session (see red circle in the image below). We could extend to almost full-screen all the session area (blue rectangle). Consider also binding the resize action to pressing "esc" on the keyboard if it doesn't conflict with anything else in JupyterLab

![image](https://user-images.githubusercontent.com/43481553/120302895-9db70180-c2ce-11eb-9427-914450236e85.png)

**Comment by ciyer** [comment]
Replaced by #1988
