### ISSUE TITLE
Adjustable lateral window on files section

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-ui#1423]
Hey Renku team,

The new UI looks amazing, I truly love it! I have been playing with it, and I have a small request to make. It would be cool to make the following lateral window, where all files are shown, adjustable, mainly to allow expanding it, as it is currently difficult to read the file names, even on a large screen. Here you have an image showing what I am referring to:

![image](https://user-images.githubusercontent.com/8778401/125678315-6ec85100-4087-4fdf-847c-b7b7f32a230b.png)

Thank you so much, keep on making Renku cooler every day!

**Comment by ciyer** [comment]
Great suggestion! We will try to do something to make an improvement.
