### ISSUE TITLE
Duplicate session option

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1424]
## Description

If a numeric session option is selected, it is shown twice:

![image](https://user-images.githubusercontent.com/1196411/125777526-b477f0ad-f76d-4cf1-bdf1-f9bff226f6f0.png)

This only seems to happen for numeric options, not other ones.

## Reproduce

1. Click on `New Session`
2. On the form, change the CPU Request value to something else

You will see a duplicate.

**Comment by lorenzo-cavazzi** [comment]
fixed by #1440
