### ISSUE TITLE
iframe session not working for rstudio

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#1430]
Rstudio sessions seem to not display in iframes. Opening the same session in a new tab works. Note that this was on a freshly created r-based project from our templates, https://renkulab.io/projects/ableuler/another-r.
![image](https://user-images.githubusercontent.com/13014091/125988360-8414cdd5-928a-4112-8dc7-96c180b8e4f1.png)

**Comment by gavin-k-lee** [comment]
I also encountered this.

**Comment by ciyer** [comment]
So it seems to be working now:

![image](https://user-images.githubusercontent.com/1196411/129904960-b3d2ee9f-a219-4728-8ac6-8fb4359f7e61.png)

Not sure why you were having the problem before. It would be good to change the icon for the session tab from the Jupyter icon to R-Studio when that's the environment.

**Comment by ableuler** [comment]
Agree. I am 99.99% sure though that when I tried this (and it failed) at the same time and on the same instance the iframe session was working for a python session. I don't think I understand what has happened here, but things seem to work now.

**Comment by ciyer** [comment]
Closing as not reproducible.
