### ISSUE TITLE
Retaining filter by {Project, User, Group} in Project search

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1433]
## Motivation

When users have many projects under many groups they may be part of, searching for projects using the search bar is great. However, the option to additionally filter by User or Group are not available in the "Your Projects" or "Starred Projects" subtabs - it is only available in the "All Projects" subtab.

## Proposal

Add the filter by User/Group to all subtabs to enable additional sorting/filtering.

## Context

![image](https://user-images.githubusercontent.com/22785147/126759677-50110117-459d-42dc-b341-e997831a5b37.png)

![image](https://user-images.githubusercontent.com/22785147/126759802-0a71d494-daf0-4fc7-ab62-15b107a55f4c.png)

**Comment by ciyer** [comment]
This is a very good suggestion, and I have added it to the search improvements epic: https://github.com/SwissDataScienceCenter/renku/issues/1924
