### ISSUE TITLE
No image available

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1448]
## Description

The warning about no image being available seems to persist even when the image is available. That should be refreshed.

![image (1)](https://user-images.githubusercontent.com/43481553/129562576-2072b4db-4411-4141-8d6b-364803c31b51.png)

Users also pointed out that hiding the docker image availability info makes it difficult to understand what the user should do when the image is not available: it's not clear it's being build and waiting would be enough.

**Comment by ciyer** [comment]
Also consider the comment https://github.com/SwissDataScienceCenter/renku-ui/issues/1450#issue-971677211
