### ISSUE TITLE
session iframe too small

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1449]
We previously discussed adding an "expand" button on the session page to simulate a full window, but we temporarily decided against that solution #1370

Users who tried the new UI reported they feel the screen area for the session iframe is too small, therefore opening JupyterLab in a new tab as soon as it's ready.

While the "open in new tab" option is already available and it's a viable solution, we would like to keep the users in RenkuLab to provide additional information whenever needed. We could try to implement a full-window like solution

**Comment by ciyer** [comment]
This is been resolved by the new full-screen session window.
