### ISSUE TITLE
Create a quick feedback form for the new UI

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#1451]
## Motivation

It would be good to have a quick feedback form before we release the new UI so that users could give us feedback quickly and easily.

## Proposal

I think we should add a Feedback button on the footer...
![image](https://user-images.githubusercontent.com/42647877/130064469-7942afd8-47fa-4e03-a2ad-e174fcf16d7d.png)

This should open a page with a form containing basic fields and a text field for users to fill.
https://renku.discourse.group/

There is an issue here since the user should have an account on discord already to fill in a form, we could maybe use a renku-UI username for these posts instead.

**Comment by vfried** [comment]
We should maybe fetch the categories from the API and have a name, category and text field 

https://docs.discourse.org/#tag/Posts/paths/~1posts.json/post

**Comment by ciyer** [comment]
This was implemented in #1495.
