### ISSUE TITLE
Allow to go back to old UI

### ISSUE THREAD

**Issue by phgrosjean** [SwissDataScienceCenter/renku-ui#1464]
## Motivation

Allow to revert back to old UI during the transition period. Currently, it is possible to move to new UI from the old one on the main page. However, once it is done it is not possible to go back to the old UI anymore.

## Mock-ups / Design

Provide a similar button in the new UI that switches back to old UI during the transition period. The user could prefer the old UI for now, or because of bugs in the new UI in development.

**Comment by ciyer** [comment]
It is possible to switch back, but the button to do so is admittedly hidden. You need to log out, then you are returned to the landing page, and there you have the option to go back to the old version of the UI.

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/1196411/130666930-aaf6d71b-1758-432a-91a8-675225ac8ca4.png">

We can also offer this from the logged in home page, though.

**Comment by phgrosjean** [comment]
Ah OK. Thanks. So, I leave this issue open if you plan to offer it also in the logged in home page. Otherwise, it can be closed.

**Comment by ciyer** [comment]
Fixed in #1495.
