### ISSUE TITLE
GET /knowledge-graph/datasets/:id won't provide name for the hasPart items

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-ui#1497]
## Motivation

The new Dataset metadata does not contain information about the part `name`. Thus, the `GET /knowledge-graph/datasets/:id` won't be able to provide it anymore.

## Proposal

The UI may use part's `atLocation` as a name if needed.

**Comment by vfried** [comment]
I discussed this with Kuba, the has part is actually the list of files… I think the easiest thing we can do is on the client call, inside the .then() to split the file path with the .split(“/”) and grab the last element of the array there and add the “name” ourselves so we don’t have to change the code where we are using the name, I think this should work and it's a clean solution.

**Comment by vfried** [comment]
It should also be easy to release this change inside the old and new UI if we wanted to
