### ISSUE TITLE
list notebook servers in notebook tab

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#151]
In https://github.com/SwissDataScienceCenter/renku-notebooks/issues/4, we have implemented a simple UI for managing running servers.

Here, we can to create a tab within Renku that offers the same features.

In the UI `Notebooks` tab, we should show this list together with some sort of `Launch` button as well as a `Delete` button. The delete button should just send http `DELETE` to the server URL. 

# Implementation

The notebook server is using a HubOAuth object (https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/services/auth.py) to do authentication. I would expect that the UI can call the renku-notebook server API endpoint to list servers, providing the OAuth bearer token it has, and the server should allow it to have access, but this is not currently working. It looks like the HubOAuth object does not actually look for the bearer token, but instead uses some cookie that is set in some other part of the JupyterHub authentication process.

## Possible Solutions

* Find out how to get HubOAuth to use the Bearer token to identify the user
* Modify the implementation of the authentication decorator in renku-notebook to check the bearer token against GitLab 
* Make the API Gateway/proxy a client of JupyterHub which can call the relevant JupyterHub APIs directly and have the UI go through the API to get a list of running servers.

**Comment by jirikuncar** [comment]
You can compare it with a list of project environments which should contain also the not running ones.

**Comment by ciyer** [comment]
Superseded by #351.
