### ISSUE TITLE
Project datasets are not sorted

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1514]
## Motivation

The project datasets listing is not sorted in any way, making it difficult to find datasets if you have many.

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/1196411/136404465-c11ff87d-995c-4118-8321-c13d84a7fecb.png">

## Proposal

Sort datasets. We should provide a switch to allow alphabetical or most-recently-updated sorting (the latter can be default).

## Mock-ups

[coming soon]

**Comment by lorenzo-cavazzi** [comment]
We should sort by "last modified".
Sync with KG to be sure the property is already returned by the API in the last KG release

**Comment by andre-code** [comment]
## Proposal
Include "Sort by" component.
- Title: A to Z (default)
- Title Z to A
- Recently modified
-  Least recently modified

Cases:
1. Datasets already in KG, more than 1 in the list => Show component Sort by..

![Desktop - 1](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/b56a3a8f-9b16-42fe-ba40-f6fe023775d1)
![Desktop - 4](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/3c8602ca-ce98-4f4c-8313-8f481094b878)

3. Only one dataset in the project => Don't show component Sort by...

![Desktop - 2](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/fc84ecf1-f11d-462c-afcf-9f07d3e35be4)

5. **Special case**: Datasets not activated in Kg or partially activated (in process), In this case the list would have a dataset(s) without modification date, we could assume the creation date as the modification date.

Also remove the dataset list title

![Desktop - 3](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/8547a55f-0b36-4548-bf6e-3ac19f200344)

Depends on:  https://github.com/SwissDataScienceCenter/renku-graph/issues/1630
