### ISSUE TITLE
Enable project deletion through RenkuLab web ui

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#1527]
A user brought forward the suggestion of making it easier to delete a Renku project. I think this is a fair point, especially for showcases and short trials where people would like to completely clean up when done. I see two options:

1) Coding up the deletion through the GitLab API. 
2) Linking to the project deletion section on the GitLab UI which already has all the warnings and red banners about the irreversibility of this action 

Until we also have a project deletion endpoint on the knowledge graph (or on a dedicated projects service!) option number 2 is probably good enough.

**Comment by lorenzo-cavazzi** [comment]
We will do this through KG #2416
