### ISSUE TITLE
Grid search results alignment

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1551]
## Description

On the Dataset Search page, the left border of the grid search results are about 9 pixels away from the form elements. The results should probably be aligned with the form (which is the case in list mode), and we should see how things appear in other places where the grid display is used.

## Screenshot

![image](https://user-images.githubusercontent.com/1196411/140747949-68937bcb-b92d-4fbc-98c1-c4b559cc064c.png)

**Comment by lorenzo-cavazzi** [comment]
We changed the search page and the cards component.
