### ISSUE TITLE
Render math blocks in Markdown

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1552]
## Description

GitLab supports rending of LaTeX inside a `math` code block. 

![image](https://user-images.githubusercontent.com/1196411/140758070-eff4c248-6006-4f6d-bc01-5c4ee7a64116.png)

We should do the same in the UI.

![image](https://user-images.githubusercontent.com/1196411/140758131-4ffac484-1340-406f-996c-903979af483f.png)

See https://dev.renku.ch/projects/cramakri/mathjax

**Comment by lorenzo-cavazzi** [comment]
This may be a useful library for that https://www.npmjs.com/package/showdown-katex
