### ISSUE TITLE
Project creation and fork unavailable in inherited namespaces

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1555]
## Description

When access to sub-groups is inherited by access to a (super)-group, users cannot see the namespace option in the Renku UI. For example: Oksana and Gavin have Direct access to this subgroup, but Tao inherits it through `Learn Renku`.
![image](https://user-images.githubusercontent.com/22785147/141267698-7da827c1-a421-4966-bd48-35e03f717025.png)

Tao then only sees `learn-renku` as an option in the UI, whereas Oksana and I see both:
![image](https://user-images.githubusercontent.com/22785147/141267830-a357ae36-9ffa-4fc5-966b-e8b48a84f39b.png)

All members are owners.

## Reproduce

1. Create a group in GitLab
2. Create a subgroup within that group in GitLab
2. Add a team member (A) to the group
3. Add a different team member (B) to the sub-group
3. Check that (B) can make projects in the `group/sub-group`
4. Check that (A) cannot see the option of `group/sub-group`

## Context

- renkulab url: https://renkulab.io/gitlab/learn-renku/teaching-on-renku
- operating system and version: Mac/Linux
- browser and version: Chrome

**Comment by lorenzo-cavazzi** [comment]
Additional info: we are using the /namespaces API that apparently doesn't support returning inherited namespaces like the above example `group/sub-group` .
We may explore using the /groups API (combine with the `min_access_level` param) to get all the group namespaces.
![Screenshot_20211110_164834](https://user-images.githubusercontent.com/43481553/141269385-a24c890e-157a-40d5-992b-1dbdf9a74f0b.png)

**Comment by lorenzo-cavazzi** [comment]
As a reference, GitLab shows the proper content

![Screenshot_20211110_164815](https://user-images.githubusercontent.com/43481553/141269466-cdbf923c-c3e1-4c22-b751-2507ce3085b1.png)

**Comment by lorenzo-cavazzi** [comment]
Due to GitLab API limitations, we ended up restricting the requirements for creating projects through the UI on subgroups (i.e. needs to be maintainer level)
