### ISSUE TITLE
QuickNav does not work when on a project page

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1575]
## Description

In testing #1553 I found a bug that the QuickNav does not work correctly if you are on a project page. Also, it is possible to navigate the QuickNav results using the keyboard, but `Enter` does not select the project. That should be fixed as well.

## Reproduce

1. Go to the page of any project
2. Enter some text into the QuickNav box on the top of the UI
3. Click on of the projects, you will an endless spinning wheel.

![image](https://user-images.githubusercontent.com/1196411/142160118-0068fe5f-9e2d-474e-802a-4365c47918de.png)

![image](https://user-images.githubusercontent.com/1196411/142160162-f30d8938-12bb-4945-b7ba-72bbe9b6939a.png)

**Comment by suhhee1011** [comment]
@ciyer Can I work on this?

**Comment by suhhee1011** [comment]
@ciyer Thank you for accepting 👍 I need to set up the environment. Is there any document can help me?

**Comment by ciyer** [comment]
> @ciyer Thank you for accepting 👍 I need to set up the environment. Is there any document can help me?

Great! I need to first apologize and warn you first that this process isn't as easy as we would like it to be. There are instructions for running Renku on your computer here:

- https://github.com/SwissDataScienceCenter/renku/blob/master/docs/how-to-guides/admin/running_renku_on_minikube.rst

That describes the pre-requisites that first need to be installed on your computer. Once the pre-requisites have been installed, the steps for installing Renku on your machine can be followed. Let us know if you have any questions or get stuck.

(If you have access to a Kubernetes cluster, you might find these instructions easier:  https://renku.readthedocs.io/en/latest/how-to-guides/admin/deploying-renku.html)

**Comment by ciyer** [comment]
@suhhee1011 Were you able to set up an environment to develop against? One of the members of the team ended up taking this issue, but there are many others that are good candidates for a new contributor, so let us know if you are still available to work on something, and we can point you to some good issues.
