### ISSUE TITLE
Restore correct behavior when pressing Enter on project search bar

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1576]
## Description

Pressing "Enter" on the search bar in the top navbar should bring to the selected entry (of the first entry if none is selected).

## Reproduce

1. Go to the RenkuLab home page
2. Enter a word in the search bar
3. Press on "Enter"
4. The dropdown closes

![Screenshot_20211117_163704](https://user-images.githubusercontent.com/43481553/142231744-8c4662c0-c1b5-41cc-b088-134bd2396a13.png)

**Comment by mohammad-sdsc** [comment]
Moreover, when a search term is entered in the search box (or if one is selected from the drop-down list), pressing "Enter" key should initiate a search and show the results. Currently, search is done only when clicking the search icon.
