### ISSUE TITLE
Error when creating a project in a group namespace

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-ui#1581]
## Description

When creating a project in a namespace which is not owned by the user (`renku-qa` for example; I have a maintainer access to it not an owner one), an error message is displayed once the project creation is done (see the screenshot). The project is created and can be navigated to when clicking on the "Go to the project" button.

## Reproduce

1. Go to dev
2. Click on creating a new project menu
3. Select `renku-qa` as the namespace (use whatever you want for the other fields)
4. Click on "Create Project"
5. Wait for project being created and see the error message "Renku API error"

## Context

- dev
- macOS Big Sur, 11.6
- Safari, 15.0

<img width="1552" alt="Screenshot 2021-11-19 at 17 59 15" src="https://user-images.githubusercontent.com/50210674/142845205-70e91578-298b-4a27-b01d-9587ea5ee1e1.png">

**Comment by mohammad-sdsc** [comment]
I've tried this with and without whitespaces in project's name and they both resulted in the same error.

**Comment by lorenzo-cavazzi** [comment]
This was fixed recently -- we now allow creating projects only within owned namespaces
