### ISSUE TITLE
Utils folder refactor

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#1592]
## Motivation

The utility folder is growing a bit disorganized as it is not easy to recognize the files to store constants, helper functions, or UI components, these are spread between folders and files making it difficult to read and reuse what is already implemented as well as the maintainability of large files such as UIComponents.

## Proposal

- utils
    - components
        - formgenerator
        - quicknav 
        * FileExplorer.js
        * List.js
        * Markdown.js (RenkuMarkdown, MarkdownTextExcerpt)
        * Avatar.js (UserAvatar, ProjectAvatar)
        * FieldGroup.js
        * TimeCaption.js (displayTimeFromDate)
        * RenkuNavLink.js
        * Pagination.js
        * ExternalLinks.js (ExternalLinkButton, ExternalLinkText, ExternalLink, ExternalDocsLink, IconLink, 
                ExternalIconLinkWithTooltip, ExternalIconLinkWithoutTooltip, ExternalIconLink)
        * Loader.js (LoaderSpinner, LoaderBouncer, Loader)
        * Alert.js (RenkuAlert, InfoAlert, SuccessAlert, WarnAlert, ErrorAlert)
        * Icon.js (JupyterIcon)
        * Clipboard.js (Clipboard, 
        * Tooltip.js (TooltipToggleButton, standardToggler, TooltipToggleButton)
        * Button.js (ButtonWithMenu, RefreshButton, GoBackButton)
    - constants
        * Datasets.js
        * Media.js
    - helpers
        - sentry
        - url
        * Encoding.js
        * EnhancedState.js
        * HelperFunctions.js
        * ServiceWorker.js
        * Time.js
        * UseInterval.js

**Comment by lorenzo-cavazzi** [comment]
fixed in #1643
