### ISSUE TITLE
feat: allow more options for autostart

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#1596]
The session "play" button has been a really nice addition to the UI, and it is now even possible to provide users with a URL that they can share with others to automatically "land" in a running session. Currently, this behavior only allow starting from the latest commit on the main branch. It would be nice if, for the purposes of automatically generating links to be shared outside renku, we could add additional query parameters to the `<renku>/<namespace>/<project>/sessions/new?autostart=1` URL that would allow one to pre-select a branch and a commit for something like

```
<renku>/<namespace>/<project>/sessions/new?autostart=1?branch=feature?commit=12345abcde
```

In addition, one could imagine a drop down menu that would allow a user to copy the autostart link for easier sharing, like is currently done for pre-filling the new project form.

# Mockup

![image](https://user-images.githubusercontent.com/1196411/145547894-bb369587-4e06-4af6-86ad-2b828a0c5a3c.png)

**Comment by ciyer** [comment]
This should probably be easy, since the underlying support is there, we just need to get the info from the URL.

**Comment by rokroskar** [comment]
Perfect! cc @volodymyrss

**Comment by ciyer** [comment]
@rokroskar We have put together a mockup of how we imagine the UX for creating links. Is this consistent with what you had in mind?
