### ISSUE TITLE
Show expected migration time in UI

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1602]
## Motivation

The migration of a project can time some time. We should let the user know how long we expect the migration to take so they understand how long they may have to wait.

## Mock-ups / Design

*If* the project is being upgraded from a version < 1.0.0 to a version >= 1.0.0, show the expected migration time information. This can be retrieved from the KG.

![image](https://user-images.githubusercontent.com/1196411/145358240-565b50b3-e4de-471e-b072-a436f01fad02.png)

**Comment by lorenzo-cavazzi** [comment]
closed in #1621
