### ISSUE TITLE
Notebook status does not show correctly

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1606]
## Description

In the file viewer, when looking at a notebook, there is an icon that lets the user start a session or open the notebook in a session. 

This icon is not currently working (probably due to the project state refactoring)

![image](https://user-images.githubusercontent.com/1196411/145835681-b0699980-ccd3-4b20-8ac3-49a5fb56820c.png)

![image](https://user-images.githubusercontent.com/1196411/145835567-cdb07bf8-d6b6-44f3-8478-4ce39f3dcbea.png)

**Comment by rokroskar** [comment]
The icon works fine for me but clicking on it leads to the wrong URL: 

![image](https://user-images.githubusercontent.com/3353586/146377094-aa2526b4-8546-4014-80f0-f8f7882ac113.png)

![image](https://user-images.githubusercontent.com/3353586/146377135-50290d98-7aab-43ed-970a-1102c9e78732.png)
