### ISSUE TITLE
statuspage maintenance in popup is ordered incorrectly

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#1609]
The banned announcing upcoming maintenance windows shows the wrong maintenance first - see the current state at renkulab.io:

![image](https://user-images.githubusercontent.com/3353586/146216261-dbc3ead1-b790-4131-96a7-ec22883ef8ea.png)

It should show the gitlab maintenance pt1 first. In addition, there should be an indication that _multiple_ maintenances are upcoming so the user is aware that this is not the only one to consider.

**Comment by ciyer** [comment]
This is a browser-dependent problem. We are sorting the scheduled maintenances; the order is correct in Chrome but reversed in FireFox and Safari.
