### ISSUE TITLE
Link to instructions about migrating outdated project is broken

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1615]
The link to the instructions in the renku docs for migrating an outdated project is broken.

Curently (on renkulab.io) the link is:
https://renku.readthedocs.io/en/latest/user/upgrading_renku.html#upgrading-your-image-to-use-the-latest-renku-cli-version

![image](https://user-images.githubusercontent.com/16360283/146770560-0a0c7ac0-b1e2-496d-8d4c-45d33a2c8588.png)

I think it is supposed to be:
https://renku.readthedocs.io/en/latest/how-to-guides/upgrading-renku.html?highlight=migrate#upgrading-your-image-to-use-the-latest-renku-cli-version

**Comment by olevski** [comment]
The project I saw this on is here: https://renkulab.io/projects/tasko.olevski/test-999/overview/status

**Comment by lorenzo-cavazzi** [comment]
Thanks for reporting the issue.
We fixed it recently #1591 , we will make soon a new release that includes it
