### ISSUE TITLE
Display recently access projects

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1626]
# Use Case

As a user, I want quick access to projects that I recently look at, so that I can quickly get back to working on them

# Mock-up

Replace "Your Projects" with "Recent Projects"

![image](https://user-images.githubusercontent.com/1196411/148192959-412daa19-8e1c-408a-8471-f91b63f72178.png)

**Comment by lorenzo-cavazzi** [comment]
close in #1628
