### ISSUE TITLE
Renku UI Projects URL scheme

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#167]
Currently, we have the following URL scheme for information around a project:

Entity | URL
------|-----
Project Home | /projects/[project-id]/
Project Kus | [project-home]/kus
Project Ku |  [project-home]/kus/[ku-id]
Project Settings |  [project-home]/settings
Project File | [project-home]/[path-to-file]

There are a several problems with this:
1. Projects should be in namespaces, and the namespaces should be visible
2. Project URLs should use the project name instead of the opaque id
3. References to files should be explicit, not implicit since this may result in namespace collisions

For these reasons, the UI URL scheme should be changed to the following:

Entity | URL|Status
------|-----|------
Project Home | /projects/[project-namespace]/[project-name]|
Project Kus | [project-home]/kus|&#10004;
Project Ku |  [project-home]/kus/[ku-id]|&#10004;
Project Settings |  [project-home]/settings|&#10004;
Project File Listing | [project-home]/files/|&#10004;
Project File Lineage| [project-home]/files/lineage/[path-to-file]|&#10004;
Project File Content| [project-home]/files/blob/[path-to-file]|&#10004;

**Comment by rokroskar** [comment]
The title of this issue is "Renku URL scheme" but the description only refers to Projects - with #579 merged, can this be closed?

**Comment by vfried** [comment]
I changed the name, we can close it now.
