### ISSUE TITLE
2022 Q2 Framework Upgrade

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1726]
# Description

We update to the latest core components:

- Node v16 (https://nodejs.org/en/about/releases/) 
- React v18 (https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html)
- react-redux v7 (https://www.npmjs.com/package/react-redux)
- bootstrap 5.1.3 + reactbootstrap 9.0.1 (https://www.npmjs.com/package/reactstrap)

**Comment by lorenzo-cavazzi** [comment]
Done
