### ISSUE TITLE
Dataset do not work on projects with a default branch other than master

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1754]
## Description

Many dataset operations do not work correctly in projects where the default branch has a name other than master. See https://dev.renku.ch/projects/cramakri/main-as-main/datasets

We need to decide how we want to approach this problem. One possibility is generally supporting branches, à la #1162. Another is that renku core would checkout the default branch if no branch is specifically specified.

**Comment by lorenzo-cavazzi** [comment]
Fixed
