### ISSUE TITLE
session is said to be "Running" but "Open" button leads to 503 error

### ISSUE THREAD

**Issue by volodymyrss** [SwissDataScienceCenter/renku-ui#1796]
## Description

Happens for every session. 
I see what the interface is trying to convey to me, but as we are about to invite some more users, I am concerned they will be confused.

Session is said to be "Running" but "Open" button leads to 503 error

## Reproduce

![image](https://user-images.githubusercontent.com/3909535/163554489-00ac5205-102e-408d-b2bd-8123596fc1f4.png)

Clicking "Open" leads to

![image](https://user-images.githubusercontent.com/3909535/163554619-eac8a9f9-faf1-43bb-a86c-c153485be9f9.png)

* https://renkulab.io
* firefox

**Comment by lorenzo-cavazzi** [comment]
Thanks for the feedback!
You are right, that "Open" button should not be there anymore during the session startup phase.

In the past, we used JupyterHub, which provided a nice loading page transitioning to the JupyterLab environment as soon as that was ready. Now that is not the case anymore and the 503 error page is definitely not a good UX :grimacing:
