### ISSUE TITLE
UX (search): backend for saving the user's last search queries (keywords)

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#1804]
## Motivation
Reduce user effort to remember recent queries

## Proposal

Store all recent searches, in order to provide this data to the user the next time they conduct a search.
TBD if use REDIS as https://github.com/swissdatasciencecenter/renku-ui/issues/1627

## Context
![Screenshot 2022-04-26 at 12 29 03](https://user-images.githubusercontent.com/43388408/165358407-e584ba54-46b8-404f-9767-ead3870f9865.png)

**Comment by ciyer** [comment]
Fixed in #1875
