### ISSUE TITLE
UI (entity-search): Search Page

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#1812]
## Description

Display the result of the entity search as mockup attached.
The user must be able to search for entities, filter and sorting the results.

Integrate the logic for the searching [here](https://github.com/SwissDataScienceCenter/renku-ui/pull/1780) with UI for it #1808 and #1809 #1810

![Screenshot 2022-04-27 at 14 55 33](https://user-images.githubusercontent.com/43388408/165620510-5363cce0-878c-437d-ab35-07bba2034e94.png)

![Screenshot 2022-04-27 at 14 55 59](https://user-images.githubusercontent.com/43388408/165620576-2e8802fb-1bc5-402e-b39f-b7520418dec1.png)

**Comment by ciyer** [comment]
Fixed in #1869
