### ISSUE TITLE
User can be routed to /api/auth/None in some cases

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#1817]
I will add some more details and try to replicate this. This error was reported by Guillaume when someone tried to give him access to a non-public project but they did not give access to the right account. I.e. Guillaume has 2 different accounts on renkulab.

Here is what Guillaume observed:

> I tried to connect to a renkulab page ( at https://renkulab.io/gitlab/call-for-projects/) which Renku told me does not exist. 

I think the above makes sense since he did not have access (as he describes below)

> I am not sure that this is correct, maybe the message that I am getting is not correct, the page exists but I don't have access to it because I don't have the right credentials, and so I tried to login with other credentials
by clicking on the link that says
[Sign out and sign in with a different account](https://renkulab.io/gitlab/call-for-projects/#) and then I landed on an even less existing page: https://renkulab.io/api/auth/None

So the problem is that he was routed to https://renkulab.io/api/auth/None which should not occur. Especially not as a result of something that we prompted the user to do.

It also could very well be that this is more a bug on the gateway side. I will move it if that is the case.

For now please disregard until I add more info on how to reproduce. Because I have never seen this before myself.

**Comment by lorenzo-cavazzi** [comment]
I would guess this comes from the gateway -- or any other renku-python code. `None` does not exist in javascript, it's unlikely the `ui-server` generated such a link by mistake. It would rather be `/void` or `/undefined`.
Ofc the UI (server) may be the faulty part and somehow have triggered it by redirecting to a wrong URL.
