### ISSUE TITLE
Handle URLs pointing to datasets with the old dashed format

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1819]
## Description

The UI handles datasets with dashes (old format) by stripping out all the unneeded `-`.
This was implemented in #1694 , but we considered only the API responses, while users may have saved links like https://renkulab.io/datasets/2b4f3e51-5fb7-4cc0-9992-ad1d0de3e68c 

A very quick and easy solution would be to redirect to the hash-stripped URL

## Reproduce

Try the following:
- working: https://renkulab.io/datasets/2b4f3e515fb74cc09992ad1d0de3e68c
- broken: https://renkulab.io/datasets/2b4f3e51-5fb7-4cc0-9992-ad1d0de3e68c

**Comment by nperraud** [comment]
Thanks a lot
