### ISSUE TITLE
Post toolchain-update cleanup

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1823]
# Description

Issue #1782 upgrades react to 17, node to 16, and typescript to 4.5. There are some small problems that remain and some other frameworks that should be upgraded.

# Visual Problems

The handling for `.scss` files changed, and there is no longer a need to pre-process them, but the CSS results seem to be slightly different. Compare the new on the left with the old on the right:

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/1196411/167134389-d49d118a-e9fe-4d96-9e43-fba036ab30d3.png">

# Frameworks

- [ ] CKEditor (https://ckeditor.com/docs/ckeditor5/latest/installation/getting-started/frameworks/react.html)
- [x] reactstrap (see #1766)

**Comment by lorenzo-cavazzi** [comment]
These seem to be addressed in the current UI. Please re-open with updated details if relevant
