### ISSUE TITLE
UI/UX Upload dataset image component

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#1828]
## Motivation

Improve the user experience when loading the dataset image into the dataset addition form.

## Proposal

![Screenshot 2022-05-06 at 15 12 54](https://user-images.githubusercontent.com/43388408/167210312-b55f67a5-38a8-4725-b921-8cef09ceaba6.png)

**Comment by ciyer** [comment]
Great! I am looking forward to see your proposal.
