### ISSUE TITLE
Update Homepage CTA

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1834]
@lokijuhy commented on [Wed May 11 2022](https://github.com/SwissDataScienceCenter/ORDES/issues/488)

**Comment by lokijuhy** [comment]
Blocked by https://github.com/SwissDataScienceCenter/ORDES/issues/489

**Comment by lorenzo-cavazzi** [comment]
The product team will think about a more comprehensive solution for this
