### ISSUE TITLE
Create a sitemap for SEO

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1837]
As a Renku developer, I seek to optimize the RenkuLab.io web platform for our users throughout their user journey. I will provide a visual sitemap showing RenkuLab pages and their relationships to serve as a basis for SEO optimization, such as developing a dynamic XML sitemap, implementing a structured data markdown, and annotating with unique meta tags. The sitemap will be available as a Figma document to streamline further work on page importance and annotations. 

Additional context is available in [SEO plan](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan), including site map best practices, an example site map from Code Ocean, and a link to a site map test tool. 

**Acceptance criteria**
- [x] visual sitemap in **Figma/mermaid** with pages and their relationships (e.g. [Community template for sitemap](https://www.figma.com/community/file/1040665131833505769))
- [x] pages are annotated with the canonical version of the URL location
- [ ] pages are annotated with the existing meta tags

**Comment by andre-code** [comment]
are you planning to include links to the public projects? or just the general renku links like projects, datasets, sessions...?

**Comment by andre-code** [comment]
Site map proposal (not finished)

```mermaid
flowchart TD
      subgraph L1
        A(/)-->B(/projects)
        A-->C(/datasets)
        A-->D(/sessions)
        A-->E(/help)
        A-->AD(/search)
      end
      subgraph L2
        B-->G(/new)
        B-->H(/own)
        B-->S(/all)
        B-->I(/starred)
        B-->J(/:id)
        C-->W(/:id)
        C-->AF(/own)
        C-->AG(/all)
      end
      subgraph L3
        J-->L(/files)
        J-->M(/datasets)
        J-->N(/commits)
        J-->O(/issues)
        J-->P(/merge-requests)
        J-->Q(/status)
        J-->R(/lineage)
        J-->T(/edit)
        J-->U(/stats)
        J-->V(/new-session)
        W-->X(/add-to-project)
        J-->AC(/fork)
        end
        subgraph L4
        M-->Y(/:dataset-name)
        M-->Z(/new)
        V-->AA(?autostart=1)
        end
         subgraph L5
        Y-->AB(/modify)
        end
```
```mermaid
flowchart LR
      A(/)-->F(dev.renku.ch/github)
      A-->AH(datascience.ch/who-we-are/)
      A-->AJ(gitter.im/SwissDataScienceCenter/renku)
      A-->AK(renku.discourse.group/)
      A-->AL(renku.readthedocs.io/en/latest/tutorials/01_firststeps.html)
```

**Comment by lokijuhy** [comment]
@ksanao Is the above sitemap what you are looking for? (And is mermaid ok, or do you really want it in Figma?)

**Comment by andre-code** [comment]
> @ciyer and @andre-code: @ksanao and I reviewed together, and the mermaid diagram is great! Two points of follow up:
> 
> 1. Can you please also share the mermaid code for these diagrams?
> 2. To confirm acceptance criteria point 3- what are the tags currently present? Is it only the new tags added to the landing page, or are there other ones present?

Thx @lokijuhy 🙂
Regarding your points...
1. I have added the sitemap of the current status of the application, feel free to update it directly. Find here the documentation about Mermaid https://mermaid-js.github.io/mermaid/#/flowchart
2. All internal pages of the app use the same meta-tags as the landing page 😬.
