### ISSUE TITLE
Develop SEO plan with Coteries

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1838]
**Acceptance Criteria**
- [ ] Identify SEO measures to implement for Renku
- [ ] Issues for SEO improvements created in this backlog (Laura will help if wanted)

**Comment by lokijuhy** [comment]
Oksana: This is currently not a priority for the budget. Do #1841 first.

**Comment by ksanao** [comment]
https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan
