### ISSUE TITLE
Build up SEO backlog

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1841]
To increase Renku visibility, we'd like to Renku to appear in Google searches. For example:
* When a renku user googles the name of a project on Renku, we'd like the Renku project to appear at or near the top of the first page.
* When someone googles the name of a researcher, their renku projects should be listed. 

Increasing this visibility will require a combination of surfacing the proper metadata for Google to crawl as well as improving performance, so that Google is willing to put Renku near the top of the search results. 

**Acceptance Criteria**
- [ ] Discuss with ORDES to develop shared understanding of why/in what ways SEO is important for Renkulab
- [x] Research SEO best practices to develop a preliminary understanding of available approaches
- [ ] Create issues in the SEO section of this backlog for how SEO could be addressed for Renkulab

**Not in scope for this task:**
* Prioritizing the SEO backlog (will be done later during a backlog prioritization meeting)
* Starting work on any SEO development task itself.

**Comment by lokijuhy** [comment]
@ksanao started a Confluence page about SEO practices here: https://sdsc.atlassian.net/l/c/YPpZQJ1m

**Comment by lokijuhy** [comment]
ORDES will take a stab at this first

**Comment by gavin-k-lee** [comment]
hey @lokijuhy , oksana and I reviewed some of the metadata tags for the landing page here: https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan#Landing-page - those chosen are in **bold**. They could be part of the issues for the SEO sectioin of this backlog.
