### ISSUE TITLE
UI/UX tags on dataset page

### ISSUE THREAD

**Issue by cmdoret** [SwissDataScienceCenter/renku-ui#1845]
Renku allows users to version their datasets through a tags mechanism.
To provide a smoother UX around dataset versioning, users should be able to import specific dataset tags (versions), see https://github.com/SwissDataScienceCenter/renku-python/issues/2904

To inform users of the availability of tags for a particular dataset, the dataset page should display a list of available tags (potentially similar to [how Zenodo shows versions](https://zenodo.org/record/6551730) on the right of the page).

The tags list should:
* Be truncated (in case there is a large number of tags)
* Link to pages of previous dataset versions to allow importing them from the UI.

**Comment by ciyer** [comment]
We should prepare a design proposal for this.

**Comment by rokroskar** [comment]
@ciyer is this being worked on this sprint?

**Comment by ciyer** [comment]
> @ciyer is this being worked on this sprint?

Fleshing out the design is scheduled for this sprint, yes.
