### ISSUE TITLE
Add tags to the landing page

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1848]
As a Renku developer, I seek to optimize the RenkuLab.io web platform for our users throughout their user journey. When users do not know about Renku, the results of a web search engine influence their first impressions. Users and stakeholders complain that the information is unclear. I will update several essential meta tags to ensure that stakeholders deciding on funding decisions and future users have successful experiences during their awareness stage. Following best practices, these tags will briefly explain the value of Renku using essential keywords, such as open-source.

ORDES has developed an [SEO Plan](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan), which includes the list of meta tags that should be added.

### Current view when you Google "renku"
![image](https://user-images.githubusercontent.com/7387902/168608002-26bb211a-32b6-43c5-b95a-8b42a83edf66.png)

### Acceptance Criteria
- [ ] The **title**, **description**, and **social media** metatags listed in [SEO Plan - Meta Tags](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan#Fix-SEO-Meta-Tags) are implemented (tag text listed in bold in the "possibilities" column)

**Comment by ksanao** [comment]
@lokijuhy what do you mean it is not the same for Code Ocean, how did you check it?
It is the same with SEO site checker tool ([check here for full report](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan#CodeOcean)):
<img width="1151" alt="Screenshot 2022-05-16 at 18 43 36" src="https://user-images.githubusercontent.com/644935/168642492-92ebbf3a-474d-41f8-bd32-a8b366acadba.png">

**Comment by gavin-k-lee** [comment]
When we searched codeocean in Google we get this: 
![image](https://user-images.githubusercontent.com/22785147/168747942-4a3c97ba-8f25-46fa-bf45-f51e2c1e7250.png)

**Comment by andre-code** [comment]
Interesting, there can be several reasons, it can be an update of the description that google has not yet updated, this depends on how often the bot goes through the page to see what is displayed, the same could happen with us. It may take time to see our changes reflected in the google search result.

The best strategy would be to have the same text in the description tag and in the html.
