### ISSUE TITLE
Expose project metadata as JSON-LD markup/structured data

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1867]
Adding structured data to webpages allow Google to better show the page in search results.

[Understand How Structured Data Works | Google Search Central  |  Documentation  |  Google Developers](https://developers.google.com/search/docs/advanced/structured-data/intro-structured-data?hl=en)

Corner case: If there is no data available (i.e. because link to KG broken) -> don't show anything

**Open Questions**
- [ ] Do we need to differentiate between "public" and "published" datasets? (discussed in 2022-07-21 Renku meeting)

**Acceptance Criteria**
- [ ] Expose metadata from Renku projects as json-ld structured data. For a description of which exact fields to expose, please see the [SEO Plan confluence page](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan#Implement-structured-data).

**Comment by ciyer** [comment]
This documentation from Google describes an approach that we could use to add metadata from the KG to a project page:

https://developers.google.com/search/docs/advanced/structured-data/generate-structured-data-with-javascript?hl=en

**Comment by jachro** [comment]
So, we already have the `GET /projects` endpoint (more details [here](https://github.com/SwissDataScienceCenter/renku-graph/tree/release/knowledge-graph#get-knowledge-graphprojectsnamespacename)). At the moment you can ask for `application/json` only but I guess we could add `application/ld+json`. The only question I’d have is how much (and what) data we’d like the endpoint to return for that purpose. At the moment there’s quite a lot returned by it and, I guess it won't be a surprise for you if I'd say it would be nice if we don't have to change that quantity but only the shape. From the other side, I'm not sure if things like `statistics` are/should be put on the page as project metadata.

**Comment by andre-code** [comment]
Thanks @jachro .

@SwissDataScienceCenter/ordes What data do you want to include from the list of data shown [here](https://github.com/SwissDataScienceCenter/renku-graph/tree/release/knowledge-graph#get-knowledge-graphprojectsnamespacename)?

**Comment by gavin-k-lee** [comment]
Hi @andre-code , we have listed the initial list here: https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan#Corresponding-fields-that-we-want-initially.

It seems like from the `GET /projects` end point we don't have affiliation - @jachro is this something we can add, even if it might be empty at this point?

**Comment by gavin-k-lee** [comment]
Yes please, that would be great!
