### ISSUE TITLE
[timebox] Improve SEO Checkup score for the landing page to 80

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1880]
Low SEO rankings lead to missed opportunities to bring on users. We would like to improve the ["SEO Checkup" score](https://seositecheckup.com) of the RenkuLab.io homepage to a score of 80 (a value comparable to our competitors). 

At the start of the MIX feature team, the score was 60. After MIX Sprint 1, it was 64. After implementing #1878 and #1867, the score should be higher still.

It is up to the UI team to figure out what strategies they'd like to use to improve the score. The SEO checkup site has many suggestions, which can be found in the [SEO Checkup report saved in Confluence](https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/2315190295/SEO+Plan#RenkuLab).

**Acceptance Criteria**
- [ ] SEO Checkup Score as measured on [this site](https://seositecheckup.com/analysis#speed-optimizations) for https://renkulab.io is 80 or higher. _(Note: the free version of this site only allows 1 check per day)_

**Comment by ciyer** [comment]
This is an open-ended issue, since there is an iterative process to progress on this:

```mermaid
flowchart TB
    Start[Score < 80] --> Do[Fix greatest reward/effort ratio problem] 
    Do --> Check
    Check --> |Score < 80?| Start
    Check --> |Score >= 80?| Finished
```

We can time-box this to 2 days and see how far we get.

**Comment by ciyer** [comment]
Change of plan: we will first investigate the best approach for getting good SEO.  That means we will look at the tools report in greater detail and identify an approach for how we want to solve the problems. This could be

- Upgrade to React 18 and use code-splitting features there
- Introduce next.js
- ??

This issue is now a timebox that will be filled in later. Also include #1878.

**Comment by ciyer** [comment]
Replaced by
- https://github.com/SwissDataScienceCenter/renku-ui/issues/1908
- https://github.com/SwissDataScienceCenter/renku-ui/issues/1909
- https://github.com/SwissDataScienceCenter/renku-ui/issues/1910
