### ISSUE TITLE
Project page title tag should include the name of the project (to display in browser tab)

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#1881]
Previously, the title for a page in renku was "Renku", now it is "Reproducible Data Science ..." for better SEO, which is fine for the home page, but not informative for other pages.

<img width="815" alt="image" src="https://user-images.githubusercontent.com/1196411/171016299-ebfa61f0-ace5-467c-9f40-9714e928dc45.png">

**Projects**
* The title should be set to include the name of the project.
* Description to be the project description.

**Dataset**
* The title should be set to include the title of the dataset.
* Description to be the dataset description.

We probably want to use https://github.com/nfl/react-helmet for this.

**Comment by gavin-k-lee** [comment]
Should this also be done for Datasets, for example?

**Comment by lokijuhy** [comment]
> Should this also be done for Datasets, for example?

@ciyer Should we make a separate issue for putting the title of a Dataset in the title tag, or would you prefer that it be part of this task?

**Comment by ciyer** [comment]
I agree it makes sense to do this for datasets, but I would prefer a separate issue for that.

**Comment by ciyer** [comment]
Oh, yes, that makes sense and is a small extension. We can do that as part of this issue.
