### ISSUE TITLE
Add custom 404 page

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1910]

**Comment by ciyer** [comment]
Here is a design. Ask me for the vector image of the illustration (it is large)

<img width="3002" alt="image" src="https://user-images.githubusercontent.com/1196411/174066080-cc48dbdb-06cc-4b75-b16a-494977a024dd.png">

**Comment by lokijuhy** [comment]
It's so cute! 😍 Will the page still have the renku title bar at the top? I think the 404 page should have the renku name and logo somewhere.

**Comment by ciyer** [comment]
Thanks for that feedback! Those are good suggestions -- I will update the proposal.
