### ISSUE TITLE
As a user, when I google Renku, I want to see subheadings under the Google result (Sitemap?)

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1917]
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap?visit_id=637908830430262045-2961267211&rd=1

Let's start with the subheadings:

- Projects
- Datasets
- Documentation

Documentation might be hard to link to unless we have it explicitly in the sitemap though.

**Comment by ciyer** [comment]
Google does not expose the ability to control whether the results are displayed as subheadings or not.

  https://developers.google.com/search/docs/advanced/appearance/sitelinks

But having a sitemap makes sense and could be a factor.
