### ISSUE TITLE
Investigate options for measuring landing page user interaction

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1918]
1. How do we want to measure the success of the landing page?
Ideas:
    * Number of visits
    * Bounce rate (how many leave before completing another action)
    * Amount of time spent on the site, or sections of the site (heatmaps)
    * How much each of the CTA buttons are clicked
    * Source (whether they come from Google etc.)

2. Does Sentry provide that information?
    * Not for the marketing/landing page aspects we want to know about.

Note: Using Google analytics would require substantial (and time-consuming) changes to our privacy policy developed with the legal team.

---

Let's change this to scoping out HotJar or Mouseflow instead of Google Analytics.

Acceptance Criteria
- [ ] investigate nginx logs, HotJar and Mouseflow, Sentry, and more for renkulab.io landing page, and which of the above metrics they could cover.
- [ ] investigate whether there are GDPR/legal consequences of turning these on

Other Considerations
* Do we want a tool specific for the landing page, or do we want something that can be expanded in the future for the rest of RenkuLab.io?

**Comment by gavin-k-lee** [comment]
Since we are redesigning the UI, it would be great to have a way of measuring success between the old UI and new UI. This data would be really useful in forming some metrics around the Coteries work.

**Comment by andre-code** [comment]
|                                                                      | Hotjar                                                                                                                                                                                                                 | Mouseflow                                                                                                                                                                                    | Matomo                                                                                                                                                                                    | Lucky orange                                                                                                                                                                                                                                               | Smartlook                                                                                      | nginx logs                                                                                                                                                     | Sentry |
| -------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------ |
| Number of visits                                                     | yes                                                                                                                                                                                                                    | yes                                                                                                                                                                                          | yes                                                                                                                                                                                       | ok                                                                                                                                                                                                                                                         | ok                                                                                             | yes                                                                                                                                                            | yes    |
| Bounce rate (how many leave before completing another action)        | yes                                                                                                                                                                                                                    | yes                                                                                                                                                                                          | yes, visitors engagement                                                                                                                                                                  | yes                                                                                                                                                                                                                                                        | no clear                                                                                       | no                                                                                                                                                             | no     |
| Amount of time spent on the site, or sections of the site (heatmaps) | yes                                                                                                                                                                                                                    | yes                                                                                                                                                                                          | yes, adding it manually                                                                                                                                                                   | yes                                                                                                                                                                                                                                                        | no clear                                                                                       | no                                                                                                                                                             | no     |
| How much each of the CTA buttons are clicked                         | yes                                                                                                                                                                                                                    | yes                                                                                                                                                                                          | pending                                                                                                                                                                                   | yes                                                                                                                                                                                                                                                        | yes                                                                                            | no                                                                                                                                                             | no     |
| Source (whether they come from Google etc.)                          | no                                                                                                                                                                                                                     | yes (referer)                                                                                                                                                                                | yes, behaviour transitions                                                                                                                                                                | yes                                                                                                                                                                                                                                                        | no clear                                                                                       | no                                                                                                                                                             | no     |
| Forms analytics                                                      | yes                                                                                                                                                                                                                    | yes, pending testing                                                                                                                                                                         | yes, pending testing                                                                                                                                                                      | yes                                                                                                                                                                                                                                                        | no                                                                                             | no                                                                                                                                                             | no     |
| Allows regex for url to agroup all urls for projcts, datasets etc    | no                                                                                                                                                                                                                     | yes                                                                                                                                                                                          | yes                                                                                                                                                                                       | no                                                                                                                                                                                                                                                         | no                                                                                             | yes                                                                                                                                                            | no     |
| Recordings                                                           | yes                                                                                                                                                                                                                    | yes                                                                                                                                                                                          | yes, adding manually                                                                                                                                                                      |                                                                                                                                                                                                                                                            |                                                                                                | no                                                                                                                                                             | no     |
|                                                                      |                                                                                                                                                                                                                        |                                                                                                                                                                                              |                                                                                                                                                                                           |                                                                                                                                                                                                                                                            |                                                                                                | [https://docs.nginx.com/nginx/admin-guide/monitoring/live-activity-monitoring/](https://docs.nginx.com/nginx/admin-guide/monitoring/live-activity-monitoring/) |        |
| Users                                                                | \-                                                                                                                                                                                                                     | unlimited                                                                                                                                                                                    | unlimited                                                                                                                                                                                 |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| free account                                                         | \-                                                                                                                                                                                                                     | yes, 500records, 1month storage                                                                                                                                                              | no                                                                                                                                                                                        |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| price yearly                                                         | CHF372.00                                                                                                                                                                                                              | CHF288.00                                                                                                                                                                                    | CHF252.00                                                                                                                                                                                 |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| sessions/month                                                       | 3000                                                                                                                                                                                                                   | 5000                                                                                                                                                                                         | 50000                                                                                                                                                                                     |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| limits                                                               | 100 daily sessions, 365 days storage                                                                                                                                                                                   | 3 months storage                                                                                                                                                                             | 24 months storage                                                                                                                                                                         |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| GDPR                                                                 | [https://www.hotjar.com/legal/compliance/gdpr-commitment/](https://www.hotjar.com/legal/compliance/gdpr-commitment/)  [https://rating.wecontrol.io/technology/hotjar/](https://rating.wecontrol.io/technology/hotjar/) | [https://mouseflow.com/legal/gdpr/](https://mouseflow.com/legal/gdpr/)                                                                                                                       | [https://matomo.org/gdpr-analytics/](https://matomo.org/gdpr-analytics/)                                                                                                                  | [https://www.luckyorange.com/blog/posts/answers-to-your-gdpr-questions](https://www.luckyorange.com/blog/posts/answers-to-your-gdpr-questions)  [https://rating.wecontrol.io/technology/lucky-orange](https://rating.wecontrol.io/technology/lucky-orange) | [https://web.developer.smartlook.com/docs/gdpr](https://web.developer.smartlook.com/docs/gdpr) |                                                                                                                                                                |        |
| How join multiple pages in one heatmap                               |                                                                                                                                                                                                                        | [https://help.mouseflow.com/en/articles/4278272-combining-several-pages-into-a-single-heatmap](https://help.mouseflow.com/en/articles/4278272-combining-several-pages-into-a-single-heatmap) |                                                                                                                                                                                           |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| Pros                                                                 | integration with slack                                                                                                                                                                                                   | Great information on clicks, easy configuration, customisation dashboard, exclude content.                                                                                                   | Great adding custom urls, a lot of metadata about users behaviour, option to store the data in our servers but then we have to pay by plugin e.g heat-maps, data un Germany for paid account |                                                                                                                                                                                                                                                            |                                                                                                |                                                                                                                                                                |        |
| Cons                                                                 | No option to create group of links, useful for dataset and project links, head-map added manually                                                                                                                       | storage limited                                                                                                                                                                              | limited info about clicks, should add heat-maps manually                                                                                                                                   | No option to create group of links, useful for dataset and project links                                                                                                                                                                                   | No option to create group of links, useful for dataset and project links                       |                                                                                                                                                                |

**Comment by ciyer** [comment]
We have decided to use Mouseflow and Matomo. #1983 is the continuation of this work.
