### ISSUE TITLE
As a user, when I google my project or dataset name + renku, I want it to show up in the top search results

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1931]
Guaranteeing that the result appear at the top of the search results listing is probably not realistic, since there are factors outside of our control in realizing that, but we can make an effort to ensure that projects and datasets are indexed by search engines.

There are some questions that need to be resolved, though.

1. Should we feed every public project and dataset to the search engine, or do we want to impose some requirements that need to be fulfilled (e.g., a project should have at least N commits, a dataset should have a description, etc.)?
  -> No filters

2. How should we handle forks of projects? Should forks be indexed, or just the original project?
  -> only index the root project (not forks)

3. How should we handle versions (tags) of datasets? Same for forks of datasets should that concept be introduced?
  -> only index the original dataset

**Comment by gavin-k-lee** [comment]
I think we are just addressing the Findability aspect of Projects and Datasets here. Thus, I don't see any problem in indexing every public project? I think all forks should also be searchable - one could add a namespace keyword to their search.

**Comment by lokijuhy** [comment]
@gavin-k-lee A downside is that it would look perhaps "unprofessional" to google 'project-x' and get multiple nearly identical looking hits. (GitHub only does originals, not forks- I updated my comment in the description).

**Comment by gavin-k-lee** [comment]
Right, I see that. If we are able to identify the 'root' repository we can start with that.

**Comment by cmdoret** [comment]
For the same reason of avoiding multiple nearly identical hits, I think having the same behavior for datasets would make sense (i.e. only indexing the original one on search engines).

The only downside I can see with this is if the original dataset is abandoned and there are newer up-to-date forks. In the future, we'll probably need a way to navigate these dataset relationships (such as what was proposed in https://github.com/SwissDataScienceCenter/renku-ui/issues/1846).

**Comment by lokijuhy** [comment]
@ciyer We came to decisions for the 3 questions above. Is there anything else you need clarified here?

**Comment by ciyer** [comment]
@lokijuhy I think this is enough for us to get started. We will look at generating sitemap.xml files for projects and datasets that will allow them to be indexed as desired. It is possible that we do not have all the information we need from the KG, and we may need to create issues that will allows us to complete the implementation.

**Comment by andre-code** [comment]
We can extend the current sitemap to include links from the dataset and project sitemap, https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps.

The https://renkulab.io/sitemap.xml would possibly look like this:

````
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://renkulab.io/sitemapGeneral.xml.gz</loc>
  </sitemap>
  <sitemap>
    <loc>https://renkulab.io/ui-server-api/kg/sitemapProjects.xml.gz</loc>
  </sitemap>
   <sitemap>
    <loc>https://renkulab.io/ui-server-api/kg/sitemapDatasets.xml.gz</loc>
  </sitemap>
</sitemapindex>
````

Note: sitemapGeneral.xml.gz include the links of the current sitemap https://github.com/SwissDataScienceCenter/renku-ui/issues/1917
This sitemap can be generated directly from kg.
@jachro  here the expected format https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#sitemapformat
The expected sitemaps:
1. A sitemap for public projects, not including forks.
2. A sitemap for public datasets, the initial dataset not later versions.
Note: the sitemap only includes links (https).

**Comment by jachro** [comment]
Now, when I see the format I'm starting to have some doubts if KG should really return the data in this very specific rather UI format. I'm wondering if KG endpoints shouldn't rather return just pure data (json or xml) and UI(server) would simply turn that into the sitemap format. What do you think? Would that be fine for you?

**Comment by lorenzo-cavazzi** [comment]
Not relevant anymore
