### ISSUE TITLE
Explore solutions for Server Side Rendering

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#1934]
## Description

Use this approach to serve an initial payload with HTML, JavaScript, CSS that loads quickly containing the template or the complete content for some cases (landing page for unauthenticated users, help page and 404 pages) and then updates the data using react hydrate, this in order to improve search engine optimization (SEO).

**Comment by lorenzo-cavazzi** [comment]
We want to explore this sometime soon.

The main candidate is [NextJS](https://nextjs.org/), but also [Remix](https://remix.run/) was suggested and we might want to be sure we don't miss other potential solutions.

**Comment by lorenzo-cavazzi** [comment]
We discussed this and agreed on picking Remix. We will continue the effort through a ShaepUp pitch
https://www.notion.so/Make-project-links-render-nicely-when-they-are-shared-6b87dfb434c74b6a92e9386aad4a0984
