### ISSUE TITLE
Loading project message has no offset

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1943]
## Description

While loading a project, we show "Loading project <full-name>" and the bouncing dots.
The sentence is now displayed on the top left without margins. Probably we are not returning the external containers (`Row` and  `Col`).
We might also want to use the new progress bar instead of the bouncing dots.

![Screenshot_20220705_160514](https://user-images.githubusercontent.com/43481553/177347582-97d61db2-5022-42fa-acdd-cf6a7d3fb371.png)

## Reproduce

Try to hard-reload a project to get the message

**Comment by andre-code** [comment]
Fixed in #1949
