### ISSUE TITLE
Autosaves occasionally mess up with the "Start button" session

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1947]
## Description

Occasionally, having an autosave in a project mess up with the "Start button" when trying to start a session.
In the following GIF, I show how clicking on the "Start session" button actually triggers the "create sharable link" modal.

Deleting the autosaves _and after refreshing the list of autosaves_ (in the video by moving out an it the sessions page again) solves it.

![starting with autosaves](https://user-images.githubusercontent.com/43481553/184600008-02e4f94a-28a5-46e1-be9b-502ec6531bdf.gif)

## Reproduce

For some reason, I can't always reproduce it and I'm not sure why. In the video, I used a pet project on limited.
It seems plausible that the problem is in the `checkServer` function here https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/notebooks/NotebookStart.present.js#L1137-L1210

Not sure if something changed there (maybe check with renku-notebooks for the autosaves endpoint?), but the `.filter` function not matching the commit could cause the `toggleShareLinkModal` function to be triggered on the Start button instead of the `handlers.startServer`

## Actions

* [ ] Investiage the issue (and open issues in other repos if necessary)
* [ ] Fix the issue

**Comment by ciyer** [comment]
This is hard to recreate -- let us time box this to 1 day.

**Comment by lorenzo-cavazzi** [comment]
![starting with autosaves](https://user-images.githubusercontent.com/43481553/184600094-16fab23c-2499-438c-b864-07f09ee758ca.gif)
