### ISSUE TITLE
Define flows for "Refresh" button

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1956]
As part of targetting no/low code solutions and their users, we should implement clickable buttons to run certain commands, like `git pull`. Possible breakdown of cases (TBC with devs):
https://www.figma.com/file/5WnX17bEKxRN46XWVyDKWk/Refresh-button?node-id=0%3A1

Simplify flows for initial implementation, set scope for future rounds.

Could we lean into a Git GUI for this?

## Acceptance criteria
- [ ] confirm all possible cases for this flow

**Comment by ciyer** [comment]
The logic needed for this is described in https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1196.
