### ISSUE TITLE
Define flows for "Save" button

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#1957]
As part of targetting no/low code solutions and their users, we should implement clickable buttons to run certain commands, like `renku save`, or `git add -all; git commit -m 'message'; git push`. Possible breakdown of cases (TBC with devs):
https://www.figma.com/file/x1YHYNJA5PCHYztmAIvvMO/Save-button?node-id=0%3A1

Simplify flows for initial implementation, set scope for future rounds.

Could we lean into a Git GUI for this?

## Acceptance criteria
- [ ] confirm all possible cases for this flow

**Comment by ciyer** [comment]
We do not need to wait for the bigger redesign of the sessions flow to implement this, we can already put this into the UI and let users make use of it.



![Image](https://user-images.githubusercontent.com/1196411/179231694-12b06c58-6f99-4ac4-a57e-26ba1d50aba0.png)

**Comment by ciyer** [comment]
https://github.com/SwissDataScienceCenter/renku-notebooks/pull/762 should be merged at the end of the current sprint. That will make the infrastructure necessary for the save button necessary available

**Comment by ciyer** [comment]
https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1175 describes the logic needed to support this in the UI.
