### ISSUE TITLE
logout does not log out

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#196]
It doesn't seem like the logout from the drop-down menu does anything anymore?

**Comment by leafty** [comment]
Probable cause: no 'deep' logout, i.e. clearing of session from the third party login provider.

**Comment by ableuler** [comment]
This should have been improved by #198, yet I'm leaving this issue open as some things (for example logging out with the actual provider of the login (see the comment of @leafty) remain to be done.

**Comment by ableuler** [comment]
Will be resolved once the gateway is integrated into renku.

**Comment by rokroskar** [comment]
closing for now, waiting on #228
