### ISSUE TITLE
Implement no-code git Refresh button as defined

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#1986]
Is this ready to go after https://github.com/SwissDataScienceCenter/renku-ui/issues/1956 is done?

**Comment by ciyer** [comment]
Depends on https://github.com/SwissDataScienceCenter/renku-notebooks/issues/1196.

**Comment by ciyer** [comment]
In the implementation, please make sure to add cypress tests for the refresh and the save button (the latter, since they were skipped in the PR).
