### ISSUE TITLE
File browser scroll

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#1992]
## Description

We switched to a sticky file browser a while ago (i.e. scrolling down a long file should keep the browser anchored top-left). After the first implementation, a few other UI/UX changes went in, making the behavior sometimes buggy.

The following is an example of a file with little or no content (a directory works as well) and a file browser with many items. Scrolling down with the mouse wheel actually changes the height of the container and, after a while, moves the content to the right.

Tip to reproduce: keep the mouse pointer in the lower part of the file browser, and reduce the browser window height (or use a repo with _a lot of_ files)

![File browser expanding on scroll](https://user-images.githubusercontent.com/43481553/184098952-6055cf13-5e84-4bca-9ab2-a1c23718d843.gif)

**Comment by ciyer** [comment]
This page is a *great* candidate for using grid layout. I think that will make it easier to get nice code and results here.

**Comment by lorenzo-cavazzi** [comment]
Duplicate of #2336
