### ISSUE TITLE
Show dataset visibility on dataset card (blocked by KG)

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#2007]
Users should be able to tell if their dataset is public/internal/private. In order to show this in the UI, it needs to be made available in the KG.

![Image](https://user-images.githubusercontent.com/7387902/185120165-defef380-e8a6-49a4-84b8-83ab236e16a5.png)

**Comment by ciyer** [comment]
Gavin will coordinate with Kuba to resolve the semantics of dataset visibility. UI can implement once the KG side is in place.

**Comment by lorenzo-cavazzi** [comment]
That was done
