### ISSUE TITLE
Differentiate when user is logged in or not on the landing page for Metrics collection

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-ui#2011]
At the moment, renkulab.io shows different things depending on whether a user is logged in or not. If not logged in, you will see the landing page, and if you are logged in, you will see your 'dashboard'. 

This makes data collection from things like Matomo and Mouseflow difficult.

After discussions with UI, we find that the easiest thing to do is direct users to `renkulab.io/dashboard` if they are logged in and keep them on `renkulab.io` if they are not. This will separate these two cases.

**Comment by lorenzo-cavazzi** [comment]
This will be solved when implementing the dashboard.
P.S. filtering anonymous users should be simple since they have no username nor email
