### ISSUE TITLE
Do not strip certain cookies in ui-server

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2018]
Needed to implement core service scaling.

The sticky session cookie should not be stripped.

Followup from https://github.com/SwissDataScienceCenter/renku-python/pull/3094

**Comment by lorenzo-cavazzi** [comment]
A few info: the relevant code is here https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/routes/apis.ts#L45-L57
We can move the `proxyMiddleware` component to its own file. The name of the cookies _not_ to be stripped should possibly come from the values.yaml file (loaded in the `config` as usual). The function `getCookieValueByName` might come in handy here.
