### ISSUE TITLE
UI/UX (search): Show user projects that are not in KG

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2020]
## Motivation

Now that we have the cross-entity search that returns the entities that exist in kg, the user must have an alternative to find those projects that do not have active kg so it is not possible to find them in the cross-entity search.

The user must be able to:
- list projects that are not in kg
- have the option to activate kg to several projects in the list
- view the progress of activation

Rel [#1038](https://github.com/SwissDataScienceCenter/renku-graph/issues/1038)

**Comment by andre-code** [comment]
### Proposal
![project inactive in kg](https://user-images.githubusercontent.com/43388408/188137430-ab3e7468-74da-47e8-8d0f-f7b8fcd15b04.gif)


Figma File: https://www.figma.com/file/sgVkknWDUT7DLvLqGx51CN/Project-in-kg?node-id=0%3A1


### To define:
- [ ] Project information to display in the table
- [ ] All final texts (kg tooltip, page title, cross entity search message, activation button, confirmation no project to activate )
- [ ] Scope of this Issue, as the dashboard is not yet approved/implemented.

**Comment by lokijuhy** [comment]
@andre-code 
Responding to your "To define" points:
1.  Project information to display in the table
  -> I agree that Name, Namespace, and Visibility are must haves. Keywords doesn't hurt but is not necessary. Just a thought: would Renku Version be possible to list there? (in which case, in place of keywords)
2. All final texts (kg tooltip, page title, cross entity search message, activation button, confirmation no project to activate )
  -> I added comments in the Figma with suggested text revisions.
3. Scope of this Issue, as the dashboard is not yet approved/implemented.
  -> Do you mean, how do we handle implementing this before the Dashboard is implemented? As we discussed in today's Sync, could we query for whether the user has any non-KG projects, and if so, display a banner at the top of the users' homepage, a la my simple sketch:

![Image](https://user-images.githubusercontent.com/7387902/189168996-c666ff69-95bd-495b-a49f-96d19dd58f31.png)
