### ISSUE TITLE
links for creating renku prokect with prefilled template, namespace, visibility do not work

### ISSUE THREAD

**Issue by volodymyrss** [SwissDataScienceCenter/renku-ui#2026]
## Description

I am unable to create sharable links for creating renku projects, as appartent in the interface and advised by @rokroskar 

![image](https://user-images.githubusercontent.com/3909535/188923813-4ed43cbe-976a-4860-9989-e1152d0cd98f.png)

## Reproduce

https://renkulab.io/projects/new?data=eyJuYW1lc3BhY2UiOiJhc3Ryb25vbXkvbW1vZGEiLCJ2aXNpYmlsaXR5IjoicHVibGljIiwidXJsIjoiaHR0cHM6Ly9naXRodWIuY29tL29kYS1odWIvY29udHJpYnV0ZWQtcHJvamVjdC10ZW1wbGF0ZXMiLCJyZWYiOiJtbW9kYS1zbWFydHNreSJ9

it decodes to
```json
{"namespace":"astronomy/mmoda","visibility":"public","url":"https://github.com/oda-hub/contributed-project-templates","ref":"mmoda-smartsky"}
```
which makes sense.

Clicking on this leads to perpetual this:

![image](https://user-images.githubusercontent.com/3909535/188924026-71cec656-6921-4e1a-b7fc-a5509f7aa167.png)

<details><summary>Browser Output</summary>
<pre>
Uncaught (in promise) TypeError: this.getVisibilities is not a function
    e ProjectNew.state.js:221
    Babel 17
    value main.ab1ae2be5ab478f8bd77-8340587.chunk.js:2
    value ProjectNew.state.js:155
    n ProjectNew.container.js:458
    React 8
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 5
    value Model.js:158
    value Model.js:246
    value Model.js:232
    value Model.js:288
    value User.state.js:40
ProjectNew.state.js:221:13
    Babel 14
    value main.ab1ae2be5ab478f8bd77-8340587.chunk.js:2
    value ProjectNew.state.js:155
    n ProjectNew.container.js:458
    React 7
    _l self-hosted:1198
    Qi React
    unstable_runWithPriority scheduler.production.min.js:18
    React 4
    Redux 5
    value Model.js:158
    value Model.js:246
    value Model.js:232
    value Model.js:288
    value User.state.js:40

</pre>
</details>

I saw some issue about visibility in console so switched off visibility.

New link:

https://renkulab.io/projects/new?data=eyJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vb2RhLWh1Yi9jb250cmlidXRlZC1wcm9qZWN0LXRlbXBsYXRlcyIsInJlZiI6Im1tb2RhLXNtYXJ0c2t5In0

{"url":"https://github.com/oda-hub/contributed-project-templates","ref":"mmoda-smartsky"}

Does not get stuck but claims to fill something, but nothing is actually filled:

![image](https://user-images.githubusercontent.com/3909535/188924392-96332bee-12a5-4977-b049-cea64c585277.png)

I tried a couple of other combinations but no luck.

## Context

https://renkulab.io
Firefox 104.0

**Comment by ciyer** [comment]
Thanks for bringing this to our attention. I have been investigating this, and I can confirm the issues: 

* If namespace is selected, then the spinning wheel never goes away
* If **only** the template source is selected, then nothing gets filled out

Other scenarios do work for me, though. For example:

1. Specify a template source (URL + reference) **and** a template, then it works as expected:

https://renkulab.io/projects/new?data=eyJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vb2RhLWh1Yi9jb250cmlidXRlZC1wcm9qZWN0LXRlbXBsYXRlcyIsInJlZiI6Im1tb2RhLXNtYXJ0c2t5IiwidGVtcGxhdGUiOiJDdXN0b20vbW1vZGEifQ%3D%3D

(Nothing is filled in the top of the UI, but if you look further down, scrolling if necessary, you should see that the template repo and reference are filled out.)

2. Specify a template source, template, title, and description:

 http://renkulab.io/projects/new?data=eyJ0aXRsZSI6IlRlc3QgTU1PREEiLCJkZXNjcmlwdGlvbiI6IlRlc3QgTU1PREEiLCJ1cmwiOiJodHRwczovL2dpdGh1Yi5jb20vb2RhLWh1Yi9jb250cmlidXRlZC1wcm9qZWN0LXRlbXBsYXRlcyIsInJlZiI6Im1tb2RhLXNtYXJ0c2t5IiwidGVtcGxhdGUiOiJDdXN0b20vbW1vZGEifQ%3D%3D

So, some configurations work, and we will fix the problems with broken combinations ASAP.

**Comment by volodymyrss** [comment]
Yes, thanks, we can use the working combinations! It would be great to fill-in the namespace, but we did not really count on this anyway.

**Comment by ciyer** [comment]
Note for implementor: please implement some cypress tests for scenarios.
