### ISSUE TITLE
when creating renku project, groups where user is "Direct Member" are shown, and only those

### ISSUE THREAD

**Issue by volodymyrss** [SwissDataScienceCenter/renku-ui#2027]
## Description

when creating renku project, groups where user is "Direct Member" are shown, and only those. This misses indirect groups, and includes  groups where user has no right to create as a Guest.

## Reproduce

1. try to create renku project
2. see list of available namespaces
3. notice absence of non-direct gitlab user groups

## Context

https://renkulab.io/

**Comment by ciyer** [comment]
I'm investigating this problem, and my experience is a little different. In my case, I see groups where I have only maintainer and even only developer access in the new project / namespace listing in renkulab.

But there is one namespace I see in the Gitlab new project form, but I do not see in the Renkulab new project form. In this case I am the owner of the namespace! 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/1196411/189130213-8c58e489-e9e1-4d5f-b982-d57263e2f09e.png">

But, strangely, my access level is not shown when I list the namespaces of the group this belongs to:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/1196411/189130388-e88f2d0f-5532-410f-84d7-5a4dfbf10ffe.png">

In other cases, my access level is shown correctly:

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/1196411/189130931-12ff409d-e2ca-4ae4-8f7e-2fc1374c2265.png">

Can you tell me how old the namespaces are where you are having these problems? Could you also try creating a new namespace and tell me if the same thing occurs with the new namespace?

**Comment by ciyer** [comment]
Notes for the investigator:
- Check if the graphQL and the REST APIs return different information for the the namespaces of a user

**Comment by ciyer** [comment]
The REST API and graphQL API *do* indeed return different results.

We use the rest endpoint: `/ui-server/api/namespaces?per_page=100&page=1`.

GitLab uses the graphQL query: ```[{"operationName":"searchNamespacesWhereUserCanCreateProjects","variables":{"search":""},"query":"query searchNamespacesWhereUserCanCreateProjects($search: String) {\n  currentUser {\n    id\n    groups(permissionScope: CREATE_PROJECTS, search: $search) {\n      nodes {\n        id\n        fullPath\n        name\n        visibility\n        webUrl\n        __typename\n      }\n      __typename\n    }\n    namespace {\n      id\n      fullPath\n      __typename\n    }\n    __typename\n  }\n}\n"}]```

If we switch to using the graphQL query, we should get the right list of namespaces.

**Comment by ciyer** [comment]
As discussed in #2075, this is a bit more complicated than initially thought. We need to discuss with Laura and Rok how this should behave, based on that we can decide how to implement.

**Comment by lorenzo-cavazzi** [comment]
@volodymyrss this apparently simple issue turned out to be somewhat complicated.
In short, GitLab APIs are more strict than GitLab UI ( :scream:  ). Supporting a similar flow in RenkuLab would require extensive changes to our backend that we prefer to avoid since it would bind us even more to GitLab and we wish to support other repository management systems in the future.

The easiest solution would be limiting the namespaces where we allow users to create a project. They would need the same `owner` permission that user namespaces already require.
Do you think this solution would be a limit given how you use GitLab groups?

**Comment by lorenzo-cavazzi** [comment]
Tip for addressing the issue: the `GET /namespaces` API on GitLab has a very convenient `owner_only` parameter than we can use in this case
https://docs.gitlab.com/ee/api/namespaces.html#list-namespaces
