### ISSUE TITLE
Fully "shape" Coteries design for Project & Dataset page bodies

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-ui#2035]
* What in the Coteries design is not available currently in the backend?
* What items are in the current page body are _not_ in the Coteries design? -> Make explicit whether to remove or find a new place for it.

**Resources**
[Coteries Figma](https://www.figma.com/file/cmVH2YlFGz6uAv2EEH1sBZ/Renku---User-interface?version-id=2099751994&node-id=1%3A2)

**Definition of Done**

Midpoint
- [ ] List of open questions - to decide what we resolve ourselves vs send to Coteries

Final
- [ ] Revised Figma or detailed description of how exactly the Coteries design shall be implemented, ready for build.
- [ ] List of issues for things we want to add to the backend, if applicable.

**Comment by ciyer** [comment]
# Questions

## Overview

**Do we need these buttons?**

Can we remove these buttons? If we keep them, should they stay here or is another tab more appropriate? 

![1-Overview-1-buttons](https://user-images.githubusercontent.com/1196411/190371615-0ab4adb6-a52f-4f75-9732-2f161c50d675.png)

**How do we source this information?**

<img width="849" alt="image" src="https://user-images.githubusercontent.com/1196411/190374912-a7cbc54c-8e18-4e86-8090-3f8811cb07b4.png">

**Tab content?**

<img width="688" alt="image" src="https://user-images.githubusercontent.com/1196411/190388335-117a1fab-efd8-4d2e-9995-c23b593eddce.png">

**What happens to the content from the sub tabs?**

Where does the content on `Stats`, `Commits`, `Status` go? Do we remove it or move it to a new location?

<img width="183" alt="image" src="https://user-images.githubusercontent.com/1196411/190389840-9b4df66e-44a9-49d7-83f3-e3dd6b3f6f6c.png">

## Settings

What happens to this content? Where does it appear in the new design?

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/1196411/190390261-13cb4763-532b-400b-82eb-f26ec0d2d3eb.png">

**Comment by lokijuhy** [comment]
> 1. Do we need these buttons?
I think we need the "Fork" and "View in GitLab" buttons- those are both flows we use in demo'ing Renku and also for teaching use cases. I don't have a good sense for the Star button how much anyone uses it. In terms of these button's location, I think they should remain somewhere clickable upon initial page load (not within a different tab). 

> 2. How do we source this information?
* Institution: Ignore for the time being- we need separate work to enable adding this info to Renku.
* Creator: We have the first and last name for the profile that created the project, do we not? And could we do the same for the other profiles that have committed to the project?
* Papers: Ignore for the time being

> 3. Tab content?
I would recommend that the tabs for this next iteration are:
* Overview
* Files
* Workflows (will be available in ~2 sprints)
* Sessions
* Settings

> 4. What happens to the content from the sub tabs?
* Stats:

**Comment by lorenzo-cavazzi** [comment]
We don't need most of this anymore.
We will expand point 4 here https://github.com/orgs/SwissDataScienceCenter/projects/44/views/14?pane=issue&itemId=18472407
