### ISSUE TITLE
Improve UX when starting on an autosave branch

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2045]
The UI should provide more indications that the user is being brought to an autosave branch. #1879 should improve the situation once a session is started.

For the "Start with options" we should also provide some more explicit information about the existence of an autosave:

![Image](https://user-images.githubusercontent.com/1196411/191684981-dacc521e-f987-4cd9-97f5-29e3af796cfc.png)

The full-screen session view should also provide hints, but this still needs to be designed.

**Comment by ciyer** [comment]
Before starting on this, discuss with Rok.

**Comment by lorenzo-cavazzi** [comment]
Moved to a ShapeUp project here https://www.notion.so/Make-autosaves-not-be-so-bad-120264b524ce45d485d407c14a597fb6
