### ISSUE TITLE
Project search page keeps reloading/flickering

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2060]
I just noticed this on renkulab.io

Steps:
- search for a project from https://renkulab.io/projects/all?query=test
- the project is eventually found but the whole results section keeps flickering and reloading constantly, also the form for searching cannot be edited because the reloading resets the state and value of it (I assume)

I have not been able to replicate this. I thought it happened because I was searching for a project that is in the process of being created (i.e. was just created) but I could not get the same behaviour.

**Comment by lorenzo-cavazzi** [comment]
We now use the new `search` page instead of `projects` (it's still reachable manually as a backup but it's going away soon)
