### ISSUE TITLE
UX: Unify views when preparing a session and when starting a new session

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2064]
## Motivation
Provide a better UX where the process to start a new session does not require more than one screen or those screens are similar.

Current status:
1. Screen preparing a session
![Screenshot 2022-10-10 at 09 21 35](https://user-images.githubusercontent.com/43388408/194816140-e739c22f-2e01-4032-9512-48a5b3a349a2.png)
2. Screen starting a session
![Screenshot 2022-10-10 at 09 17 08](https://user-images.githubusercontent.com/43388408/194816183-01e63c69-f3c1-4d41-8220-5243ace5824d.png)

## Proposal

Using step-by-step progress loading in the session preparation screen.

**Comment by lokijuhy** [comment]
To make it clear to the user that if they go back during "Preparing Session", change the back button text from "back to <Project>" to "Cancel Session Start & back to <Project>".
