### ISSUE TITLE
UI kg-search glitches and testing

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2109]

**Comment by lorenzo-cavazzi** [comment]
This requires:
* Rebasing the code and adding a description (AC)
* Review the PR on the UI side (CR, LC)
* Ask for feedback to devs: fix bugs and create follow-up issues (AC)
* ? coordinate with Product team to involve users in testing

**Comment by lorenzo-cavazzi** [comment]
fixed by #2208
