### ISSUE TITLE
No-code pull/save buttons should provide feedback

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2118]
The buttons to pull changes and save changes should be more dynamic.

<img width="230" alt="image" src="https://user-images.githubusercontent.com/1196411/199935569-9d1df030-917c-496e-baad-abc7cef9c942.png">

The ui-server should poll the git status of the session. The "Save" button should be disabled, showing a tooltip that there are no changes to save, if the checkout is clean. If there are changes to save, it should be more visible (for example, colored in green). The "Refresh" button should be disabled if the checkout is up to date with the origin. If the the origin is ahead, the refresh button should be made more visible (for example, green).

**Comment by lorenzo-cavazzi** [comment]
Most of what's listed here has been implemented, except the changing colors
