### ISSUE TITLE
Fix Redis Sentinel support

### ISSUE THREAD

**Issue by seanrmurphy** [SwissDataScienceCenter/renku-ui#2140]
The current implementation does not have proper Redis Sentinel support, being unable to accept a list of sentinels. This issue arises in other services and there is Renku-Python issue open here:

https://github.com/SwissDataScienceCenter/renku-python/issues/3204

To fix it, it is necessary to:
- provide a mechanism by which a list of sentinels is made available to the UI server
- modify the UI server such that these sentinels are used in the config of the Redis client

The specific way that this info will be provided via the helm chart has not been decided yet.

**Comment by lorenzo-cavazzi** [comment]
To add some context, we currently:
* get the redis info from here https://github.com/SwissDataScienceCenter/renku-ui/blob/master/helm-chart/renku-ui/values.yaml#L29-L40
* made them available through this config file https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/config.ts#L71-L78
* set up Redis here using [the `ioredis` library](https://github.com/luin/ioredis) https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/storage/RedisStorage.ts#L36-L65

**Comment by leafty** [comment]
I think this is obsolete because `ioredis` supports Sentinel and we configure the connection accordingly.
