### ISSUE TITLE
ui: introduce form validation

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#217]
# Summary

Forms should provide feedback about which fields are required and which fields have errors.

# Details

Forms fields should have *bold labels* when a value is required. The field tooltip should also indicate if it is required or optional. Fields with invalid (non-empty) input should be marked in red and the error should be explained below the field. 

Fields should be validated on the client side as input comes in. Some validation can only happen on the server side, so it is also necessary to show errors from the server.

# Implementation

We have a model object for our entities. The model includes schema information which is used to perform validation, but, currently, the validation results are returned to the client. Instead, these should be stored with the model state, possibly in a separate channel.

# Bug Report 

Nothing happens when:
```
Project.js:64 Can not create new project - insufficient information:  Array(1)
0:
{description: "description must be provided and non-empty"}
```

Make `create project` form tell user what's wrong.

# From #255 

- [x] show which fields are required to create projects
- [ ] disable create button unless all fields are correctly filled-up

**Comment by ableuler** [comment]
All forms should be validated before POST-ing the data to the server.

**Comment by ableuler** [comment]
Good plan! Two small details to consider: 
- To me it seems a bit more common to mark required fields with an asterisk rather than bold font.
- From a tooltip I'd usually expect some information that I do not already have (if field is required or not), so maybe it could be a combination like "Required field - <Some-information-about-what-should-be-entered-here>"
