### ISSUE TITLE
Restore projects and datasets images

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2179]
## Motivation

We used to show images in projects and datasets -- both in the listings and in the descriptions.

![image](https://user-images.githubusercontent.com/43481553/205024313-948a9998-3d5a-4bc2-a9d0-bc753177be7c.png)

After the last design iteration, we removed them but the users want them back.
We now have a new design for that: we should re-add the images back.

## Mock-ups / Design

Figma files: 

* Project and Dataset Cards for listings -- including new position for visibility and type icons
    * [Figma](https://www.figma.com/file/abXsWrYhxeJ0GlkS7ypg7j/Project-and-Dataset-Cards?node-id=43%3A76&t=AJI3lGbO0Fd8CyJd-1)
    * [PDF](https://github.com/SwissDataScienceCenter/renku-ui/files/10152157/Project.and.Dataset.Cards.pdf)
* Project details with changes in the headers
    * [Figma](https://www.figma.com/file/AyZh0mKF2CY5nA48CuleRr/Project-Page-(Header-prioritization)-FINAL?node-id=25%3A447&t=DvCVd0l1FJAgrmr1-1)
    * [PDF](https://github.com/SwissDataScienceCenter/renku-ui/files/10152150/Project.Page.Header.prioritization._FINAL.pdf)

**Comment by jdupre81** [comment]
Hi, here is the link to the Figma file with the design of the image tool for the the project "I want my project images back".
If any question or changes are requested, please just let me know. Everybody can access and edit the file, but in case you want to make big changes please let me know, as the file a bit complex and some screenshots are locked. 

https://www.figma.com/file/sJS1EDIsYWe7MtFQ4G3eeM/I-want-my-project-images-back_Final?node-id=164%3A749&t=xFo0RQPZ3cews97X-1
