### ISSUE TITLE
Link to documentation about autosaves is broken

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2197]
When an autosave is present the link to the docs is broken.

For renkulab.io it points to `https://renku.readthedocs.io/en/latest/how-to-guides/session-stopping-and-saving.html#autosave-in-sessions` but it should go to `https://renku.readthedocs.io/en/latest/how-to-guides/renkulab/session-stopping-and-saving.html#autosave-in-sessions`

This is the link:
![image](https://user-images.githubusercontent.com/16360283/206176894-e4e3fef3-4be4-45b8-af32-8bd8d2758dc8.png)

**Comment by lorenzo-cavazzi** [comment]
Thank you for reporting it!
There were a few other outdated links, I just pushed a fix
