### ISSUE TITLE
ui: file tab structure

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#220]
The file tab should have 4 sub-tabs:
- All (show all files here)
- Datasets (show files in the data directory here)
- Notebooks (show only ipynb files here)
- Workflows (show files in .renku/workflow here)

**Comment by rokroskar** [comment]
An additional thing to consider: should "notebooks" be moved to their own high-level tab? The "Launch notebook server" button (i.e. a "blank" server without a specific notebook) would make more sense in that context IMO and should be made prominent and possibly renamed into something like "Create new notebook"
