### ISSUE TITLE
Add documentation about how to transfer project from personal namespace to non-owner groups

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2205]
## Motivation
Since the GitLab APIs are stricter than the GitLab UI, Renku only allows creating a new project or forking a project when the namespace has owner permissions after the Issue #2027.

This Issue is to document how users can transfer the project once it is created to non-owners groups.

Rel #2027

**Comment by lorenzo-cavazzi** [comment]
Renku 2.0](https://blog.renkulab.io/renku-2) has a different concept of groups and we won't need to rely on GitLab anymore.
