### ISSUE TITLE
Migrate NewProjectCoordinator to RTK query

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2206]
## Motivation

We will soon have a new project creation API from KG (https://github.com/SwissDataScienceCenter/renku-graph/issues/1635), which will include a bunch of operations that we currently do separately (E.G. invoking renku-core for the project initialization, changing visibility in GitLab, activating KG, adjusting name when required, ...)

Since the code is outdated and a bit buggy, the best approach is rewriting it and migrating to RTK query.
That includes all the content in the "ProjectNew*" files from the "/project/new" folder, and the templates APIs.

## Tips

There is quite some overlap in the logic in "ProjectNew.container" and "ProjectNew.state".
Reading through the code to understand the logic is highly recommended, but writing new components from scratch is probably easier than trying to convert them one by one.

There are a few details to keep in mind:
- The new project creation API already includes handling all details in GitLab and KG. We will need to invoke a single API to create the project.
- Those components handle both initializing a new project and forking an existing project. We can keep them together or separate, whatever works better. Do not underestimate the effort to migrate the components for the forking operations since there are a few intricacies.
- For the project creation (and to some extent for forking too), we invoke a rather convoluted function to catch errors early. That can be simplified. Also, we don't really need to fetch all the user projects to prevent duplicates but rather handle the backend error when that happens.
- There is quite some logic to handle links with embedded data in the `autoFill` function. Again, it's a significant chunk of work and it requires some changes but we cannot lose any functionality there. Do not forget to test it thoroughly!

**Comment by lorenzo-cavazzi** [comment]
As discussed, this isn't a priority anymore since we will phase out the old projects in the near future and we already introduce a different project creation page.
Closing the issue
