### ISSUE TITLE
Improve re-rendering of project/settings/sessions page

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2215]
When implementing the `Can view and modify settings` test in https://github.com/SwissDataScienceCenter/renku/pull/2837, workarounds had to be implemented because the UI kept re-rendering the settings. We should look at the UI code and stop the constant re-rendering. When this is done, the tests in the renku cypress-tests folder can be re-activated.

**Comment by lorenzo-cavazzi** [comment]
The issue might be similar to the one we fixed here #2144 -- i.e. related to nested `mapStateToProps`
