### ISSUE TITLE
Notebook Branching / Merging UI

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#223]
A common use case we will encounter is a user extending/improving a notebook. We want to offer a very simplified UI experience for for this case that will, behind the scenes, involve branching / merging, but keep the interaction simple and straightforward.

In the first version, we will offer two options:

- Merge to master w/o review
- Merge to master after review

## Merge to master w/o review

The Jupyter Notebook commit button will orchestrate the following:
  - commit changes to a branch
  - open a merge request from the branch to master
  - accept the merge request

If the accept fails, the user will be notified and be asked to manually merge

## Merge to master after review

The Jupyter Notebook commit button will do the following:
  - commit changes to a branch
  - open a merge request from the branch to master

The Renku UI will do the following:
- [x] When a project is accessed, load all merge requests for the project (https://docs.gitlab.com/ee/api/merge_requests.html#list-project-merge-requests). From this list, extract a list of notebooks that have pending merge requests -> see also #236 
(https://docs.gitlab.com/ee/api/merge_requests.html#get-single-mr-changes).
- [x] When a notebook is shown, check if there is a pending merge request on it. If so, display a button to review pending changes -> see also #238 

The review pending changes page will show the old and new version of the notebook, side by side, and provide a button to accept changes and another to reject changes. Accept changes will accept the MR (https://docs.gitlab.com/ee/api/merge_requests.html#accept-mr). Reject changes will require a comment and close the MR without accepting it.

(Later, when we have server notifications supported [#225], the server can trigger an update to the list of merge requests).

**Comment by ableuler** [comment]
Closed by #246
