### ISSUE TITLE
Group buttons in sessions not reachable

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2237]
## Description

When starting a new session "with options", some of the options might not be visible/reachable depending on how many options are provided and the window size. The worse combination seems to be "lots of options" + "medium size window".

![image](https://user-images.githubusercontent.com/43481553/208400495-ca74a3df-e55c-4e66-8a34-61f77c188336.png)

## Reproduce

This is easy to reproduce on limited since there are many options for both memory and storage.
To quickly reproduce the problem while developing, the easiest way is to add a few extra fake options to the response of the `server_options` API.

## Solution

We agreed on this solution https://github.com/SwissDataScienceCenter/renku-ui/issues/2237#issuecomment-1463891326

* Show separate buttons when there are few elements: that should be decided based on the number of elements + the characters contained in it.
    * try a few combinations to find a magic number: E.G: <num of chars> * <5 * number of elements> <= 20
    * _always_ show the button on 1 element
* Show a dropdown through a standard `<select>` element when there are mote elements

**Comment by jdupre81** [comment]
Dropdown menu - 2 drafts:


![Image](https://user-images.githubusercontent.com/117274853/213701832-823fbe34-22cf-457a-ae01-5d1ec79c0fb7.png)



https://user-images.githubusercontent.com/117274853/213701873-743739e7-884d-4199-adaa-ced1a2b6af99.mov
https://user-images.githubusercontent.com/117274853/213701874-2e1fb1cb-dd9e-4598-930b-b3b8e4b3428b.mov

**Comment by jdupre81** [comment]
https://user-images.githubusercontent.com/117274853/213712619-176f92de-ad7a-4211-9203-ea73f899a897.mov



![Image](https://user-images.githubusercontent.com/117274853/213712844-c8451d0d-4484-435f-89cc-0631015fdfd7.png)

**Comment by jdupre81** [comment]
![](https://files.slack.com/files-pri/T319Z06H3-F04LHGQMDQU/screenshot_2023-01-25_at_09.55.02.png)

**Comment by jdupre81** [comment]
<img width="519" alt="Screenshot 2023-01-25 at 09 59 27" src="https://user-images.githubusercontent.com/117274853/214521016-15492b9d-1724-4f91-9486-2c19ec52a121.png">

**Comment by jdupre81** [comment]
https://user-images.githubusercontent.com/117274853/214886407-2e8135f6-66b1-47b4-b3ac-4e06b9e2f17b.mov



![Image](https://user-images.githubusercontent.com/117274853/214886378-48e72dc5-02a0-4338-986f-6a789bd954ec.png)

**Comment by ciyer** [comment]
Draft 5 is very nice! Do we want to display the individual options as buttons or just make it a normal dropdown (options shown vertically, one per row) then?

**Comment by jdupre81** [comment]
here is an example of the normal dropdown (options shown vertically, one per row). 

I think that the only disadvantage here is space consuming and long scroll down when there are too many options. But I can imagine this can be a good solution for small screen devices for example.

https://user-images.githubusercontent.com/117274853/222475278-0ddcc305-6301-4157-9891-065e95a686e2.mov

**Comment by jdupre81** [comment]
As discussed on the UI POD meeting. Here is design proposal #7

https://user-images.githubusercontent.com/117274853/224285780-3ca6c846-ce8d-45e3-8929-f213dac1d17c.mov
