### ISSUE TITLE
Show commit message when selecting commits on "start session" page

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2240]
## Final mockup
_Updated_

This is the final mockup we should implement https://github.com/SwissDataScienceCenter/renku-ui/issues/2240#issuecomment-1405128483
We need to switch from a standard `select` element to a richer dropdown.

### Motivation

When starting a new session "with options", it's challenging to identify a specific commit in the "Commit" list, especially when there are many from the same user at close intervals.

![image](https://user-images.githubusercontent.com/43481553/208467174-ac42b1b3-cdec-4452-b2f8-1e8100d12344.png)

Some users suggested somehow showing the commit message, to at least part of it when it's too long.

### Mock-ups / Design

An idea could be switching the `select` element with a more complex dropdown input (as in the search) and try to fit in (the beginning of) the commit message.
⚠️ the element size should still be small enough.

![Screenshot_20221219_164940](https://user-images.githubusercontent.com/43481553/208469205-d6e20a32-9bde-4547-a33d-5eb389607efa.png)

**Comment by jdupre81** [comment]
Here 2 design proposals for this issue. 
FYI, maybe designs or prototypes are not perfect but they help us to have an idea of what could be the better potential solution

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/214023382-54658e48-b6fb-4157-9758-6758bd0b104e.png)



https://user-images.githubusercontent.com/117274853/214023400-4fe934d3-863f-49ee-8336-81ca6c2f77e2.mov

**Comment by jdupre81** [comment]
Option 2: I have included a filter which is currently not part of the commit visualisation. 

![Image](https://user-images.githubusercontent.com/117274853/214035462-de8f021a-da9a-4afc-ab69-e26d14832245.png)

https://user-images.githubusercontent.com/117274853/214035444-a6cd061c-2c20-4c3c-b94c-c7ed6fe67b40.mov

**Comment by till-m** [comment]
Hi @jdupre81,

I think the proposals you have posted are improvements over the current situation. However, in my opinion, the most helpful/identifying information for each commit is the commit message, so ideally that would be shown too. They are limited by git to 72 characters, which I understand might be a bit much but maybe even a shortened version would work?

**Comment by jdupre81** [comment]
@till-m thanks for your help! See new screenshot. Is this kind of the solution that you would like to see?

![Image](https://user-images.githubusercontent.com/117274853/214058366-ec951dc9-648d-4287-b6cc-e2343f469058.png)

**Comment by till-m** [comment]
Can't speak for everyone else, but this would definitely make my life easier @jdupre81!

**Comment by jdupre81** [comment]
@till-m your opinion is very important to us. Thank you very much for your collaboration ;)

**Comment by ciyer** [comment]
This looks good! Am I right that the only difference between option 1 and 2 is the addition of filtering functionality? 

I agree with Till that including the commit message is the core of this issue. A couple of suggestions:
1. I think it would look nicer if the times would all line up to form a column. We do not use a monospaced font for this information, so the time information can be offset between rows.
2. Could you try a version where the gap between rows was smaller (maybe using an alternating row background if necessary)? I think the information there could be compressed a little to accomadate more rows in the same space.

**Comment by till-m** [comment]
On the topic of dates/times, GitHub and GitLab have both elected to not show the time of the commit as absolute values, but instead use a human-readable relative-time ('an hour ago', 'last week', etc.) version. Maybe that's also worth considering here? This is already the case for at least one Renku page (see project Overview -> Commits).

<details>
<summary>GitHub</summary>

![GitHub commit history screenshot](https://user-images.githubusercontent.com/36440677/214249120-65222deb-31a2-4bf0-a3e7-2adf9aa5356a.png)

</details>

<details>
<summary>GitLab</summary>

![GitLab commit history screenshot](https://user-images.githubusercontent.com/36440677/214249604-c94d1414-8c30-41f3-9880-d722ee8e6209.png)

</details>

<details>
<summary>Renku</summary>

![Renku commit history screenshot](https://user-images.githubusercontent.com/36440677/214250967-d279cb91-3b0c-40e2-953c-25f21a048fc0.png)

</details>

**Comment by lorenzo-cavazzi** [comment]
@till-m that makes sense, it would make dates more human readable.

It's hard to preserve the alignment since usernames can be very different, breaking the columns. We could try to cut the username after the first N chars

**Comment by jdupre81** [comment]
> This looks good! Am I right that the only difference between option 1 and 2 is the addition of filtering functionality?
> 
> I agree with Till that including the commit message is the core of this issue. A couple of suggestions:
> 
> 1. I think it would look nicer if the times would all line up to form a column. We do not use a monospaced font for this information, so the time information can be offset between rows.
> 2. Could you try a version where the gap between rows was smaller (maybe using an alternating row background if necessary)? I think the information there could be compressed a little to accomadate more rows in the same space.

**YES, the filter is the only difference between the two options.** 
**ok. that's also a good idea, I will try your suggestion regarding the rows ;)**

**Comment by jdupre81** [comment]
here we go: Option 4

- Rows more compacted without background color, instead a slightly dotted line.
- Date/time more human readable. (e.g. authored 1 week ago).
- Colour and stroke differentiation for commit and date/time (bold and grey)
I am leaving the filter function for now, as I am not sure if it is helpful or not. We can discuss this on our next team meeting if you want. 

<img width="923" alt="Screenshot 2023-01-25 at 11 06 13" src="https://user-images.githubusercontent.com/117274853/214535387-2be5d7ae-a512-40f9-9630-8067a9cc8f3b.png">

**Comment by jdupre81** [comment]
As discussed, here the final design for the 3 viewport sizes (L, M, S)

[Final Figma File](https://www.figma.com/file/8G3atbeizkP9cMQCkqCBBY/Github-issue-%232240---Show-commit-message-...?node-id=41%3A774&t=PNRV1LUa16kRPmZV-1)

![Image](https://user-images.githubusercontent.com/117274853/214867075-a3145998-cb50-499e-a873-0ce4eae2f662.png)

**Comment by till-m** [comment]
Hi all, I realize it is a bit late to bring this up now, but how would this look with autosaves present?
