### ISSUE TITLE
"Launch Notebook Server" URL is broken

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#226]
This might be by design? It doesn't seem to yield the correct URL, however:

https://testing.datascience.ch/jupyterhub/services/notebooks/undefined/221d52a93f083ba12cc2f2382eef67748f256304/undefined?branch=master

![image](https://user-images.githubusercontent.com/3353586/40630668-c29c96f2-62d4-11e8-9077-993d78962bfa.png)

**Comment by leafty** [comment]
Might be useful to be able to make new notebooks that way.

**Comment by rokroskar** [comment]
yes, that's why I thought it's there and that this is intended -- but it doesn't work (the generated URL is invalid)
