### ISSUE TITLE
Publish storybook when deploying RenkuLab

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2300]
## Motivation

Making Storybook accessible on deployments allows UX/UI designers to interact easily with components. We could publish that as we do with the API swagger page.

Since it's an all-UI solution and we just need to serve static pages, it might be very easy to integrate this step into the UI-building phase. We should turn it on/off based on a variable in the values file.

Ref: https://storybook.js.org/tutorials/intro-to-storybook/react/en/deploy/

**Comment by lorenzo-cavazzi** [comment]
We can explore this after updating and fixing Storybook -- this requires #2212 and #2298

Let's explore a solution to publish Storybook 7 and timeframe it to a maximum of 3 days
