### ISSUE TITLE
Dashboard: Build the project dashboard

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2303]
Add dashboard project section.
Url:` / `only for authenticated users

cases:
- Users without projects: show alert to create a new project or follow tutorial
![Screenshot 2023-01-17 at 10 56 15](https://user-images.githubusercontent.com/43388408/212867151-3f2926fb-61ff-49d3-bcae-989b19c02392.png)

- The user has not visited any projects 
![Screenshot 2023-01-17 at 11 00 35](https://user-images.githubusercontent.com/43388408/212868138-35b30570-8a33-4e1a-ad78-85bc697f5591.png)

- The user has visited some projects (show max. 5 projects)
![Screenshot 2023-01-17 at 10 57 14](https://user-images.githubusercontent.com/43388408/212867369-0a72fa35-b0ed-4c34-bc45-7bba9d8fd94e.png)

**Comment by lorenzo-cavazzi** [comment]
Finished
