### ISSUE TITLE
Dashboard: Build the dataset dashboard

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2304]
Add dashboard dataset section.
Url:` / `only for authenticated users

cases:
- Users without datasets: 
![Screenshot 2023-01-17 at 11 02 57](https://user-images.githubusercontent.com/43388408/212869014-8b576da8-d2b4-4b12-8ca9-f17c6e548944.png)

- The user has datasets (show max. 3 datasets)
Note: use kg-search query by entity(dataset) and user
![Screenshot 2023-01-17 at 11 03 29](https://user-images.githubusercontent.com/43388408/212869201-881eeaad-8007-4f11-b23f-7a2cd6f0e725.png)

**Comment by lorenzo-cavazzi** [comment]
Finished
