### ISSUE TITLE
Dashboard: Include sessions in the project section

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2306]
If there are sessions in progress, include them at the top of the project list.
Note:
- Include all existing sessions + 3 recently visited projects (do not duplicate projects)
- Include recently visited projects to complete at least 5 cards 

![Screenshot 2023-01-17 at 11 14 26](https://user-images.githubusercontent.com/43388408/212871344-d22d3786-0680-444d-a59c-8bd38dd132f6.png)

**Comment by lorenzo-cavazzi** [comment]
Finished
