### ISSUE TITLE
🔶 SSH: verify ssh support on project pages

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2324]
We need to check whether a project supports SSH and show appropriate feedback.

We will get the information from the `GET /renku/check_migration` endpoint. We already do that when loading the project page to verify renku-core compatibility, so the change should be minimal.
[Here is the renku-python PR](https://github.com/SwissDataScienceCenter/renku-python/pull/3294) implementing the new response for the endpoint -- the new flag is `template_status.ssh_supported`. It can be tested [using this project](https://gitlab.dev.renku.ch/ralf.grubenmann/test-ssh-support).
Here is the link to the API on swagger:
https://renku-ci-rp-3294.dev.renku.ch/swagger/#/cache/get_renku_cache_migrations_check
Here is the renku-notebooks PR with the changes to the `GET /notebooks/version` endpoint:
https://renku-ci-nb-1389.dev.renku.ch

**EDIT**: some deployments will **not** support SSH. We can verify that by querying `GET /notebooks/version`. We should adjust the UI accordingly to prevent showing wrong information or commands that cannon be run.

### Showing the info
There are a few possible places:
* The project status page
* Somewhere on the project session page
* In the "start with options" page
  * Maybe just a label, ssh enabled or not? That info should come from the "renku.ini" file.
  * If it's more complex than this, or we can't just readf "renku.ini", we should create a separate issue for this

**Comment by lokijuhy** [comment]
### Laura-Lorenzo Discussion Notes
**Design Goals**
* Goal 1: User doesn’t remember which projects are SSH enabled, wants a quick way to tell
* Goal 2: Make users aware of SSH Access as a new feature (assuming most users do not read release notes!)

**SSH Project Status Indicator**

* Not supported on deployment → no icon
* template has `ssh_supported=false`
  * standard template → “Update your template!”
  * non-standard template → Docs on how to modify your template…
* template has `ssh_supported=true` → ssh enabled

**Comment by lorenzo-cavazzi** [comment]
We agreed on showing a new "SSH" option on the "Start" button that opens a modal.
The content includes links to documentation and how to enable the project to support SSH (or how to proceed).

No need to show anything on the project status page.

**Comment by jdupre81** [comment]
https://github.com/SwissDataScienceCenter/renku-ui/issues/2324#issuecomment-1413469186



![Image](https://user-images.githubusercontent.com/117274853/216693511-7408f0bb-cf56-4eec-a8b3-974609037629.png)

**Comment by jdupre81** [comment]
label ideas for the ssh support

![Image](https://user-images.githubusercontent.com/117274853/216694018-3f72d120-bbec-4aae-86ce-add86ffbc031.png)

**Comment by jdupre81** [comment]
this idea was presented and discarded right away.

![Image](https://user-images.githubusercontent.com/117274853/216694482-2b60cdab-1cb0-4269-a1f4-0e215d3a97e0.png)

**Comment by jdupre81** [comment]
https://github.com/SwissDataScienceCenter/renku-ui/issues/2324#issuecomment-1413469186

here is an example of the design template for the modal. Could someone please send me screenshots or links for the information that should be displayed on it ? ..

<img width="858" alt="Screenshot 2023-02-05 at 12 29 24" src="https://user-images.githubusercontent.com/117274853/216816151-cbb9e34c-a426-4e71-8b64-47a2846f8c8c.png">

**Comment by lorenzo-cavazzi** [comment]
We will show the SSH info only for "starting a session", not for a running one
