### ISSUE TITLE
Update cross entity search to sort on 2 parameters

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2335]
## Description

We are using cross-entity search and we [introduced a workaround here](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/features/kgSearch/KgSearchPage.tsx#L113-L115) to prevent getting older projects first when sorting by relevance without having any search entry.

Now KG supports sorting on 2 fields, so we should remove the above code and always sort for descending creation date as the second parameter.
We probably want to [introduce the change here](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/client/src/features/kgSearch/KgSearchApi.ts) so that, after the `sort` variable, we add the second parameter as a fixed string.

## New KG API

We can now send the query parameter multiple times, and the values will be considered in the same order they are sent.

> https://dev.renku.ch/ui-server/api/kg/entities?type=project&sort=matchingScore:desc&sort=date:desc

**Comment by andre-code** [comment]
Fixed in https://github.com/SwissDataScienceCenter/renku-ui/pull/2320

**Comment by lorenzo-cavazzi** [comment]
Closed in #2373
