### ISSUE TITLE
Test the new gateway and adjust the UI server (and client?) where necessary

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2386]
The UI server will "move" behind the Gateway and delegate all the Authentication tasks.
In the long term, it will essentially become a WebSocket service. For now, the tasks are:
- [ ] Adapt the UI server to the new Gateway.
- [ ] Change the routing in the UI client wherever needed.

**Comment by leafty** [comment]
This is probably not relevant anymore.
