### ISSUE TITLE
Improve the display of templates and add an SSH enabled badge

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2387]
## Motivation

We get the info on SSH support for templates when fetching the list of templates.

## Proposal

We should use that to show an SSH-enabled icon/text next to the template supporting it.

We will use the style shown here https://github.com/SwissDataScienceCenter/renku-ui/issues/2387#issuecomment-1462099847 -- consider the left-aligned text.

* Adjust the current style to match the one in the preview (mind removing the highlighted border that changes the card's size and adding proper padding)
* Add the flipped side of the card on mouse over with the description and the SSH icon _only on deployments supporting ssh_ (that info is already fetched with RTK query from the `GET /notebooks/verion` API). ℹ️ mind that very long template descriptions should not change the card size; show a vertical scrollbar instead

**Comment by lorenzo-cavazzi** [comment]
This issue is to potentially show an "SSH enabled" icon next to the templates that support SSH. 
That's on the "New project" page:
https://dev.renku.ch/projects/new

![image](https://user-images.githubusercontent.com/43481553/221192782-08eba0d9-c486-458c-af90-95789dc5e698.png)

**Comment by jdupre81** [comment]
First design proposal with different kind of solutions for this issue. 

https://user-images.githubusercontent.com/117274853/221594823-c7e599cf-8044-415f-863c-cad34eb416a1.mov


[Figma prototype](https://www.figma.com/proto/iGfF6bBWEvkPxmNkptpKoY/SSH-enabled-icon-for-templates-%232387?page-id=2%3A144&node-id=2%3A286&viewport=185%2C258%2C0.23&scaling=min-zoom&starting-point-node-id=2%3A286&show-proto-sidebar=1)

**Comment by ciyer** [comment]
Very nice proposals! I think they are all good, but I like the way the `Streamlit` template is shown the best:

* SSH badge in the upper right corner
* Card replaced with descriptive text in white/green bg on mouse over

I think the SSH badge with details on mouse over is a cleaner solution than always taking space on the card for the details. As to how the details should be shown, my preference is less pronounced: I think all the options are fine, but I do like the one mentioned above best.

**Comment by jdupre81** [comment]
Lorenzo's comment on slack: "I like the idea of swapping the card on mouse hover to show the description :100:
The one drawback is that the description might be too long to fit there.
For this reason, I believe the 4th card ("Julia" template) works best. I would probably make the SSH icon smaller  and cut the text to just supports SSH to fit in 1 line"

Lorenzo's design proposal

![Image](https://user-images.githubusercontent.com/117274853/222478236-aea6efd0-8c25-4846-9b8f-eceb8d71c9fb.png)

**Comment by jdupre81** [comment]
as discussed today. 
black mouse hover box. 


https://user-images.githubusercontent.com/117274853/224042194-59b26607-5785-45ad-8ac2-e6cdb5dfc4d6.mov

Here we have 2 options for the text alignment: centered or to the left. 
I have some tendency to the left alignment although probably the text in the middle makes a bit more sense when thinking about consistency. 

![Image](https://user-images.githubusercontent.com/117274853/224042305-6b994ee9-cca2-4c3d-9863-360c6132f698.png)

**Comment by ciyer** [comment]
This looks great! I also prefer left-justified text.

**Comment by lorenzo-cavazzi** [comment]
On longer description, we will cut the content and add the 3 dots at the end

**Comment by jdupre81** [comment]
@andre-code [design proposal update](https://www.figma.com/file/iGfF6bBWEvkPxmNkptpKoY/SSH-enabled-icon-for-templates-%232387?type=design&node-id=401%3A520&mode=design&t=hv6firK0ZajZj3xw-1) incl. Template **R (4.2.0) Project with Renv package managment**
<img width="904" alt="Screenshot 2023-09-06 at 16 39 38" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/71a5f5b6-7443-408e-ac95-47bcaa9bed9a">

**Comment by jdupre81** [comment]
As discuss today in our UI POD meeting and after some iterations with Andrea, here you have the video of the [updated prototype](https://www.figma.com/proto/iGfF6bBWEvkPxmNkptpKoY/SSH-enabled-icon-for-templates-%232387?page-id=448%3A5026&type=design&node-id=448-5029&viewport=161%2C135%2C0.25&t=oPXKL0eUfseLhTan-1&scaling=min-zoom&mode=design) . 

Please note that the text on the white boxes (by mouse hover) are just sample text.

https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/791b8426-42f7-4dcb-8564-eaee08c52f83
