### ISSUE TITLE
Starting with base image button does not work properly when image is pinned

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2395]
To reproduce:
- create a project (or pick an existing one)
- pin the image to something that does not exist - I just type a bunch of gibberish in the image name field
- go to start with options page
- the page will correctly recognize the image does not exist but it will allow you to use the "start with base image" button
- pressing the "start with base image" button results in a failure to launch the image because the POST request to the notebook service still uses the pinned non-existing image

The logic on the notebooks around this is as follows:
- if the image field in the POST request to launch a session is specified then there is no fallback to a default, if the image requested does not exist then we fail with a 404 and an error message stating this (the error message properly shows up in the ui too actually which is great)
- if the image is not specified we derive an image name based on the project and commit sha, if that image does not exist we use the default

So one way to fix this is to simply not request the pinned image when the pinned image does not exist and the user pressed the "start with base image" button.

**Comment by olevski** [comment]
Tested on dev.renku.ch with renku/renku-ui:3.2.0

**Comment by lorenzo-cavazzi** [comment]
### Additional info
When a pinned image is available, we invoke the `POST /servers` API with an additional `image` parameter. We should **not** do that when clicking on "start with base image".

![image](https://user-images.githubusercontent.com/43481553/221183835-aaacc31d-3830-41bd-9fe5-d9630f9f884d.png)

### Reproducing
* Project with pinned image **not** available: https://dev.renku.ch/projects/lorenzo.cavazzi.tech/pinned-image-broken
* Project with a valid pinned image: https://dev.renku.ch/projects/lorenzo.cavazzi.tech/1408-pinned-image
