### ISSUE TITLE
Error messages from failing sessions are hard to find

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2396]
I have seen this with multiple people using Renku. Most recently Till had this problem.

When a session fails. The status of the session is properly shown in the ui. However the error message that explains the failure is hidden in this small red icon. And it was not clear to Till (and several other people I have talked to) that you can click this small icon to see the message.

I think it would be better to display the error message more prominently or to make it clear that the little icon is clickable and also make it clear what contents it has.

![image](https://user-images.githubusercontent.com/16360283/221158825-c7747732-e4bf-42d1-a1eb-2ca5dd91db99.png)

**Comment by olevski** [comment]
Example what it looks like when the little circle is clicked and the message appears. Also clicking the text that says `Error` does not result in the message showing up - only the small red circle shows it.

![image](https://user-images.githubusercontent.com/16360283/221159094-bca44e1c-010b-44cd-bd2a-ea1435f149fa.png)

**Comment by olevski** [comment]
Tested on dev.renku.ch with `renku/renku-ui:3.2.0`

**Comment by lorenzo-cavazzi** [comment]
We should use the same solution we are currently using in the Dashboard: showing a popover on the bigger Error icon on the left

![image](https://user-images.githubusercontent.com/43481553/221181614-1b6b0398-dc58-4621-ac5c-21ba319c4861.png)

### Reproduce
Use this project to reproduce the error on dev.
