### ISSUE TITLE
Show timezone when showing times

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2402]
## Motivation

We addressed an issue with times not considering timezones (see #2388 ) but the UX might still be quite confusing since we still do not show timezones at all.

## Proposal

[As suggested here](https://github.com/SwissDataScienceCenter/renku-ui/pull/2388#pullrequestreview-1315511953), we should use an approach similar to GitLab, actually showing the time and the timezone. Looking at the following screenshot, we should display the timezone in a new line in a similar fashion, without changing other details about the styling of out popovers/tooltips.

### Suggestions
* Adding more structure to the Tooltips could be nice, but we can probably limit the effort by providing a single string for the timezone without whitespaces; this should guarantee decent word wrapping (from the screenshot, I assume GitLab is using a similar approach :detective: )
* We have a common component for showing times with a tooltip (`TimeCaption` iirc), but I fear we don't consistently use it. We should verify whether that's the case and either uses the common component or update the local code accordingly to show a similar text (:bulb: tip: check every place where we invoke `Time.toIsoTimezoneString` )

![image](https://user-images.githubusercontent.com/43481553/220574980-2c1ac439-adc6-4218-b158-8c447cfc81a5.png)

**Comment by StevyCoding** [comment]
Hello @lorenzo-cavazzi  can I take care of this issue ?

**Comment by StevyCoding** [comment]
@lorenzo-cavazzi Thank you for the update and the tips on how to properly address the problem. I appreciate it. Could you please let me know what the deadline for this task is?

**Comment by lorenzo-cavazzi** [comment]
It's not a high-priority issue so there is no internal deadline yet. Issues scheduled for a specific sprint are marked in the GitHub Project "UI sprint" and assigned to a specific sprint (you can see it in the right column under Projects).
We welcome your contribution whenever you have time :slightly_smiling_face:

**Comment by lorenzo-cavazzi** [comment]
closed in #2527
