### ISSUE TITLE
ui: partially reload project information on tab click

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#241]
When the content of my repo changes and I click on one of the tabs, I expect the content to be reloaded but it isn't. I have to do a refresh of the page with `Cmd+Shift+R` (on Mac) to get the new content to appear. Not sure if this is desired, but it may lead to confusion.

**Comment by ableuler** [comment]
I changed the title of this issue to narrow down the scope. Other aspects of the same problem and solutions to it (such as polling the server for data changes, see https://gitlab.com/gitlab-org/gitlab-ce/issues/5983) should be addressed in a separate issue.

**Comment by ciyer** [comment]
Fixed in #365.
