### ISSUE TITLE
Add a Delete button on project pages

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2416]
Now that we use the KG also for searching projects, having an out-of-sync state due to manually deleted projects is worse than ever.

KG implemented a `DELETE /project/<id>` API that deletes the project from GitLab and from our backend (Reference: https://github.com/SwissDataScienceCenter/renku-graph/tree/development/knowledge-graph#delete-knowledge-graphprojectsnamespacename).
We should add a button in the UI.

We might want to put it in a non-too-visible location (settings tab?) and adopt a similar style to GitHub: red button, opening a "warning modal" on click, asking to enter the project name as a confirmation.

We need some basic design for that.

**Comment by lorenzo-cavazzi** [comment]
This looks very nice!
I feel we don't need a dedicated sub-section only for deleting projects. What about fitting this in the current `General` section? Or perhaps create an `Advanced` section where we fit "delete project" and potentially other actions in the future.

**Comment by ciyer** [comment]
I also think this looks great, and I agree with Lorenzo about not needing a dedicated sub-section. My vote is for adding this to `General`.

**Comment by ciyer** [comment]
I also wanted to add that we need to do some thinking about the content of the dialog box. `Issues`, `Merge Requests`, and `Stars` are all not visible in Renku, so I do not think we should mention them. `Forks` makes sense, but maybe we want to mention `Datasets` and `Workflows` as well?

**Comment by jdupre81** [comment]
Delete box in the General section

![Image](https://user-images.githubusercontent.com/117274853/231782538-4c4bc2a6-bd41-4dfa-8f56-ea1b9887e13c.jpg)

**Comment by lorenzo-cavazzi** [comment]
That would make sense, but I would rather move it to the "Advanced" section once we have at least something else to put there. Let's keep it in "General" for the moment being
