### ISSUE TITLE
Welcome page message is never displayed

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2434]
The BIT shows some legal notices using this: https://github.com/SwissDataScienceCenter/renku/blob/0.24.1/helm-chart/renku/values.yaml#L609

But with the addition of the dashboard the welcome page is never shown.

We should either put this functionality back in or announce that it has been removed and change the values file in ui and renku repos accordingly.

**Comment by lorenzo-cavazzi** [comment]
That's a good point. With the new dashboard, we actually lost the space for custom tests for logged-in users (in the red square on the screenshot).

Let me first discuss this internally.

![image](https://user-images.githubusercontent.com/43481553/226573154-1969961b-3dba-45f0-a4ed-e7fc45782dad.png)

**Comment by lokijuhy** [comment]
@olevski Who should we talk to at the BIT to discuss this issue and potential solutions?

**Comment by jdupre81** [comment]
here are two design proposals:
The idea is that the message appears automatically when logging, then the user can close it / or reopen it with the drop-down arrow.
The prototype gives us an idea of how this works although it is not 100 % perfect, because the message should appear behind the top nav bar and not from the top of the window, but unfortunately I couldn’t find a better animation with Figma. 

https://user-images.githubusercontent.com/117274853/227926119-450509a6-74e5-40ce-b9cf-28de45c019b9.mov



https://user-images.githubusercontent.com/117274853/227926140-4ad12057-88a0-4566-84d9-33851885ae80.mov

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/229066246-e83403d7-043e-438a-92c9-a7f630a7c3e9.png)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/229066453-7538f29d-cacb-40d4-a428-5fd33904fff2.png)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/229068006-e6d5dad0-a356-4f9c-9451-5dcc406558bf.png)

**Comment by lorenzo-cavazzi** [comment]
We picked the last proposal :point_up: 
We will show an Alert with some content, an optional hidden content, and an optional "close" icon (when closed, the alert should not show up again until the UI is refreshed or the user logs in again).

In short, the mechanism should be similar to the previously implemented `welcomePage` solution, getting the text from the values file as a markdown, but offering more possibilities to customize the content.

The structure on the values should be (similar to) the following:

```
dashboardMessage:
    enabled: boolean
    text: string (markdown allowed)
    additionalText: string (markdown allowed)
    style: string (one of the following: "plain", "success", "info", "warn", "danger"
    dismissable: boolean
```

Here is the explanation:
* enabled: turns the message on or off
* text: the text we show. It supports markdown.
* additionalText: optional text we will show when clicking "Read more...". It's part of a collapsible element that will initially be collapsed.
* style: this defines the Alert's style. If it's one of "success", "info", "warn", "danger" we can use the already styled `RenkuAlert` components. If it's any other value ("plain" or missing) we will use a standard alert with no icon or background color, just the border.
* dismissable: whether users can dismiss the alert or not. If possible, there will be the "dismiss" element on top right, and clicking it will hide the Alert until the next time the UI is refresh or the user logs in again

:warning:  Remember to remove the stale `welcomePage.text`  value, but keep an empty `welcomePage` element (`welcomePage: {}`) for backwards compatibility
