### ISSUE TITLE
Get project avatars from KG/core, maintain on core

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2439]
From #2337 

- Avatars: we _should_ have support soon for that on renku core. The pattern would be similar to the one described above. Verify it's feasible and consider creating a follow-up issue.

**Comment by lorenzo-cavazzi** [comment]
This should follow a similar pattern to what we do with avatars for datasets: use `POST cache.upload_file` and then set it through `POST project.edit`
Currently, renku-core doesn't support setting an image. This will be implemented soon on their end (_renku-python reference issues still missing -- to be added_)
https://dev.renku.ch/swagger/#/project/post_renku_project_edit
