### ISSUE TITLE
Add a Clone button

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2440]
## Motivation

We show the repository URLs and other commands to clone on the settings page. This is not very intuitive and hard to find.

![image](https://user-images.githubusercontent.com/43481553/227495358-9f29e341-177c-4f7c-9ecd-ea716d261c45.png)

## Proposal

We should adopt a solution [similar to GitLab](https://gitlab.dev.renku.ch/lorenzo.cavazzi.tech/updated-flight-tutorial-2023), with a dropdown Clone button that opens a panel with the Clone commands ready to copy

![image](https://user-images.githubusercontent.com/43481553/227495686-3c43bdcd-2325-49a9-b948-904ebe94717d.png)

The new button could go to the Overview page, where we currently have "Fork" and "Open in Gitlab". The Fork button should stay, and the "Open in GitLab" might either stay or be integrated with the new Clone button.
We don't need the date there anymore since it's already in the new project's header

![image](https://user-images.githubusercontent.com/43481553/227496251-8bdfb42a-22bb-460c-b6a7-3b53b5c554b5.png)

**Comment by jdupre81** [comment]
https://design.gitlab.com/brand-logo/core-logo

**Comment by jdupre81** [comment]
**Design proposal + video/prototype**

![Image](https://user-images.githubusercontent.com/117274853/229346804-9b2aa008-32ae-491c-884f-4ebb668f7848.png)



https://user-images.githubusercontent.com/117274853/229346727-acaeedc3-bcaf-465d-869f-718a0ef60463.mov

**Comment by lorenzo-cavazzi** [comment]
The last suggestion looks nice!

For GitLab, we can use the brand icons from Fontawesome and style it in renku-green as we do with the other icons https://fontawesome.com/icons/gitlab?f=brands&s=solid&pc=%2316a765
