### ISSUE TITLE
ability to add ssh keys or get http tokens from UI

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#245]
There is no need to go to gitlab when a new project is created apart from either a) obtaining a token for authenticating on http push or b) adding an ssh key. Ideally both of these could be done from the UI.

**Comment by lorenzo-cavazzi** [comment]
@rokroskar is this issue still relevant or can I close it?

**Comment by rokroskar** [comment]
😱
