### ISSUE TITLE
R-Studio UI can open with an incorrect appearance 

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2470]
When an R-Studio session starts, the UI is sometimes rendered with some sections set to 0 width. 

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1196411/231996041-e10aae95-a823-4912-859a-94a024cc9cf7.png">

This is how it should look:

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/1196411/231996530-1c66f301-7c30-4c92-ad60-f06e615dd9c7.png">

The suspicion is that this is caused by a race condition in the fetching of the R-Studio resources and when the elements are rendered in the UI.

We should 
1. See if we can fix this to ensure that the UI is consistently rendered correctly
2. If this is not possible, then we should update the cypress acceptance tests to **not** check that the UI has all elements visible

**Comment by lorenzo-cavazzi** [comment]
Let's spend up to 1 day on this; if the solution takes longer, we will re-schedule it

**Comment by lorenzo-cavazzi** [comment]
fixed by #2660
