### ISSUE TITLE
Start session button has incorrect notebook search param in file explorer

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#2477]
## Description

Context: https://github.com/SwissDataScienceCenter/renku-ui/pull/2469#issuecomment-1511190507

On the Files tab when viewing a notebook file, the "Start a session" button will redirect the user to an incorrect URL (`&notebook=undefined`).

## Reproduce

This happens on any project where the user does not have access, i.e. their permission level is below `Developer`.

E.g. https://renkulab.io/projects/johann-michael.thiebaut/flights-tutorial/files/blob/notebooks/FilterFlights.ipynb

**Comment by lorenzo-cavazzi** [comment]
Some context:

* The "Start session" button leads to a URL containing `notebook=undefined`, as in the following example: https://renku-ci-ui-2469.dev.renku.ch/projects/johann.thiebaut/flights-tutorial-2022-04-19/sessions/new?autostart=1&notebook=undefined
* As a consequence, we get the following error in the JupyterLab environment  (screenshot on the left; on the right it's the older error before #2469)
![image](https://user-images.githubusercontent.com/43481553/232701199-768609ad-b510-4bd2-9aec-5fe0cb5d4c0e.png)
