### ISSUE TITLE
Fetch files from git-lfs

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#248]
# Summary

The UI should be able to fetch files from LFS. 

# Details

The API we currently use returns LFS metadata, but not the contents of the file. We should either use a different endpoint in the API (if there is one) which returns the contents, regardless of whether the file is in the repo or LFS, or we need to check the response and potentially perform a second fetch for the contents from LFS

**Comment by ableuler** [comment]
>We should either use a different endpoint in the API (if there is one) which returns the contents, regardless of whether the file is in the repo or LFS, ...
I don't think that there is such an endpoint already, but we could offer one through the gateway. However, I'd prefer the clients to fetch those potentially large files directly from LFS server and not stream all the files through the gateway.

**Comment by ebiiii** [comment]
Once LFS is managed through our storage service, there will be endpoints to download LFS objects directly.
Otherwise, you can also emulate the LFS protocol from the gateway.

**Comment by ciyer** [comment]
@ebiiii Do you have an estimate for when LFS will be handled by the storage service?

**Comment by ciyer** [comment]
Closed, as this is currently not a problem since the only files we display, notebooks, are not stored in LFS. We will consider this again later when we decide how to handle file display in general.
