### ISSUE TITLE
Support Resource Pools from the UI

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2484]
## Motivation

We are introducing [Resource Access Control](https://github.com/SwissDataScienceCenter/renku-design-docs/blob/main/rfcs/011-resource-access-control/011-resource-access-control.md) in RenkuLab to assign resource pools to specific users.

This requires a few changes in the UI since the session will start within the context of a specific resource pool with an assigned set of resources.

### Starting sessions

We will need to query an API to get the list of resources (it should be [the `GET /resource_pools` API here](https://github.com/SwissDataScienceCenter/renku-data-services/blob/main/src/api.spec.yaml)) available to the user.
We will also need to query the project options to get a project's default pool and try to set it.
For quick-started sessions, we will use whatever is the project default or just the global default if nothing local overwrites it; for sessions through the "Start with options" page, we will error if the project-defined pool is not available, and show a warning. User can pick any other available option from the pool on that page.

ℹ️ This means the single resources (CPU, RAM, disk, GPU) won't be selectable as single entities but just as a pre-set. We won't need the `notebook_options` anymore since there will be just pools with sets of resources.

![image](https://user-images.githubusercontent.com/43481553/233350191-94e00920-7136-4351-810c-9bca81a58103.png)

### Sessions settings
On the project page, users can set session settings. The abovementioned ones will disappear and be swapped with the new pool sets.
Keep in mind that not everything is disappearing from there. The pinned images won't change, nor the default_url (even tho it will be just a pure string), and _probably_ also the "Automatically fetch LFS data" should not change.

**Comment by jdupre81** [comment]
Basically, and for practical and consistency purposes, the design follows the same design principle of the commit dropdown message. 

![Image](https://user-images.githubusercontent.com/117274853/234025859-ab75b16b-7f0a-4f6e-821a-8fc081916b66.jpg)



![Image](https://user-images.githubusercontent.com/117274853/234025882-debcda90-c98e-40c9-9a43-dee24cd0e8aa.jpg)



![Image](https://user-images.githubusercontent.com/117274853/234025897-26971139-ddae-4da8-a901-2fac7efb70d4.jpg)

**Comment by jdupre81** [comment]
as a **second option** I did a design with a short list and put a "Expand Button", but I think the design above looks much better. 

![Image](https://user-images.githubusercontent.com/117274853/234027129-62196a9b-a0a8-4998-b9bc-b58b2b9c6785.jpg)



![Image](https://user-images.githubusercontent.com/117274853/234027165-cd038066-669c-47f5-9984-a62eff635e2b.jpg)



![Image](https://user-images.githubusercontent.com/117274853/234027193-8019680c-d81e-47ab-934e-8ed24a18da88.jpg)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/234827360-16d5aa07-39e6-4b21-8dc5-34e95867ee06.png)



![Image](https://user-images.githubusercontent.com/117274853/234827391-55f54452-ce53-4033-a547-f4af76ff94c0.png)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/234859108-a5009271-5bf8-411b-8790-1cefe2846243.jpg)
![Image](https://user-images.githubusercontent.com/117274853/234859109-cabb9644-0f30-4497-bea8-02b9b6b10fb5.jpg)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/234896951-a4816ddd-be53-4394-a70b-bf8696df519a.png)

**Comment by jdupre81** [comment]
https://user-images.githubusercontent.com/117274853/235107045-74632151-6c35-4344-ba73-ecbe31d2ae84.mov

**Comment by lorenzo-cavazzi** [comment]
We can start working on this. We will broadly follow the design proposal with a modification: to simplify, we can start using a dropdown (similar to the commit selection dropdown) so that we don't need to re-shuffle the content when selecting an item further down on the list. We can define the last visual details before merging.

The data service should be up and running. Please ping Tasko to verify how to include it in a PR (or personal) deployment.
