### ISSUE TITLE
Render an error screen instead of a blank one when the UI crashes

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#2498]
## Motivation

When the UI crashes, it renders a blank screen which can be confusing to users.

See for example: https://github.com/SwissDataScienceCenter/renku-ui/issues/2488.

## Proposal

Use Sentry's error boundary component to render a fallback component (e.g. "An error occurred") which would let the user either reload the page or return to the home page of the UI.

See: https://docs.sentry.io/platforms/javascript/guides/react/features/error-boundary/.

**Comment by lorenzo-cavazzi** [comment]
![image](https://user-images.githubusercontent.com/43481553/234800231-533cd4ed-ce15-43d8-94e1-58c76701dd1f.png)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/235183203-cbcabe6c-8b76-4389-b010-ae58f110832c.png)

**Comment by jdupre81** [comment]
![Image](https://user-images.githubusercontent.com/117274853/235230968-efbe9353-9ef9-429b-9b72-6ead3e2b1ce2.jpg)

**Comment by jdupre81** [comment]
https://user-images.githubusercontent.com/117274853/235234726-27e536bc-76c9-4ac6-9286-77bba9de902f.mov
