### ISSUE TITLE
Update the search page "owned by me" option to list exactly projects owned by the user

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#2523]
## Description

Currently the search is performed using the user's full name and may inaccurately match projects not owned by that user.

The KG will add a search param to match exactly based on the user's credentials. The issue on their side is the following: https://github.com/SwissDataScienceCenter/renku-graph/issues/1486

## Reproduce

1. Create alternate accounts with the same full name
2. Create a project from one account
3. Log out
4. Log in with an alternate account
5. Search projects with "Owned by me" option

EDIT: the KG issue has been solved; use the `development` branch, or any KG version >= 2.46.0
~Depends on: https://github.com/SwissDataScienceCenter/renku-graph/issues/1486~

**Comment by lorenzo-cavazzi** [comment]
https://github.com/SwissDataScienceCenter/renku-graph/issues/1486 has been merged and the `development` branch of KG contains the required changes.
The new query parameter is named `owned`

**Comment by lorenzo-cavazzi** [comment]
[KG blocker](https://github.com/SwissDataScienceCenter/renku-graph/pull/1786) was solved. We can now filter by roles; we should check whether it's better to filter just by `owner` or both òwner` and `maintainer`
