### ISSUE TITLE
Add interactivity to lineage graph

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#256]
- [x] Clicking on a node should take you to the lineage view for that node
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1196411/54537822-798fd400-4993-11e9-8c64-b3e86b052a1e.png">

( compare with current display where it is not clear what is current and what is past )
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/1196411/55553659-12875480-56e1-11e9-85b4-4d333a35f931.png">

**Comment by rokroskar** [comment]
should we close this and make a separate issue for seeing different commits? I think it's quite a different beast to tackle. @vfried @lorenzo-cavazzi ?

**Comment by rokroskar** [comment]
or we can make an epic out of this since I think seeing and navigating commits might take several issues

**Comment by vfried** [comment]
I think we can make a new epic with new issues for it
