### ISSUE TITLE
ui: standardize conventions

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#261]
# Summary

We need to have conventions in the UI for when and why we use:

- Badges (currently for tags, state of kus, etc.)
- Buttons Filled
    - Links to GitLab
    - State change actions
- Buttons Not-Filled
    - Close ku
    - Star/Unstar project
- Text links
    - Links to other pages within the application
- OK/Cancel button location (left/right) and order

# Proposal

- Use unfilled buttons for state transitions
- Use filled buttons for links to other sides and actions
- Text links for app-internal links

# Implementation

Create components: ```InternalLink```, ```ExternalLink```, and ```StateChange``` so we can control the appearance in one place.

**Comment by rokroskar** [comment]
This has the urgent tag but it's not obvious it's being worked on -- if not, can you move it to the backlog or remove it from the current project?

**Comment by ciyer** [comment]
Superseded by #1322
