### ISSUE TITLE
Failed writes to Redis are potentially ignored

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2610]
The Redis adapter in the ui-server returns true or false [here](https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/storage/RedisStorage.ts#L97).

But in several places the result from the `save` method is not checked. And the code assumes that the write to Redis was successful. Or perhaps Redis raises an error if the write was not successful. If Redis raises an error on failed writes then it would be good to check the code and ensure that ignoring the return value from `storage.save` is correct or some checks should be added. Or if the true/false value being returned from the save method indicates a successful write to Redis then we should be always checking the output and raising an appropriate error.

Here is where this happens:
- https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/authentication/index.ts#L182
- https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/authentication/index.ts#L189
- https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/authentication/index.ts#L365 (indirectly but the return value is still ignored)
- https://github.com/SwissDataScienceCenter/renku-ui/blob/master/server/src/utils/middlewares/lastProjectsMiddleware.ts#L52

There are a few more cases.

**Comment by seanrmurphy** [comment]
More generally, from an operations perspective, it's good to have visibility into issues with redis. Previously, I've seen exceptions raised if there are problems communicating with redis but did not see this in the last episode. For us, it would be helpful to have:
- a log message when starting the ui-server which states that a redis connection has been established
- log messages in case a read from or write to redis has failed...

**Comment by lorenzo-cavazzi** [comment]
@seanrmurphy  Problems with connections are already logged, but we might be swallowing some other errors, perhaps on read/write as Tasko mentioned.
We need to investigate further; it would be great if we had a way to reproduce a similar error as the one that happened recently. Please let us know; otherwise, we will simulate failures and go for generic `try/catch` -- hopefully that should be enough
