### ISSUE TITLE
Support standard R files

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#2637]
## Motivation

See  https://github.com/SwissDataScienceCenter/renku/issues/3145

- [x] .code-workspace
- [x] .qmd 
- [x] renv.lock
- [x] .Renviron
- [x] .Rnw 
- [x] .Rprofile

**Comment by philipp-baumann** [comment]
- `renv.lock`
- `.Rprofile`
- `.Renviron`
- `.qmd` (quarto markdown notebook, also relevant for py and Julia projects)
- `.Rnw` (sweave; becomes less relevant because of RMarkdown and Quarto, but still very nice for going 10 plus years back and reproduce stuff.)

**Comment by philipp-baumann** [comment]
These are generic nice-to-have support in viewer I think:
- `.code-workspace` => currently, there is support for `.Rproj`, but VSCode/VSCodium are nice to have alternatives.

**Comment by philipp-baumann** [comment]
Thanks for implementing :100: found one more:
- `.lintr` (linting config)

**Comment by ciyer** [comment]
> Thanks for implementing 💯 found one more, not core R but still good for good development practice:
> 
> * `.lintr` (linting config)

Sorry, I only noticed this one after already merging the PR, but I quickly added another one: #2639
