### ISSUE TITLE
ui: enable nav search bar

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#264]
The input field in the top nav is now a quick-nav bar making it possible to navigate to a project by typing a portion of its name into the input field. This element will later be improved to include real search capabilities.

**Comment by rokroskar** [comment]
can we add to this pagination of the projects that are listed? Or is that a separate issue

**Comment by ableuler** [comment]
@rokroskar you guessed it - separate issue.
