### ISSUE TITLE
Reference to the currently deployed release in the UI

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku-ui#2664]
## Motivation

As a user, I would like to understand which is the current version of RenkuLab that I am using, and refer it to the releases in GitHub.

## Proposal

The footer of RenkuLab could include the version of Renku, matching the latest deployed release:
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/127967525/4e54d1d0-c768-45b4-96d9-6b72916076c0)

**Comment by lorenzo-cavazzi** [comment]
The UI side is rather simple. We need to get the version data and that's easy from single services (most of them have a `version` endpoint) but ironically we still don't have a way to get the Renku version. I'll start a discussion

See also https://github.com/SwissDataScienceCenter/renku/issues/2422

**Comment by lorenzo-cavazzi** [comment]
Thank you @jdupre81

On the footer I would even make it shorter, perhaps `v0.31.0` or even just `0.31.0`, and link the page to both the text and the renku frog next to it.

On the full page, I would not say "Most recent" or "latest" since a deployment might be running an older version of renkulab.

I would rather say.
`Renku version: 0.31.0`

And later:
```
Renku components version:
* UI: 3.9.0
* Core: 2.6.1
* Notebooks: 1.16.1
[...]
```

**Comment by jdupre81** [comment]
Thanks for your feedback @lorenzo-cavazzi 

Here is the revised design

![Image](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/c7bdb816-b7a4-4fea-8a38-c077e98fa4ef)

**Comment by lorenzo-cavazzi** [comment]
Additional info: align the version number vertically, and the element containing logo and version number should be aligned horizontally

**Comment by jdupre81** [comment]
![Image](https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/97aef03a-2f82-4ea9-a95c-75dfa93b35e6)
