### ISSUE TITLE
Update Template Basic Python Project version to 3.10

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku-ui#2665]
## Description

Within the default Renku templates, the Basic Python Project states 3.9, but actually version 3.10 is installed.

## Reproduce

1. Go to https://renkulab.io/projects/new
2. Scroll down to Templates
3. See "Basic Python (3.9) Project"

<img width="130" alt="image" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/127967525/c54e7484-e570-42a5-ac65-8eef35973c8d">

**Comment by lorenzo-cavazzi** [comment]
@bethcg the template content is loaded dynamically from the UI. The right place to change it is in the following repo https://github.com/SwissDataScienceCenter/renku-project-template , specifically [in the manifest file](https://github.com/SwissDataScienceCenter/renku-project-template/blob/master/manifest.yaml).

The latest version already fixes it; you can [check it on dev](https://dev.renku.ch/projects/new).
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/06203097-dc92-4a3d-898b-bc8aef067e29)
