### ISSUE TITLE
Reference to selected project template within a project

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku-ui#2666]
## Motivation
After creating a project with a specific template, there is not any information about the type of template that is currently in use for the project. 

## Proposal
Expose in the UI the specific template that a given project is using (e.g. Julia, Python, Basic, etc.)

**Comment by lorenzo-cavazzi** [comment]
We made this available in the Settings tab a couple of releases ago. You can expand the project status section to see both the renku and template versions.

For the template, it mentions the version and the name; in both cases, you can click on it to open the reference.
Mind that the information might be missing for older projects or in a couple of other corner cases.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/b0ea0a68-839e-4550-9f67-e98a3404f2e0)

**Comment by lorenzo-cavazzi** [comment]
P.S: in the past we were showing the template more prominently but it was decided to hide it under a collapsible element (collapsed by default).

More info on [the ShapeUp document](https://www.notion.so/Simplify-project-status-view-25346cf78fd74c4aab54165748ef966d)
And the UI issue https://github.com/SwissDataScienceCenter/renku-ui/issues/2315

**Comment by lorenzo-cavazzi** [comment]
I'm closing this since it seems addressed already in the latest UI version.
Feel free to re-open with further comments if there is something to discuss or if you have suggestions to improve.
