### ISSUE TITLE
Font for notebook outputs

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#268]
1. Source Code Pro is not loading on my Opera (it's replaced by a serif font!)
2. I think it should be the same font as cell inputs

**Comment by ableuler** [comment]
@leafty can you maybe post a screenshot here just to make sure we're talking about the same thing?

**Comment by leafty** [comment]
![screenshot from 2018-08-10 07-53-23](https://user-images.githubusercontent.com/951086/43940977-7df89e42-9c72-11e8-9d96-baa16fe9cc4a.png)

**Comment by leafty** [comment]
Erm, welll it's the same, sorry

**Comment by ableuler** [comment]
I vote for closing this issue. Although I agree that this font is not optimal, I think we have more urgent issues to take care of.

**Comment by leafty** [comment]
Will do

**Comment by leafty** [comment]
It's good now
