### ISSUE TITLE
Landing page - Unused links/pages in the first section 

### ISSUE THREAD

**Issue by jdupre81** [SwissDataScienceCenter/renku-ui#2685]
When an anonymous user click on `Sessions` , it redirects to a page without any useful function. 

I suggest:
1. to improve this page, giving the user more specific instructions (CTA button), Documentation, Tutorials, etc., 
2. Or to eliminate this page since an anonymous user can not start a session from here. 

Additionally,
3. Unused links/pages: Medium, Youtube, Twitter - Do we want to keep them or would be better to take them out?

<img width="413" alt="Screenshot 2023-07-20 at 17 18 25" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/41ebbd7c-e1bb-47f6-b637-469fd97927fe">

<img width="1507" alt="Screenshot 2023-07-20 at 17 16 47" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/05925a34-e298-4e45-98c0-ba8e4527ef4a">

**Comment by lorenzo-cavazzi** [comment]
The sessions page already suggests what you can do to start a session when none are available. Still, adding a link to the documentation as you suggest would be helpful since most users here won't probably know what even _is_ a session.

I would keep the page since it's the only place where anonymous users can find running sessions (they don't have a dashboard)

**Comment by lorenzo-cavazzi** [comment]
> Unused links/pages: Medium, Youtube, Twitter - Do we want to keep them or would be better to take them out?

This feels like a Product decision rather than a UI decision. If you believe we should not rely on those we are happy to get rid of them.

**Comment by jdupre81** [comment]
> > Unused links/pages: Medium, Youtube, Twitter - Do we want to keep them or would be better to take them out?
> 
> This feels like a Product decision rather than a UI decision. If you believe we should not rely on those we are happy to get rid of them.

yes, I also thought the same !  I will discuss it with POD when everyone is back :) 
... or maybe I can ask Rok for his opinion, so that we don't have to wait too much. 

I will keep you inform ;)

**Comment by lorenzo-cavazzi** [comment]
Let's converge the first round of changes to the anonymous landing page (search bar and social media icons) into #2681
