### ISSUE TITLE
Removing Non-Simplifying Components in the App

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2696]
## Motivation
In the current state of the app, there are instances where certain components do not add substantial value to the app's core functionality or user interface. As a result, it introduce unnecessary complexity and overhead, leading to potential maintenance challenges and reduced code readability.

Example: InputHintLabel using FormText component from reactstrap

## Proposal
- Review the app's codebase thoroughly, focusing on components that may be non-essential or redundantly using external libraries like reactstrap.
- Evaluate whether it is necessary to keep the component when it can be used directly from the library.
- If the component is deemed non-essential or unnecessarily complex, refactor the relevant parts of the code to remove its usage entirely.

**Comment by lorenzo-cavazzi** [comment]
I totally agree with the concept, but I feel this issue is a bit too generic to schedule it "as is".
I suggest opening single issues when we identify stale components.
