### ISSUE TITLE
Phase out FontAwesome icons and use only Bootstrap

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2763]
## Motivation

We are using different sets of icons. Ideally, we should use a single library plus any custom in-house icons.

## Proposal

We agree with the design and product team to pick Bootrap and gradually phase out FontAwseome.

**Comment by lorenzo-cavazzi** [comment]
@ciyer this has been addressed, right?

**Comment by leafty** [comment]
We are pretty far from addressed:

![Screenshot 2024-06-06 at 09 29 42](https://github.com/SwissDataScienceCenter/renku-ui/assets/951086/9045bc2c-898a-4b24-93b0-69d6e210030a)

**Comment by ciyer** [comment]
> @ciyer this has been addressed, right?

@leafty's screenshot is a bit out of date (`Avatar.jsx` has been deleted as part of this effort), but it is still ongoing.

**Comment by lorenzo-cavazzi** [comment]
The new 2.0 pages now use Bootstrap Icons.
We can phase out the other library once we don't need Renku 1.0 anymore
