### ISSUE TITLE
Improve mechanism to check for non-indexed projects

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2774]
We need something more robust, especially when we have hundreds of projects (E.G. on CI deployments).

- The message on the dashboard should be _much_ faster: limit checking the first 5 projects on the Dashboard, and show a more generic message -- "You have N projects" is fine for up to 5; when it's more, we could say "You have more than 5 projects requiring ...".
-  Improve the logic in the `inactive-kg-projects` page and the UI server. Currently, we allow indexing simultaneously for up to 100 projects. That seems to break the mechanism. We should allow users to do that for up to 5 projects and implement a UI server solution to index everything. P.S. be sure to double-check that the current implementation actually works for 5 projects; it seems a bit broken.

_EDIT_
Logs suggest that the UI server keeps checking for project activation indefinitely. We should have a simple solution to prevent that, like for the sessions where the process stops as soon as there are no channels available. Or we could have a timeout (you can check the endless checks here: [Graphana](https://grafana.renkulab.io/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bcontainer%3D%5C%22ui%5C%22,%20pod%3D%5C%22renku-uiserver-b54b8d567-ht868%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22A%22,%22maxLines%22:5000%7D%5D,%22range%22:%7B%22from%22:%221695160800000%22,%22to%22:%221695643553000%22%7D%7D); alert on [Slack](https://swiss-data-science.slack.com/archives/C03446TNDGW/p1695644654579669))

**Comment by ciyer** [comment]
I think part 1 (_The message on the dashboard should be much faster_) and 3 (_do not check for project activation indefinitely_) can be implemented without further work, but I think some design work needs to happen improve the `inactive-kg-projects`. 

Currently, we fetch *all* projects that need activation and show them on the page. For many reasons this is not great, but it does have the advantage of being straightforward and allowing several different scenarios. For example, if there is one specific project a user is interested in, they can just search for it and either navigate to the project or select it for activation. If we add paging to the list and limit the number of projects that can be in the activation queue, we need to support searching for particular projects of interest and showing the projects currently being indexed separate from the entire list of projects.
