### ISSUE TITLE
feat: add typeset, icons and color palette in Storybook

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2785]
## Motivation

In this issue, we aim to enhance our Storybook by incorporating essential design elements such as a typeset system, icons, and a standardized color palette. This addition will improve the overall user experience, streamline development, and ensure design consistency across our applications.
## Proposal

**Typeset Integration:** Implement a typeset system in Storybook to ensure consistent typography across components and pages.
Ref: https://storybook.js.org/docs/react/api/doc-block-typeset

**Icon Library Integration:** Incorporate an icon library into Storybook, making a wide range of icons readily available for use in our UI components.
Ref: https://storybook.js.org/docs/react/api/doc-block-icongallery

**Color Palette Implementation:** Define and integrate a standardized color palette to maintain consistency in color usage throughout our Storybook.
Ref: https://storybook.js.org/docs/react/api/doc-block-colorpalette

**Comment by lorenzo-cavazzi** [comment]
We revamped Storybook, and it now includes colors and common elements.
For the icons, we now use only Boostrap Icons (with some exceptions, especially on legacy 1.0 pages).
