### ISSUE TITLE
WebSockets might causing crashes on the UI server pod

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2813]
## Description

UI pods seem to restart more frequently than they should.
One of the responsible errors is the following:

* [Sentry](https://sentry.dev.renku.ch/organizations/sentry/issues/1614/?project=4&query=is%3Aunresolved&referrer=issue-stream)
* [Graphana](https://grafana.renkulab.io/explore?orgId=1&left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki%22%7D,%22editorMode%22:%22builder%22,%22expr%22:%22%7Bcontainer%3D%5C%22ui%5C%22,%20pod%3D%5C%22renku-uiserver-b54b8d567-wxwq2%5C%22%7D%22,%22queryType%22:%22range%22,%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%221695643146247%22,%22to%22:%221695643553367%22%7D%7D)

## Reproduce

We should investigate this problem.
At the very least, we should try to handle unexpected WebSockets events in a way that doesn't crash the service.

**Comment by leafty** [comment]
I think we should close this considering #2814 makes the server properly handle bad WebSocket frames.

**Comment by lorenzo-cavazzi** [comment]
Closed by #2814
