### ISSUE TITLE
Double check why files are occasionally downloaded sequentially.

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2815]
## Description

Occasionally, static files for RenkuLab are downloaded sequentially. Looking at the screenshot, the Waterfall column shows that the JS bundle isn't downloaded until renkulab.io is loaded, and later the CSS bundle is served only after the JS bundle content is fully downloaded.

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/0c50244a-dae9-41af-a5be-48ee99b8f68b)

This isn't currently a big issue since we have just 1 big bundle file and the others combined take <100ms, but it might be worse if we move to another technology like NextJS.

We could spend some time investigating it. The primary suspect is Nginx, perhaps some limitation in serving concurrent requests.

P.S: mind that our network structure is not straightforward and we pass through other layers before hitting the UI client. It sounds unlikely that they introduce this behavior, but it cannot be totally excluded.

## Reproduce

* Open an incognito window in your browser and keep open the Network tab of the developer tools.
* Be sure to tick the "Disable cache" check.
* Reload the default renkulab.io page (or dev.renku.ch) multiple times in a row. Doing it before the page is even loaded increases the chances of reproducing the problem.

## More info

* As a counter-example, this is the Network tab when all works as expected
  ![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/f6280158-8bbb-4468-bcf7-d343c3e59e96)
* Mind that Firefox shows potentially confusing feedback: it looks like the js bundle is downloaded quickly and the CSS file takes forever. Testing with a Chromium-based browser might be simpler.
  ![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/57d70a25-7672-4b2a-9d8c-e6726b5932ed)

**Comment by leafty** [comment]
@lorenzo-cavazzi are you sure this is not a request queuing issue on the browser? Browsers do not have unlimited request queues and you may just have hit one with reloading a lot.

**Comment by leafty** [comment]
Also, this would most likely be a non-issue with server-side rendering as the client-side bundles are split into the minimal code required and are thus very small.

**Comment by lorenzo-cavazzi** [comment]
@leafty it might be the browser. It would make sense to test this without a browser and see how it goes, just to be sure this is a non-problem

**Comment by leafty** [comment]
I tried https://github.com/webpack-contrib/webpack-bundle-analyzer and some of our biggest pieces:
* react-ipynb-renderer - 946kB
* highlight.js - 299kB
* ckeditor - 256kB
* pdf.js - 104kB
* showdown-highlight, contains another copy of highlight.js!!! - 300kB
