### ISSUE TITLE
Check if there is unsaved work before deleting a session

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-ui#2825]
Right now when I go to delete a running session. I get this message

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/16360283/254363fc-9523-4659-acf3-e3a835b4a5f8)

But this happens even when I have no unsaved or unpushed changes in the repo. The ui can call the sidecar in the session when the delete session button is pressed and display a proper message. In other words we can tell for certain whether there is or isnt unsaved data. And only display the unsaved data message when appropriate.

**Comment by leafty** [comment]
I don't think I agree here. There could be some process running (e.g. in a notebook) and we have no idea about it by querying the git status.

**Comment by lorenzo-cavazzi** [comment]
That's true, but we already mention that "Deleting a session will permanently remove any unsaved work". I feel the case you mention @leafty is a corner case and we don't need a bigger warning for that. Btw that could occur also when pausing sessions and we don't show a more prominent message in that case.
