### ISSUE TITLE
Cannot modify datasets imported from external sources

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#2828]
## Description
When a dataset is imported from an external resource like Zenodo, the authors' email information is not included. This poses a problem when attempting to modify the dataset, as the email is a mandatory input. The core service generates an error if this information is not provided.

## Reproduce
![import and modify dataset](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/a0cae4a0-349f-4943-919c-70713c1f8bf4)

### Solution
Consider removing the email requirement from the endpoint or exploring alternative solutions.

**Comment by andre-code** [comment]
Ref:  https://github.com/SwissDataScienceCenter/renku-python/issues/3631

**Comment by ciyer** [comment]
I tested the the issue described here does not happen anymore. Closing.
