### ISSUE TITLE
Optimize dashboard components

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2869]
The sub-components in the `Dashboard` component are re-drawn from scratch every time the servers list updates, triggering a few APIs to fetch project details and commits. That's not necessary; be sure it won't happen again when adjusting the components.
![Image](https://user-images.githubusercontent.com/43481553/267641772-83b3dbd9-d2d7-4536-b062-2b06f25b2fef.png)

Bonus:  we have separate sections and components in `ProjectsDashboard` for projects with and without running sessions. We should harmonize that so that projects don't temporarily disappear and re-appear when sessions terminate.

**Comment by leafty** [comment]
We want to better use the RTK query cache here, but this is going to be hard to do without refactoring the components used to display projects in the Dashboard.

Currently we gather all the projects' data before passing it down to rendering components, but this approach means that hitting cached will not happen when a session starts or gets deleted (change in the args used for the hooks).

The idiomatic approach is to let each component rendering a project entry to query its required data which would hit cache when available.

**Comment by lorenzo-cavazzi** [comment]
This isn't worth the effort anymore since the current Dashboard will be phased out in the context of Renku 1.0
