### ISSUE TITLE
Client does not send cookies to gateway

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#287]
Although the current [fetch spec](https://fetch.spec.whatwg.org/) set 'same-origin' as the default credentials policy, some browsers still use 'omit'. ([Fetch change](https://github.com/whatwg/fetch/pull/585/files))

To make sure we send cookies to the gateway from the UI, the credentials option should be set to:
```js
credentials: "same-origin"
```
when calling `fetch`.

See:
https://github.com/SwissDataScienceCenter/renku-ui/blob/ec2ff8ce5de22a155cc5bfc4899b4937d3950cd7/src/gitlab/renkuFetch.js#L17

**Comment by ableuler** [comment]
@leaft Which API calls / which cookie are you talking about? Of course I can add your suggested option to the `renkuFetch` method, but we're already sending the access token in the request header so in principle it should not be necessary...

**Comment by leafty** [comment]
Well, you have the refresh token in the cookie, so you'll need it to solve #39

**Comment by ableuler** [comment]
My suggestion would be that the UI sends the refresh token only to the gateway endpoint for token refreshing `/auth/token/refresh` after receiving a token expired response on a previous request. Otherwise we end up sending the refresh token along with every API call which as far as I know is not what you're supposed to do.

**Comment by ableuler** [comment]
After merging #301 the refresh token is sent through the Authorization header to the token refresh endpoint. I suggest to close this issue.

**Comment by rokroskar** [comment]
@leafty?

**Comment by ableuler** [comment]
Closed in favour of #307 which addresses the concerns raised by @leafty .
