### ISSUE TITLE
Change the unavailable image warning once the image is available

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2906]
## Motivation

When trying to quick start a session just after a commit has been created (mind that many interactions requiring invoking renku-core APIs end up creating a commit) it's rather common to get the yellow warning because the new base image hasn't been built yet. Still, it will probably be ready within a few seconds, so the user can just try to click again.

![image (1)](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/99daffab-d383-4aac-9c98-8b2fcfc6024c)

This turns out to be confusing for some users who don't know exactly what was the problem.

## Proposal

As soon as the image is available, we could either:

- Change the alert to Info and mention there was an error cause the image wasn't ready, but now it's available and trying to start the session again should work. Or...
- Add another Info alert below the Warning to explain the image is no available and trying to start the session again should work.

I generally don't like swapping alerts, but adding multiple alerts might be overkill and users might ignore the latest addition.

**Comment by andre-code** [comment]
We can perhaps add a button that, during the building process, displays `Building Image...` (disabled status). Once the process is complete, it can change to `Retry Start Session`. This way, it will be clear both about the current status and the action the user can take after the building is done.
