### ISSUE TITLE
sessions page is very empty with no sessions

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-ui#2918]
when there are no sessions, the sessions page is pretty empty and it might not be immediately  apparent for a new user that the button all the way in the top right is how you start a session.

Maybe we could add a sessions start button here as well or make it clearer how to start a session if there are none
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/664486/70a344df-66f1-4b68-9d22-04e967a70de4)
in any case, feel free to ignore, it's really just a trivial suggestion

**Comment by jdupre81** [comment]
Text proposal:


**Currently you have no running sessions. You can click `here` to start a session.**

**If you want to start a `session with options`, `connect with ssh` or `create a session link`, please click on the green Start button at the right top side of the header**
