### ISSUE TITLE
Welcome page 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#293]
We need a few things on the welcome page for renkulab.io 

- [x] statement about renkulab.io being best-effort etc to manage expectations
- [x] a "get help" section with a link to gitter channel https://gitter.im/SwissDataScienceCenter/renku and the main renku repo issues page
- [ ] request that people do not upload more than 1GB datasets for the time being
- [x] link to first steps (#292)
- [ ] styling?

**Comment by fgeorgatos** [comment]
Hey, a 1st disclaimer attempt?

```
Renku has been through a heavy redesign during first half of year 2018, while the components design is solidifying during the 2nd half of the year. Kindly be aware that the developers may have good reasons to make changes and reserve the right for modifying APIs, in a look to reach v1.0 release.
```

**Comment by rokroskar** [comment]
thanks @fgeorgatos -- I edited slightly. Since we don't really publish/expose any APIs I took that statement out.

**Comment by ciyer** [comment]
I've created some text for this: https://github.com/SwissDataScienceCenter/renkulab.io/pull/8/

Will need to coordinate with Andreas and #294 to get this deployed.

**Comment by ableuler** [comment]
Changes will be visible on renkulab.io once #294 has been merged. See (and possibly edit further) https://github.com/SwissDataScienceCenter/renkulab.io/blob/master/renku-values.yaml.
