### ISSUE TITLE
'Or' oddly placed on login page

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-ui#2936]
![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/664486/49573f50-2589-44b1-8328-35802f9ed882)

the placement of the 'or' on the login page looks really off on firefox, not centered between the two sides and just floating at the top. tested on dev. I'm guessing it's supposed to be further down and between the two blocks?

**Comment by andre-code** [comment]
Closing this issue as the reported problem is related to browser cache.
