### ISSUE TITLE
Add Privacy Policy and Terms of Use

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2954]
## Motivation

Renkulab must support Privacy Policy and Terms of Use (or Terms and Conditions).
The texts for RenkuLab.io can be found here https://www.notion.so/Add-Privacy-Policy-and-Terms-of-Use-0c7d42e9d2ee4401be5b064732192cf3

## Proposal

* The Terms should be accepted at sign-up. We can use Keycloack for that
https://www.keycloak.org/docs/latest/server_admin/#proc-requiring-tac-agreement-at-registration_server_administration_guide
:bulb:  Mind that the best solution might be to set it from the values file; that's not strictly UI.

* The Privacy Policy should be part of the UI. There was a mechanism to customize that but we should double-check whether it still works correctly and revive it if necessary.

**Comment by ciyer** [comment]
I have added some questions about the proposal to the Notion page.
