### ISSUE TITLE
Update project creation

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#296]
Make sure to automatically reflect new files being added to the project template repo and not just changes to existing files.

**Comment by ableuler** [comment]
"On hold" until https://github.com/SwissDataScienceCenter/renku-python/issues/279 is resolved...

**Comment by leafty** [comment]
Btw, consider https://github.com/SwissDataScienceCenter/renku-project-template/issues/7 too.

**Comment by ciyer** [comment]
Superseded by #473.
