### ISSUE TITLE
Update the footer to add the link to the blog

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#2973]
Blog URL: https://blog.renkulab.io

**Comment by jdupre81** [comment]
Do we keep Medium as well?

**Comment by jdupre81** [comment]
Do we say "`Renku Blog`" or "`Blog Renku`" ?

**Comment by lorenzo-cavazzi** [comment]
Renku blog

> Do we say "`Renku Blog`" or "`Blog Renku`" ?
