### ISSUE TITLE
Avoid flashing alerts on the "Session class" section when changing branch

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#2976]
On the "Start session" page, changing branch results in flashing for a moment an error alert on the "Session class" section (see gif, even if it's not the best example).
Checking the network tab, there are no API errors; it's probably just a matter of returning early when all the required data for the session class is missing, or a wrong condition on showing the error message.

![Peek 2024-01-17 14-00](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/f05f1173-0469-4342-a7fe-200c0affe1fd)

**Comment by leafty** [comment]
This may be fixed by #2977.
