### ISSUE TITLE
Deprecate `Url.js` and replace it with `generatePath` from `react-router`

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#3052]
We don't need to re-invent the wheel to generate paths for the UI, we should use `generatePath` from `react-router`.

**Comment by lorenzo-cavazzi** [comment]
I think we can keep `Url.js` for the older Renku 1.0 pages and use `generatePath` for 2.0.
As part of the PR, it would be nice to have a new rule in the coding guidelines mentioning how to compose URLs

**Comment by lorenzo-cavazzi** [comment]
@leafty should we close this or do you want to keep it open for v1 components?
