### ISSUE TITLE
Landing page: replace Medium with Renku Blog from the quick links in the footer 

### ISSUE THREAD

**Issue by jdupre81** [SwissDataScienceCenter/renku-ui#3059]
As discussed with Rok some weeks ago. Please replace the Medium link with our [Renku Blog](https://blog.renkulab.io/)

<img width="1118" alt="Screenshot 2024-03-04 at 15 15 22" src="https://github.com/SwissDataScienceCenter/renku-ui/assets/117274853/ea76c897-a731-4436-8f4a-615833778528">

**Comment by leafty** [comment]
? The Renku blog link is already there. Will make a PR to replace it with the Mastodon account.
