### ISSUE TITLE
Refactor token handling

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#307]
The current setup and handling of tokens needs to be refactored for CSRF and XSS vulnerabilities.

In short we need to:
- [x] Store tokens as secure HttpOnly cookies, therefore remove all cookie handling from the UI
- [ ] ...therefore, determine login status independent of cookies
- [x] Add custom header for CSRF protection
- [x] Send user directly to login route when receiving a 403 response

See also https://github.com/SwissDataScienceCenter/renku-gateway/issues/51

---
### Explanation

Currently, the tokens are stored as cookies which are accessible to JS code and could be stolen if a XSS attack was successful. To improve on this, we should store access- and refresh tokens in cookies that are **HttpOnly and secure** (the secure options needs to be set as a deployment specific parameter that can be turned off for local development). Furthermore, we need to make sure the cookie is sent to the gateway when making requests by setting `credentials: "same-origin"` explicitly (#287).

Reading the access token from a cookie header on the server-side (gateway) opens the door for CSRF attacks (the SameSite attribute of cookies is still missing in [many browsers](https://caniuse.com/#search=SameSite)). Setting a custom request header (`options.headers['X-Requested-With'] = 'XMLHttpRequest'`?) whose existence the gateway will enforce should (together with other server-side measures) provide decent security against CSRF attacks.

---
update: With the ongoing work towards a stateful gateway (https://github.com/SwissDataScienceCenter/renku-gateway/pull/58) which can hold a user tokens for the various backend services and after discussing with @ebiiii, the plan is to store a session cookie instead of the Keycloak access token itself in the browser. The rest of the described approach (storing of session cookie as secure HttpOnly cookie, custom header for CSRF protection) remains the same.

**Comment by leafty** [comment]
To add my 2 cents:

In my eyes, the best solution is to use a signed session identifier stored as a cookie, together with CSRF tokens.

Bearer tokens would be kept at the gateway level, in a session store (e.g. Redis or encrypted cookies).

**Comment by ableuler** [comment]
@leafty For me, this possibility is still there. However, the actual changes that I proposed are pretty lightweight and quick to implement. They could (or I would say should) be tackled asap.

Although I have sympathy for well-tested traditional approaches (i.e. session coodie and csrf token) - especially when it comes to security - , it seems less straight-forward to follow this for single page applications than for server-side web applications. 

Token authentication on the other hand seems to be generally accepted for SPAs talking to a REST APIs: 
https://stormpath.com/blog/token-auth-spa
https://medium.com/lightrail/getting-token-authentication-right-in-a-stateless-single-page-application-57d0c6474e3

**Comment by fgeorgatos** [comment]
would this one justify a `0.2.1`? any status update?

**Comment by ableuler** [comment]
@fgeorgatos We should definitely tag this as new versions for both the gateway and the ui when these PRs are merged.
