### ISSUE TITLE
include environment elements

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#308]
We should have some UI elements that allow specification and customization of the environment. This needs to be available at several levels:

* The instance could have a default environment
* The user could have her default environment
* A project has a default environment

An admin should have the ability to set/modify the instance environment. A user should have the ability to set/modify her default environment, and the project page needs a tab to configure the environment as well.

Project creation should select an the environment (to the user default if there, otherwise the instance environment?) and allow selection of an alternative environment. 

relates to https://github.com/SwissDataScienceCenter/renku/issues/404

**Comment by ciyer** [comment]
Superseded by  SwissDataScienceCenter/renku#611
