### ISSUE TITLE
Image build check is not from master branch

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#311]
The UI yellow notebook pill and links are tied to the most recent build, even if it's not on the master branch.

**Comment by rokroskar** [comment]
@leafty more info here?

**Comment by leafty** [comment]
The UI will tell you "The notebook image build is still ongoing. Wait a bit before launching a notebook..." when that build is from a branch and not master.
This should not happen and the UI should filter out builds which are irrelevant.

**Comment by ciyer** [comment]
This is superseded by #495
