### ISSUE TITLE
Add projectSlug as a template variable

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#319]
See: https://github.com/SwissDataScienceCenter/renku-ui/blob/master/src/gitlab/initRenkuProject.js#L76-L80

This would help to have safe names for https://github.com/SwissDataScienceCenter/renku-project-template/pull/9

**Comment by rokroskar** [comment]
We don't seem to have a need for a custom project slug atm - will reopen this if the status changes.
