### ISSUE TITLE
[A11Y] Fix keyboard navigation for adding a new launcher

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#3222]
## Description
The navigation from the "Add New Launcher" modal to the "Existing Environment" or "Custom Environment" form modals is not functioning correctly. The focus should automatically shift to the newly opened modal. Additionally, when selecting "Existing Environment," it is difficult to smoothly navigate and select the environment using the keyboard.

### Steps to Reproduce
Create a custom session launcher using only the keyboard.
Create an existing environment launcher using only the keyboard.
![add new launch](https://github.com/SwissDataScienceCenter/renku-ui/assets/43388408/138c3216-691a-47f9-bc86-8169b8b92baf)

**Comment by lorenzo-cavazzi** [comment]
This has been fixed; in the latest version, after opening the modal, launchers can be selected with the keyboard
