### ISSUE TITLE
Don't make us wait forever when starting a docker/jupyterlab fails.

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-ui#325]
**Is your feature request related to a problem? Please describe.**
The starting Jupyterlab will not notify me if something went wrong, and can make me wait forever.

**Describe the solution you'd like**
Give the option to get more details (can be summarized, no need for a full log) about what it is doing, and what's left to do, with a brief status (Ok, Fail) of operation, such as:
```
* [Ok]   starting docker container
* [Fail]  cloning repo
* [    ]   importing data   <- for git submodule update / git lfs pull
```

**Describe alternatives you've considered**
At a minimum we should report an error, so that know when there's no point to keep waiting.

**Comment by rokroskar** [comment]
At the moment, this is actually done in the notebooks service. I will move the issue there.

**Comment by rokroskar** [comment]
This issue was moved to SwissDataScienceCenter/renku-notebooks#62
