### ISSUE TITLE
Missing files/notebooks

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#326]
In a repository with many files, it appears that e.g. the notebooks don't end up getting displayed. (see https://renkulab.io/projects/47/files/notebooks for example)

**Comment by ciyer** [comment]
This should have been fixed by https://github.com/SwissDataScienceCenter/renku-gateway/pull/54. Please deploy the latest renku-gateway and test again.

**Comment by rokroskar** [comment]
seems to be resolved
