### ISSUE TITLE
the Ku markdown render does not interpret extensions correctly

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#328]
the filename is `notebook.ran.ipynb`. The original notebook is in the same directory with the name `notebook.ipynb`. I'd like to visualize the notebook that was actually executed by papermill, so I'm using the one with `ran` in the name. 

![image](https://user-images.githubusercontent.com/3353586/46279743-4a62e300-c56a-11e8-9fe7-500d5bc9aabf.png)

**Comment by vfried** [comment]
I think this was fixed already (with changes in the file explorer and file viewer)

**Comment by rokroskar** [comment]
Indeed, this seems to have been fixed.
