### ISSUE TITLE
Modify existing Ku/Contribution

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#330]
Allow users to modify previously created Kus/Contributions.

**Comment by mitch-volpi** [comment]
It's maybe not worth opening a new issue for this, but is it possible to have some level of text formatting in Kus? (e.g. as in gitlab issues textboxes). At least newlines returns?

**Comment by leafty** [comment]
The text is also markdown rendered so use two newlines to make a new paragraph --not exactly the same as in gitlab (e.g. render of notebooks inline).

**Comment by mitch-volpi** [comment]
mmm I'm not seeing markdown on the `limited.renku.ch`. I'll try better later :p

**Comment by rokroskar** [comment]
@ciyer can you have a look? There seem to be issues with markdown rendering

**Comment by ciyer** [comment]
Markdown rendering is fixed in #328. Closing this issue because we are reworking how to handle Issues.
