### ISSUE TITLE
error loading some pages on safari

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#337]
seen when opening renkulab.io/gitlab or launching the notebooks server:

![image](https://user-images.githubusercontent.com/3353586/47304271-61a36680-d626-11e8-81f7-96174f343f19.png)

**Comment by leafty** [comment]
Could be: https://blog.christopherburg.com/2017/10/18/safari-11-multiline-http-headers-and-nsposixerrordomain100/
But network traces would help narrow it down.

**Comment by ciyer** [comment]
Cannot reproduce. Seems to have been a temporary problem.
