### ISSUE TITLE
improve notebook launch

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#340]
- [x] Remove the "Connect to Jupyter" button (and the popup on "+" in the top navbar) and use the one in the "Notebook Servers" 
- [x] Add the "Launch Jupyter" button in the "Notebook Servers" tab
- ~~[ ] Allow using other branches for notebook launch: Add the option to specify a branch for launching the notebook server -- should be done by attaching the `?branch=<name>` query parameter to the notebook launch `POST` request URL.~~
- ~~[ ] Ensure that the latest commit is used when a notebook server is started (currently, we use the latest commit *at the time the page was loaded*. This causes problems if a user pushes between loading the view and launching a notebook server)~~

Next step will include fixing the list of Servers displayed in the "Notebook Servers" tab and fixing the "Notebooks" page from top navbar

**Comment by lorenzo-cavazzi** [comment]
waiting for #406 for the last 2 points

**Comment by lorenzo-cavazzi** [comment]
last 2 points --> #416
