### ISSUE TITLE
Bug with session start page in Renku 2.0

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#3401]
The session start page errors when opened in a new tab, when the project has at least one data connector.

Reproduce: open this link -> https://dev.renku.ch/v2/projects/flora.thiebaut/flora-test-session/sessions/01JCN9CJG356VCGKTAWZN6GJP6/start.

**Comment by leafty** [comment]
This may have been fixed.

**Comment by lorenzo-cavazzi** [comment]
I can't reproduce it in the latest version of the UI
