### ISSUE TITLE
#342 not working when logged in

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-ui#343]
See: #342
The expected behavior happens when not logged in (on public projects).
There is still a blank page showing up with a js crash when logged in.

**Comment by rokroskar** [comment]
I think we need an abbreviated version of the dot output done in `renku-python`, similar to the one that is generated for just the ascii version of `renku log`

**Comment by ciyer** [comment]
Thanks for testing. The original problem exhibited itself differently on my computer, but I recreated this and pushed a fix.
