### ISSUE TITLE
Integrate notebooks admin page into UI

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#351]
With #331 merged we can make requests to the notebook service directly from the UI. We should now be able to greatly simplify the notebook server interactions. 

First steps:
- [x] Create a new "Notebook Servers" tab in the project view
- [x] Display the information currently presented in a separate browser tab served from `https://<renku-domain>/jupyterhub/services/notebooks/ui/` in the above tab
- [x] Add the "connect" and "stop" options per notebook server

Some ideas for further improvements: 
* the notebook server button itself could reflect the status of the running server for the selected project
* the project view page could include an icon to connect to a running server
* there could be a global page per user on the platform level to display running servers
* the notebook servers tab could display further relevant information like e.g. running commit, branch, time inactive etc.

**Comment by lorenzo-cavazzi** [comment]
Would embedding the `https://<renku-domain>/jupyterhub/services/notebooks/ui/` page in the tab through an `<iframe>` be an acceptable solution? I believe this would easily satisfy the requirements in the first steps, but then we won't be able to customize the page further.

Anyway this would be the result

![image](https://user-images.githubusercontent.com/43481553/52716848-fba96900-2f9f-11e9-8b89-74b2ae116eff.png)

**Comment by ciyer** [comment]
Cute idea, but this is not the solution I had in mind. :)
