### ISSUE TITLE
Add markdown support for ku contributions

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-ui#354]
Viewing Kus in Renku is not as nice as in gitlab, see two attached screenshots

A similar display for Kus as is done for issues in gitlab would be nice.

![issue-in-gitlab](https://user-images.githubusercontent.com/36889839/49013683-e29dd280-f17d-11e8-844b-650a49a1f102.png)
![kus-in-renku](https://user-images.githubusercontent.com/36889839/49013684-e29dd280-f17d-11e8-84d0-ee690c341862.png)

**Comment by ableuler** [comment]
This is actually a duplication of #341 which has been merged. The corresponding changes should be deployed on renkulab.io and renku limited soon.
