### ISSUE TITLE
Refactor lineage view to use graph service

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#362]
**MVP**

- [x] Query the lineage API of the gateway rather than the artefacts API. (Needs the first two sub-issues of https://github.com/SwissDataScienceCenter/renku-gateway/issues/71 to be resolved).
Done in #374 and #392 

**post - MVP**

~Improve presentation and interactivity by making projects expandable on click.~

**Comment by rokroskar** [comment]
@ciyer the necessary pieces are in place for this to be done. It seems to me that the changes required are pretty minimal -- could you have a look?

**Comment by rokroskar** [comment]
closing this otherwise it could stay open indefinitely -- @ciyer @lorenzo-cavazzi could you please make another issue to address the `post-MVP` part?

**Comment by lorenzo-cavazzi** [comment]
I think the "on click" interactivity is already covered by #256 . Not sure if the second point here was in the same direction, but with #400 it will be also easy to preview project files.
