### ISSUE TITLE
the launch-jupyter page shows button when it shouldn't

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#370]
It might happen that the tokens are expired stale in which case the launch-jupyter dialog (in the image below) is not fully presented. Instead of the full form, the user just sees the "launch jupyter" button, which doesn't actually do anything. This should be corrected either from the gateway side (get a new token) or the UI side (not sure how). 

![image](https://user-images.githubusercontent.com/3353586/51623667-82d36600-1f39-11e9-9392-e592a4f65528.png)

**Comment by ableuler** [comment]
I think the gateway can not do this independently of the UI because as far as I can see, Jupyterhub does not issue any refresh tokens. So the entire the entire oAuth dance with Jupyterhub will have to be performed in order to obtain a new token.

**Comment by rokroskar** [comment]
I'm not sure -- the issue is more that the "Launch Server" button is there, but the form isn't. So there is probably a broken request somewhere that causes the form not to render, but the same failure doesn't prevent the button from being rendered, or better, to cause some sort of a re-login.

**Comment by ableuler** [comment]
Yes, the the request for the server options is most likely failing due to and expired token and thus re-login with Jupyterhub is needed. I'm just wondering how this is best done.

**Comment by rokroskar** [comment]
presumably it returns a 401 or 403 but I haven't tried. 

see `c.JupyterHub.cookie_max_age_days` here: https://jupyterhub.readthedocs.io/en/stable/api/app.html

It's a float so it should be possible to set it to something sufficiently small for testing.

**Comment by ableuler** [comment]
I don’t think that `c.JupyterHub.cookie_max_age_days` sets the expiration time of the oAuth access token. But here's a way to reproduce the problem: 
- log into renku through the ui
- browse to `https://<renku-domain>/jupyterhub/hub/token` and revoke the access token
- delete all jupyterhub cookies in your browser for your renku-domain
- try to launch a notebook.

**Comment by vfried** [comment]
> I don’t think that `c.JupyterHub.cookie_max_age_days` sets the expiration time of the oAuth access token. But here's a way to reproduce the problem:
> 
> * log into renku through the ui
> * browse to `https://<renku-domain>/jupyterhub/hub/token` and revoke the access token
> * delete all jupyterhub cookies in your browser for your renku-domain
> * try to launch a notebook
> 
> Does this work (well fail) @vfried ?

For some reason this only works when i'm not running telepresence :(

**Comment by vfried** [comment]
I've been trying to replicate the error when i'm using telepresence but i can't. It looks like the bug is still there but it slightly changed, after i do the steps that @ableuler mentioned it show's a "The server is already running" message but when i try to connect to jupyterlab it throws a 505 error which means that the bug is still there but it changed a bit. I will try to fix the error that i see when using telepresence, I assume the version i can run with telepresence is the latest version that we have of the frontend. If this is not ok, please tell me and i will find a way of replicating the error as described in the bug.

**Comment by vfried** [comment]
I've been trying to fix this issue and i realised that on top of receiving the proper error message, and logging out/in,  the jupyterhub pod has to be "killed" in the backend so I can launch again jupyterlab otherwise it doesn't work.
