### ISSUE TITLE
Enable webhook creation.

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#373]
- [ ] manually in project settings 
- [ ] on project creation

To turn on the webhook, make a service `POST` request to `http://webhook-service/projects/<project-id>/hooks` with the gitlab OAuth token in the `OAUTH-TOKEN` header. For the moment, webhooks only work with public projects.

**Comment by ciyer** [comment]
Duplicates #369. All information mentioned here has been added to that issue.

**Comment by rokroskar** [comment]
ah ok, thanks, sorry about the noise
