### ISSUE TITLE
Projects search page should be finer-grained

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#377]
The project search page currently just offers search. Instead, it should offer 3 options in tabs: Yours, Starred, Search.

The behavior of Yours and Starred should be similar to the landing page and show projects where the user is a a member or has starred, respectively. Search should be where the current functionality of the projects page goes.

# Details

Each tab can, but does not need to have its own URL. If it is easier to use the browser to track the state, do that, if it is easier to track the state of which tab is displayed in redux, that is also fine. 

In the first case, then the search URL in quick-nav bar will need to be updated. In the latter case, If a search query is provided, then the active tab should be the search tab, otherwise the Yours tab.

Current behavior is that clicking once on the projects top-nav shows an empty page, waiting for input, clicking twice runs the search with empty input. It should either always run the search or never.

# Mockup

<img width="523" alt="image" src="https://user-images.githubusercontent.com/1196411/52339402-4c9fe700-2a0d-11e9-9246-152b97d69a0a.png">

**Comment by rokroskar** [comment]
hasn't this been done? can the issue be closed?

**Comment by ciyer** [comment]
Yes, I had moved it to the "Done" column in our project board and assumed that that closes it, but apparently not.
