### ISSUE TITLE
Feature request: mobile device friendly layout

### ISSUE THREAD

**Issue by StathatosAlex** [SwissDataScienceCenter/renku-ui#381]
While using renkulab.io, it is not possible to launch a notebook from a mobile device.
It would be handy if smaller mobile screens were more usable, in general.

**Comment by StathatosAlex** [comment]
Motorola moto g2

**Comment by lorenzo-cavazzi** [comment]
The visualization seems to be fine on android devices with an up-to-date version of chrome (tested on a couple of physical devices and a virtual one with the same display features of the Moto G v2).

@StathatosAlex could you try again to launch a notebook? If you still experience the problem, could you please share some extra information (android version, browser type and version)

**Comment by lorenzo-cavazzi** [comment]
I am closing this since the notebook launch page has been completely overhauled in the meantime and I can't reproduce the problem. Feel free to re-open if you still experience the same issue.
