### ISSUE TITLE
Re-index project

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#390]
The renku-graph service may miss a notification from gitlab even when the webhook is working fine.
The user should have a "Force re-index" button in the project "settings page" to fix this.

The API endpoint is missing at the moment.

Extracted from #369

**Comment by jachro** [comment]
I think there's could be no need for such a button as there's job taking care of events synchronization between graph-services and gitlab.

**Comment by lorenzo-cavazzi** [comment]
Ok, but sometimes I still need to manually remove the webhook in GitLab and re-create it, otherwise I get no lineage information. Wouldn't a re-index button be useful to cover those cases?

**Comment by jachro** [comment]
I'm not so sure, it looks to me that this could be a bit too powerful and
too techie for a user. Maybe in some settings page if we have one?

**Comment by lorenzo-cavazzi** [comment]
Yes the idea was to put this in the project's settings page (e.g. https://dev.renku.ch/projects/112/settings).

Is a similar functionality already available in the graph repo?

**Comment by jachro** [comment]
It used to be but I removed in favour of auto re-indexing on Renku version
change.

**Comment by lorenzo-cavazzi** [comment]
Ok, and I assume the current auto re-index is not per project, right? Would it be a lot of effort to expose an API to do that?

**Comment by jachro** [comment]
The current re-index is per-project but it's automatic and does not require
any manual triggering.

I'm not entirely sure but I'd suggest leaving that option of manual
re-indexing when it's requested by users. Except for our dev environments,
it should be very unlikely users are forced to re-index. How they would
even know they need to do it?

**Comment by lorenzo-cavazzi** [comment]
I see... Then I have a different proposal. When I have this issue, I always get `200` from the `/webhooks/validation` API but I get `404` from the `events/status` API.
I would like to have an effective way to re-index the project when I end up in this state. Maybe just changing the `POST /webhooks` API so that it will always force a re-index when invoked?

**Comment by lorenzo-cavazzi** [comment]
We now have a mechanism to spot and index non-indexed projects
