### ISSUE TITLE
Improve file display / navigation

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#400]
* Provide a hierarchical view of the files. Currently this is flatten. The hierarchy should be flattened if there only < 6 entries in a further level, otherwise show hierarchically.

* Files should be badged "LFS" if they are in LFS

* The folders can be expended by clicking on the triangle, or they can be entered by double click, which updates the file view to just children of the folder

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1196411/54533219-f1f19780-4989-11e9-97b3-8eafec0f0185.png">

**Comment by lorenzo-cavazzi** [comment]
closed by #420
