### ISSUE TITLE
Not back to current project after visiting profile page

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#401]
If from a project page (for example https://renkulab.io/projects/385/)

![image](https://user-images.githubusercontent.com/4173925/54646851-bc8b9d80-4aa0-11e9-97b5-907cf183db4a.png)

I go to my profile

![image](https://user-images.githubusercontent.com/4173925/54646838-b4336280-4aa0-11e9-9d01-b4bf19e6d868.png)

the `Back to renku-ui` button doesn't bring me back to my project, but to https://renkulab.io/.

**Comment by ciyer** [comment]
This is easy to reproduce. We will fix by opening the profile page in a new browser window/tab, which is appropriate, since it is controlled by key cloak, not renku.

**Comment by cchoirat** [comment]
Does it mean that we'd have to reload/refresh project pages for changes to be applied?  If so, any downside to this?
