### ISSUE TITLE
Project Notebook Server List Not Filtered

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#410]
The notebook servers tab of a project shows *all* notebook servers, not just those for the project.

![image](https://user-images.githubusercontent.com/1196411/55246356-58599e00-5245-11e9-9a63-c16a438d075c.png)

# Solution

The topnav notebook element should show a page with all interactive environment servers. The project notebook servers tab should only show the notebook servers for the project.

**Comment by lorenzo-cavazzi** [comment]
#415
