### ISSUE TITLE
Remove the plus button on top.

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#412]
The plus button on top has redundant actions and could be removed.

**Comment by ciyer** [comment]
Multiple paths to the same action (e.g., new project) are generally. not bad -- look at the plus button on the top of this page, it includes a duplicate menu option to the new issue button above -- so I'm in favor of keeping the plus button.

**Comment by lorenzo-cavazzi** [comment]
I am also ok with keeping it. I use these shortcuts sometimes, maybe in the future we could also have more.

**Comment by lorenzo-cavazzi** [comment]
keeping it for now
