### ISSUE TITLE
Start notebook from any branch/commit

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#416]
- [ ] Add option to choose branch when launching a notebook -- should be done by attaching the `?branch=<name>` query parameter to the notebook launch POST request URL.
- [ ] Ensure that the latest commit is used when a notebook server is started (currently, we use the latest commit at the time the page was loaded. This causes problems if a user pushes between loading the view and launching a notebook server)

OPTIONAL
- [ ] Add option to choose a specific commit from chosen branch when launching a notebook. Display date and (head of) commit message per commit.

info: requires #406

**Comment by lorenzo-cavazzi** [comment]
the refactor should address also this #336
