### ISSUE TITLE
FileView/JupyterHub Button Semantics

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#428]
The JupyterHub button in the file view should have the following semantics:

- [x] If a server is running on the currently viewed commit, the button should take the user to JupyterHub and open the active file in Jupyter
- [x] If no server is running, the button should prompt the user to start a server, and the start button should take the user to a page that shows the selected notebook in a static view until the server is available (if this is difficult, it is acceptable to notify that a server is starting). When the server is available, the view should switch to the a live Jupyter display of the file.

**Comment by ableuler** [comment]
Bullet point one might be hard with JupyterLab as the notebooks are opened in tabs without changing the URL. I'm not sure it is possible to trigger opening a specific notebook in JupyterLab through a browser URL.

**Comment by rokroskar** [comment]
@ableuler adding the path to the notebook URL, e.g. `<renku-url>/jupyterhub/services/notebooks/<namespace>/<project>/<commit-sha>/<path>` will open the notebook specified in `<path>`.

**Comment by ableuler** [comment]
Ah right, just seen from the redirection that you return from the notebook server that the it's actually `/lab/tree/path/to/notebook.ipynb`.

**Comment by lorenzo-cavazzi** [comment]
The first point addressed by #556

**Comment by rokroskar** [comment]
I don't understand the second point - why is that needed?

**Comment by ciyer** [comment]
Fixed by #559.
