### ISSUE TITLE
Can I remove a project from the UI?

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#443]

**Comment by fgeorgatos** [comment]
not yet, so this is a feature request; gitlab is the place to do this, for now

**Comment by cchoirat** [comment]
I rephrase then: will I be able to remove a project from the UI at some point?

**Comment by ciyer** [comment]
It is something we will eventually support, but it is not completely straightforward. In particular, there are two cases: 

1. The project has does not reference any other projects and is not referenced anywhere
2. The project either references another project or is referenced by one

The first case is simple -- just remove the project. In the second case, we need to design a solution to what happens to the knowledge graph when a project is moved or deleted.

**Comment by lorenzo-cavazzi** [comment]
This comes a bit late, but now it's actually possible in the settings tab

![image](https://github.com/SwissDataScienceCenter/renku-ui/assets/43481553/39345a9a-c571-4238-a8e9-a34d5484430c)
