### ISSUE TITLE
Project title and project home

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#445]
[I'm on https://dev.renku.ch/project_new]

When I create a new project, say with the "First steps" title:
![image](https://user-images.githubusercontent.com/4173925/56890428-b6aeb200-6a79-11e9-827b-b1b06782b544.png)

I can't edit the project home `first-steps`.

Would it be possible to have the flexibility to do so?

**Comment by ciyer** [comment]
We automatically generate the project slug from the title.

GitLab does allow editing the project slug, but I find it very cumbersome. For example, if you change the project slug and then update the project name, your project slug gets overwritten. Also, the project slug is validated by the server, so if you put some invalid characters in there (e.g., space), you do not know until you try to create a project and it fails.

Our solution is that we just generate this slug automatically from the project title and we take care to make sure that it is valid. I prefer this solution, so I am closing the issue, but if you really want it to be editable, reopen and explain how you would like to handle the two cases that GitLab does poorly and we can continue the discussion.
