### ISSUE TITLE
Buttons in Kus tab have a wrong format

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#446]
[I'm on dev.renku.ch]

![image](https://user-images.githubusercontent.com/4173925/56890700-76036880-6a7a-11e9-99ab-7ea2e8f8d1ee.png)

Could/should it be on one line?

**Comment by lorenzo-cavazzi** [comment]
Right, it should.
There are also a few other buttons to fix on the `Kus` page, I add another screenshot and mark it as a refactoring.

![Screenshot from 2019-04-30 08-57-19](https://user-images.githubusercontent.com/43481553/56945067-0a76d500-6b26-11e9-930e-26dcd0bd686c.png)
