### ISSUE TITLE
Show a message when a file is from git lfs 

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#456]
In the file view, when a file from git lfs a message with a link to the file in Gitlab should be shown, instead of the text that is being shown now (example in the image)

![image](https://user-images.githubusercontent.com/42647877/57518287-fb0f3d00-7318-11e9-9b31-639714f3971b.png)

**Comment by ciyer** [comment]
![image](https://user-images.githubusercontent.com/1196411/101331918-ebe5cd80-3874-11eb-8701-c4b8a89e5456.png)

This has been implemented.

**Comment by ciyer** [comment]
Actually, this is only the case for files that are images. For other files, the UI still shows the LFS pointer file.

**Comment by ciyer** [comment]
Fixed in #1186.
