### ISSUE TITLE
Add preview to "commit" files in tree view

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#457]
Currently a file with type "commit" can be seen in the file tree but it can't be displayed. When this file is clicked to be previewed we should show a message like "This file can't be previewed here, see in gitlab"

**Comment by rokroskar** [comment]
do you have an example of this? what is a type "commit"?

**Comment by vfried** [comment]
> do you have an example of this? what is a type "commit"?

Yes, the VOM_NAT project has a file that git sends to us as a commit file (usually they are tree or blob). 
Example:

Here in source there is a file called VOM:
https://virginiatest.dev.renku.ch/projects/400/files 
https://dev.renku.ch/gitlab/virginiafriedrich/vom_natt/tree/master/src

![image](https://user-images.githubusercontent.com/42647877/63094905-fededb00-bf69-11e9-8e4d-369ee4f1dc1b.png)

**Comment by rokroskar** [comment]
aha ok - that's actually a whole git repository

**Comment by vfried** [comment]
I know, i think we should see if all "commit" files are like this and display a message and a link to gitlab or something.

**Comment by rokroskar** [comment]
got it, makes sense

**Comment by ciyer** [comment]
Seems to have been resolved. See https://dev.renku.ch/projects/cramakri/vom_natt/files/blob/src/VOM

Closing.
