### ISSUE TITLE
Show Project Visibility

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#470]
# Description

The project page does not show the project's visibility anywhere.

# Solution

We should add a badge for private and internal projects to show the visibility. No need to badge public projects. 

<img width="180" alt="image" src="https://user-images.githubusercontent.com/1196411/58254396-f01dc900-7d6a-11e9-94cd-d296e3762e4c.png">

**Comment by lorenzo-cavazzi** [comment]
closed by #497
