### ISSUE TITLE
Allow selection of project template

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#473]
# Description

When creating a new project, it should be possible to select a template for the project.

# Implementation

Add a template dropdown to the "New Project" page. This should (initially) retrieve a list of templates from the GitHub renku-project-template repository and present them as options in a drop down list. The list of templates is in the `manifest.yaml` file at the top level of the renku-project-template repo.

The logic in project.js::getPayload needs to be changed. Now it takes a template defined in the configuration. Instead, it will take the template selected by the user. The rest of the instantiation logic should probably be the same (see https://github.com/SwissDataScienceCenter/renku-project-template/issues/26). 

# Mockup

<img width="475" alt="image" src="https://user-images.githubusercontent.com/1196411/58504137-3f5c6300-818a-11e9-98d2-c41744d2a057.png">

Initially, the template selection can be a dropdown. Later, it should become a search box with behavior like the `Project Home` field.

**Comment by rokroskar** [comment]
can this be closed? cc @ciyer @vfried

**Comment by sdsc-org** [comment]
➤ Virginia Friedrich commented:

Yes, I closed it in github already.
