### ISSUE TITLE
Projects tab is greyed out

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#477]
![image](https://user-images.githubusercontent.com/4173925/58696581-232e1100-8398-11e9-805b-977e7ba68325.png)

It may give the impression that the `Projects` button is not active.

**Comment by ciyer** [comment]
We use Bootstrap 4.0, and this style of indicating active/inactive tabs is the new paradigm. See https://getbootstrap.com. If we had a disabled UI element, we would either not show it or leave it active, but explain why no content is visible there.

I will close the issue, but feel free to reopen with suggestion for an alternative you would prefer.
