### ISSUE TITLE
Fetch server options from the project config files

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#481]
After SwissDataScienceCenter/renku-project-template#29 is finished, we should fetch the server options for running a server from the metadata.yaml.

After the user selects which server he wants to run we should show the right links/icons in the UI (in notebook server and in the file view).

**Comment by rokroskar** [comment]
Most of the server options can't be set by the user - which did you have in mind?

**Comment by ciyer** [comment]
The list of allowable urls (/lab, /rstudio, etc.) is determined by the Dockerfile. Makes sense to have it configured in the project.
