### ISSUE TITLE
Commit hash and timestamp in file browser

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#487]
Would it be add to add some more info here

![image](https://user-images.githubusercontent.com/4173925/59196754-ce587a80-8b8f-11e9-8949-63d23f8ee19e.png)

or per file 

![image](https://user-images.githubusercontent.com/4173925/59196782-e7612b80-8b8f-11e9-9c89-da0703c39b88.png)

?

**Comment by ciyer** [comment]
This is a good suggestion. We will add it to the queue.
