### ISSUE TITLE
Handle gateway rate limit errors

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#489]
With SwissDataScienceCenter/renku-gateway#151 merged, there is now a rate limit on gateway requests, so some API requests may fail with a `429` error.
It would be nice to notify the user (globally?) when this happens to avoid errors to be overseen. Currently, this may happen more often in `/notebooks` page, but this should change in the near future and be a rare event.

**Comment by ciyer** [comment]
@lorenzo-cavazzi Is this still a problem? I don't think I have seen it in a while. If it is gone, we can close this issue.

**Comment by lorenzo-cavazzi** [comment]
I thought this could still happen because the values are still in place in the gateway, just higher than they used to be https://github.com/SwissDataScienceCenter/renku-gateway/blob/master/helm-chart/renku-gateway/values.yaml#L55-L61

I tried to open 10+ tabs on the Environments page but I never managed to get the error. Maybe we don't enforce these limits anymore? @ableuler 

Anyway, with the notification system, this should be very easy to handle.
For cases like this, I believe having a "Mark all notifications as read" on the dropdown menu would be also good.

**Comment by lorenzo-cavazzi** [comment]
P.S. I tested on dev, maybe limits are different there?

**Comment by ciyer** [comment]
This problem does not seem to occur anymore. Closing for now, re-open if necessary.
