### ISSUE TITLE
Add a link to Gitlab on Notebook Servers rows

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#493]
from @cchoirat 

Add a link to the gitlab commits on the Notebook Servers `Commit` column

![Upld](https://user-images.githubusercontent.com/43481553/59511374-5f905f80-8eb6-11e9-9866-549e2ad0a5f5.png)

**Comment by lorenzo-cavazzi** [comment]
This would be a nice feature and it's easy to add an external link to Gitlab for branches, commits and projects.
At the moment, the Gitlab URL is available only in the `Project` pages since it comes from a query to `<gateway_url>/projects/<project_id>`. This makes implementing this feature more complicated for the global "Environments" page.

We can decide to implement it only in the "Project > Environment" tab or we can get the information in one of the following ways:
* Query the project api for each project (it seems a bit overkill and requires caching)
* Add the gitlab url in the `renku.io` annotations in the pods (easy and fast, but it's redundant to get that info for every server/iteration of the polling loop).
* Get the GitLab url at some other level (it could be either an API in the gateway or injecting the gitlab API also in the UI pod)

**Comment by lorenzo-cavazzi** [comment]
To recap, this issue requires one of the 2 for moving on
* adding a `renku.io/gitlabUrl` field in the `annotations` data returned by the `/servers` API
* adding to the UI the GitLab URL
I would prefer the first but I prefer to ask for a second opinion on that

**Comment by rokroskar** [comment]
Is the git remote already in the annotations? Or does it need to be generated?

**Comment by lorenzo-cavazzi** [comment]
It's not in the annotations
