### ISSUE TITLE
Update notebook view

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#499]
Refactor the servers table used in `Project` and `Notebooks` pages to separate the `Action` button from the status indication.

This is the list of all the possible actions based on the current status:
    * running: connect, stop, get logs
    * failed: stop, get log
    * pending: get log
The "get log" functionality requires #414.

The new layout should
* [ ] Add an extra column to display the status (as a badge) and an info message when suitable (e.g. error state)
* [ ] Change the action button color back to the standard and add the proper action in the dropdown menu according to the list above.

![Screenshot from 2019-06-19 14-52-40](https://user-images.githubusercontent.com/43481553/59767169-fd62a080-92a1-11e9-92dd-ca498d430ce2.png)

EDIT: remember to edit the relevant documentation after this is closed since the layout will be completely different from the old one and possibly confusing for new users (`Environemnts` sub-pages, dropdown action buttons, ...)

**Comment by pameladelgado** [comment]
This seems like a great functionality to have.
Does the `failed` +logs option include when k8s can't schedule a notebook because of lack of resources?
What does the `stop` action do in case of failure?

**Comment by lorenzo-cavazzi** [comment]
1. Not sure if in that case the environment/pod data are returned at all, my bet is no but maybe @mohammad-sdsc has a different answer
2. The relevant code is here https://github.com/SwissDataScienceCenter/renku-notebooks/blob/0a6e3c484a04b0b217c74479cd24a7d2587fc8ff/renku_notebooks/api/notebooks.py#L192
In short, it invokes this `v1.delete_namespaced_pod( pod_name, kubernetes_namespace, grace_period_seconds=30)` where `v1` comes from the k8s python library
```
from kubernetes import client
v1 = client.CoreV1Api()
```

**Comment by mohammad-sdsc** [comment]
K8s reports PodStatus which includes information if a pod is not schedule-able. See `Unschedulable` in https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions.
This information is passed to GUI as well.

**Comment by lorenzo-cavazzi** [comment]
closed by #633
The logs feature will be addressed soon in #414
