### ISSUE TITLE
Style different types of nodes in the KG differently

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#502]
* Use KG metadata to display workflow steps and input / output data differently
* Use the file extension to display code (e.g., `.py`, .`R`, `.sh`) differently other kinds of input data

See mockup
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1196411/54537822-798fd400-4993-11e9-8c64-b3e86b052a1e.png">

**Comment by fgeorgatos** [comment]
hint: ideally, information that is seen with spaces should be underscored, since it yields a visual cue: `mypythonscript.py mydatafile.csv` , i.e. preferred for execution steps, to separate script from params.

**Comment by vfried** [comment]
I removed the dependency for this and i will close this if it's ok, this was done already

**Comment by rokroskar** [comment]
make sense to me
