### ISSUE TITLE
Search for datasets 

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#521]
The user should be able to search for datasets. 

For this we need to:
[ ] Create a new menu item next to the projects and notebooks in the top bar
[ ] Add a tab so the user can see their own datasets. 
       --> If the user is logged out a message under your project should be shown inviting the user to log in or create an account.
       --> If the user is logged in, a list of the datasets of the users should be displayed
[ ] Add a tab so the user can search for public datasets.
        --> When the user lands on this page, all datasets should be displayed.
        --> The user can search by text and order by relevant parameters.
        --> There should the same pagination system as in projects search.
        --> When the user clicks on a dataset it should be redirected to the details page of the dataset (On issue: #522)

**As a first step we will just search for datasets but not do the "your datasets" tab, and the search box will be just a free-text search box**

Mockups: 

![image](https://user-images.githubusercontent.com/42647877/61226269-66fb9080-a722-11e9-9948-8606a8bfca5e.png)

![image](https://user-images.githubusercontent.com/42647877/61226307-7d095100-a722-11e9-9d75-0c5eb3a1aead.png)

Related to https://github.com/SwissDataScienceCenter/renku/issues/594

**Comment by lorenzo-cavazzi** [comment]
As discussed during the Renku meeting:

This is a stub of the optional parameters on the `GET /datasets` API we will need
```
GET /datasets
	?query=string
	?subSet="yours"/"starred"/"all"(default)
	?orderBy="edits"/"hot"/"name"(default)
	?orderDirection="descending"/"ascending"(default)
	?filter="title"/"description"/"everywhere"(default)
	?project=string
```
The page will be available in the UI at these paths
```
/datasets
/project/{slug}/datasets
```
When showing all the datasets, it will be possible to switch between all/yours/starred datasets, while on projects the datasets will already be filtered by the project id. Everything else will be similar.

We expect these data from the API
```
- name: string
- description: string
- authors: string[]
- owner: object { // user or group info }
- stars: int
- usedIn: int
- visibility: int
```

**Comment by jachro** [comment]
I added some details for the `dataSet` GraphQL resource to [renku-graph#117](https://github.com/SwissDataScienceCenter/renku-graph/issues/117).

**Comment by rokroskar** [comment]
Why is this listed as blocking #522?

**Comment by ciyer** [comment]
#522 shows the details that you can navigate to from the search. The issue to view datasets from inside a project is #525.
