### ISSUE TITLE
Show dataset details

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#522]
The following information should be displayed:
- Dataset name
- Visibility
- Creators
- Description
- Relevant Metadata (in: https://renku-python.readthedocs.io/en/latest/models/datasets.html)
- Files in the dataset (The files also have separate metadata, we should make sure that all relevant information regarding the files is displayed, either in a table, a popup or something similar Issue: ).
- Which project the dataset is defined in
- Which projects the dataset is used in

Clicking on the dataset, takes you to the dataset details page in the project in which it is defined. Clicking on one the projects that use the dataset takes you do the project page.

Mockup:
![image](https://user-images.githubusercontent.com/42647877/61228431-93191080-a726-11e9-8a1c-f9ab9fd0c157.png)

Related to:  #594

**Comment by ciyer** [comment]
We should probably also show which projects use the dataset.

**Comment by ciyer** [comment]
We should probably also show which projects use the dataset.

**Comment by rokroskar** [comment]
I assume access rights are pulled from the project that hosts the dataset - but what happens when the same dataset is used in multiple places?

**Comment by vfried** [comment]
> I assume access rights are pulled from the project that hosts the dataset - but what happens when the same dataset is used in multiple places?

I assume that a public project has a public dataset (we should think if someone can publish a dataset without making the rest of the project public) the owner of the dataset is the user that created it, if the dataset is public everyone can re-use the dataset but not change it. (Maybe we can implement a dataset fork, but we should think about what this means). Everyone can see the details of a dataset but not edit it. 

If the dataset is private only the user can manipulate and see. Same if it belongs to a group, the group can see/edit.

Am i right? I think we should be careful with how we deal with this.

**Comment by rokroskar** [comment]
yes, this is a bit tricky. Since datasets are in the repo we can't really fully enforce that a user won't make changes to the metadata and push it. 

I think your basic proposal is correct but we'll probably need to iterate on this several times.

**Comment by erbou** [comment]
> I assume access rights are pulled from the project that hosts the dataset - but what happens when the same dataset is used in multiple places? 

Note: if the data is sensitive, its designated data steward must stay in control of who can access it, even if this data is accessed from multiple places. No one, including owners from other places, should be able to override the access rights granted by the steward. In other words, this decision should come from the source, not from other places that reference it.

**Comment by rokroskar** [comment]
Sorry I've sort of lost track of the various dataset issues, but is this supposed to be about datasets in the global view (i.e. not project-centric)?

**Comment by vfried** [comment]
Yes, this is for datasets in the global view, it's blocked by the search because before we display a dataset we need to be able to find it (ideally).

**Comment by rokroskar** [comment]
Right, I was just wondering if for a first iteration just listing datasets would be enough. A faceted browser/filter based on keywords might be more useful than full text search.

**Comment by rokroskar** [comment]
@vfried can this be closed?

**Comment by vfried** [comment]
Yes, closing it now.
