### ISSUE TITLE
Create a dataset in project

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#524]
[restricted the issue to just creating a dataset within a project]

The dataset tab of a project should have a button for creating a dataset.

The page for creating a dataset should have a form with the following parameters:
- Name
- Description
- Files (there should be a metadata file and 0 or more data files)

![image](https://user-images.githubusercontent.com/1196411/67273750-5bf19280-f4bf-11e9-9091-9e016eea7c86.png)

![image](https://user-images.githubusercontent.com/1196411/67270457-01553800-f4b9-11e9-9f88-1ecbbd4a77b3.png)

Related to #594

**Comment by ciyer** [comment]
I think the ability to create a dataset should also be in project, and creating a dataset from dataset search will require providing a project as well.

**Comment by vfried** [comment]
We should also allow the user to upload files from a URL (like in the CLI)

**Comment by rokroskar** [comment]
can this be closed?
