### ISSUE TITLE
Add a datasets tab inside a project page

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#525]
Inside the project overview page, there should be a dataset page.

![image](https://user-images.githubusercontent.com/1196411/61541039-214f0880-aa3f-11e9-8225-807a16b1ef01.png)

Clicking on a dataset takes you to the project dataset details page.

The following information should be displayed:
- Dataset name
- Visibility
- Creators
- Description
- Relevant Metadata (in: https://renku-python.readthedocs.io/en/latest/models/datasets.html)
- Files in the dataset (The files also have separate metadata, we should make sure that all relevant information regarding the files is displayed, either in a table, a popup or something similar Issue: ).

Mockup:
![image](https://user-images.githubusercontent.com/42647877/61228431-93191080-a726-11e9-8a1c-f9ab9fd0c157.png)

(if the user clicks on the title of a dataset she should be redirected to the dataset details page ( #522 )

Related to SwissDataScienceCenter/renku#594

**Comment by ciyer** [comment]
It should also be possible to manage data sets (create, delete, rename) here.

**Comment by rokroskar** [comment]
can this be closed?

**Comment by vfried** [comment]
It has only been pushed to the feature branch, and we are still not fetching the datasets from the KG. But that can go in a new issue i guess.

**Comment by rokroskar** [comment]
Right forgot about that - no lets keep it open until it's complete. Thanks!
