### ISSUE TITLE
Select datasets to add to new or existing project

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#527]
Either on the project search or on the create project page there should be an instance where the user selects datasets and is redirected to the create project page, so a project is created using the selected datasets.

(We should discuss about how we will do this, i don't think doing a basket that will be across the entire user interface is a good idea, I propose we either keep it in the datasets search or we implement a workflow like project creation page).

**Comment by ciyer** [comment]
There are a few paths that we need to handle:

1. Dataset Search
- User on dataset search selects some datasets
- These can be added to an existing project, or a new project can be created to add these to

2. Project 
- User on a project page selects some datasets to add to the project

3. External tool
- User is on an external tool (e.g., Dataverse) and wants to "open" the dataset in Renku
