### ISSUE TITLE
Accessibility: UI does not display correctly with larger font sizes

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#537]
On dev, I see

![image](https://user-images.githubusercontent.com/4173925/61693311-a54f0c00-ad2f-11e9-8006-e99272c5afdd.png)

independently of the zoom level

**Comment by rokroskar** [comment]
It renders correctly on my machine, I tried Firefox and Safari. Which browser are you using?

**Comment by cchoirat** [comment]
chrome

[image: image.png]

**Comment by rokroskar** [comment]
Tried with chrome as well, seems fine.

**Comment by lorenzo-cavazzi** [comment]
I cannot reproduce it on chrome as well, even when playing with zoom and window dimensions.

Does this happen with all the projects or only with a specific one? Could you please add the exact link to a page where you notice this and a screen that includes all the browser?

**Comment by cchoirat** [comment]
https://dev.renku.ch/projects/408/ for example.

it happens with all the projects i tested:

[image: image.png]

**Comment by cchoirat** [comment]
Ops, missing image:

![image](https://user-images.githubusercontent.com/4173925/61702109-88223980-ad3f-11e9-965b-d389b565832e.png)

**Comment by vfried** [comment]
I also tried to reproduce it and couldn't. Is this still happening to you?

**Comment by cchoirat** [comment]
One on computer yes, on the other no (different OS X versions and possibly
screen resolutions).

**Comment by cchoirat** [comment]
Thanks to @emmjab for figuring it out.  It seems to come from my chrome font preferences.

![image](https://user-images.githubusercontent.com/4173925/64277603-054dea80-cf4b-11e9-9c08-318fb5ea58ea.png)

When I switch from `Large` to `Normal`, it behaves as expected.

**Comment by ciyer** [comment]
Good that we now understand this. But it is an accessibility issue that the UI (e.g., the numbers in the fork/star buttons) do not display correctly at this larger font size. I am rename the issue, but it remains relevant.

**Comment by cchoirat** [comment]
Is because size is specified in pixels/cm and not in percentage?  @ciyer @lorenzo-cavazzi Is it hard to fix?  Thanks!
