### ISSUE TITLE
Show Notebook Servers tab to users without sufficient privileges to launch the interactive session

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#565]
# Description

There are two issues with launching interactive environments:
1. If the user gets logged out, then the Interactive Environment (Notebook) tab disappears
2. If user is logged in and does not have appropriate permissions, we do not show the interactive environment tab

We want to fix both of these.

# Details

At the moment, we simply do not show any notebook/interactive environment launch options for users that do not have the requisite permissions on a project. Instead, we should guide the user through the possible steps to get an environment running. 

For example, when clicking on a "start new server" button, the user could be shown an option to fork the project and initiate the launch from there. 

cc @cchoirat @emmjab

**Comment by lorenzo-cavazzi** [comment]
A first simple implementation may be the following:

* [ ] anonymous users: display a "please log in" message
* [ ] users without sufficient privileges: display a "how-to" message to start an interactive environment along with the fork button
