### ISSUE TITLE
Use a term other than 'notebooks' for the interactive environments

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#568]
# Description

'Notebooks' and 'Notebook Servers' only makes sense for Jupyter Notebooks, but we also support R-Studio and may support other environments in the future. So we need a better term for this feature.

# Proposals

- Servers
- Interactive Environments
- Live Environments

**Comment by rokroskar** [comment]
I personally like "interactive environments" - "servers" imo sounds too much like we're giving someone a VM.

**Comment by lorenzo-cavazzi** [comment]
+1 for not using "servers".
I kind of prefer "Live Environments" over "Interactive Environments" but both are fine for me

**Comment by lorenzo-cavazzi** [comment]
In the meanwhile, I have started using "Interactive Environments" in the new PRs. I will go on with that if no one disagrees.
This requires also a refresh of the documentation pages/images -- that is needed anyway since a few screenshots are already different from the UI.
