### ISSUE TITLE
Notebooks do not include GPU request when launched

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#574]
## Description
When I try to launch a notebook on [limited](https://limited.renku.ch/) and get the GPU request set to `false` instead of 1 or 2. The notebook is launched without a GPU request in its pod, as a consequence the notebook starts but is not scheduled and not using a GPU.

![gpu-request-false](https://user-images.githubusercontent.com/43743260/63414088-6201bf00-c3fb-11e9-89c2-b6a4ab3a7b83.png)

Renku version: 0.4.1
Notebooks version: 0.4.0

**Comment by lorenzo-cavazzi** [comment]
I moved this to renku-ui since it seems to be a UI related issue -- I verified that the information returned by renku-notebooks APIs is correct
