### ISSUE TITLE
Number of forks reported incorrectly

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#581]
See images:

This project has been forked (see below), but the number of forks is not currently listed:

![image](https://user-images.githubusercontent.com/1196411/63761207-0636aa80-c8c1-11e9-93e7-6c43112e1b39.png)

![image](https://user-images.githubusercontent.com/1196411/63761147-eacb9f80-c8c0-11e9-99e8-91d02ec23a83.png)

**Comment by lorenzo-cavazzi** [comment]
It seems that also the "Details" page on GitLab doesn't show the proper "Fork" number.
![Screenshot from 2019-08-27 11-57-03](https://user-images.githubusercontent.com/43481553/63768277-186c1500-c8d0-11e9-8b41-842b27ec7ab8.png)

Yet, if I click on the number of fork (that is currently 0) I end up in the list of forks where your is listed correctly. This is strange behavior from GitLab
![Screenshot from 2019-08-27 13-40-23](https://user-images.githubusercontent.com/43481553/63768381-56693900-c8d0-11e9-9bea-ff002731774e.png)

**Comment by ciyer** [comment]
Closing as a bug in the underlying API for now.
