### ISSUE TITLE
Run image build pipeline on all branches after a project fork

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#589]
The recently introduced feature which triggers an image build after the fork is very nice. However, it's currently only activated for the master branch. It would be nice if the image build was triggered on all branches except those for autosave purposes.

**Comment by lorenzo-cavazzi** [comment]
This can potentially be overwhelming, but now the UI shows an error when the image is missing and allows to build it on request for the last commit on any branch
