### ISSUE TITLE
Persistent KG popup for a private project

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#594]
I want to permanently deactivate the KG integration, but this keeps showing up:
![image](https://user-images.githubusercontent.com/4173925/64277863-a8066900-cf4b-11e9-954f-090f4d970ad7.png)

**Comment by ciyer** [comment]
Yes, I agree, this is annoying. The solution needs two parts:
1. Make it possible on the settings page to activate the KG. The user may change their mind in the future
2. Provide the options: "Not now", and "No" (and do not ask again) to the dialog. For the "No" option, we need to store somewhere that the user has explicitly opted out.

**Comment by lorenzo-cavazzi** [comment]
I have checked possible alternatives to save project-related metadata in GitLab and, after a quick discussion with @jachro, it seems that the KG may be the best candidate.
This requires an API to store/retrieve the information from the UI (graphQL endpoint). It makes sense to briefly discuss the solution before going in that direction.

**Comment by rokroskar** [comment]
> it seems that the KG may be the best candidate

so you will store data in the KG for a project that doesn't want its data in the KG? :)

**Comment by lorenzo-cavazzi** [comment]
Ahah yes. The project won't be indexed, but a few metadata about the project (user config data) may still be saved there. My understanding is that in the future also those projects will be (at least partially) indexed but the data won't be exposed.

The alternative is to store these metadata in the existing postgres DB (we should create an API to interact with it) or to create a new DB.

**Comment by lorenzo-cavazzi** [comment]
Once SwissDataScienceCenter/renku-gateway#183 will be in place, we can use those API to store this information in the gateway Redis instance

**Comment by ciyer** [comment]
Closing since we will switch to having all projects in the KG always.
