### ISSUE TITLE
Release 0.7.0 UI Fixes

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#601]
Various bugfixes we want in the next release

**Comment by rokroskar** [comment]
I think you want `0.6.6`? I think the current state of the UI could be a bugfix release already making it `0.6.5`?

**Comment by ciyer** [comment]
Since 0.6.5 is the next release ATM, I will leave that in the title, but I will update the title if we make a release before the issue is closed.
