### ISSUE TITLE
Open GitLab on same file as Renkulab?

### ISSUE THREAD

**Issue by cchoirat** [SwissDataScienceCenter/renku-ui#603]
Suppose I'm viewing a file in Renkulab (e.g., Dockerfile).  Is it possible / of interest to have the `View in GitLab` button open the same file (and not the toplevel repo view)?

**Comment by rokroskar** [comment]
If you click the gitlab icon on the right-hand side, that's exactly what happens

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/3353586/64494957-c514a200-d293-11e9-9982-8d5e9ebf0585.png">

**Comment by ciyer** [comment]
Closing as already implemented. Reopen and add extra information if the initial question was misunderstood.
