### ISSUE TITLE
Fetch datasets information for projects from the KG 

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#604]
We should fetch dataset information from the KG endpoint.

API Description: https://github.com/SwissDataScienceCenter/renku-graph/blob/dataset-info/knowledge-graph/README.md

The results from the fetch should be displayed here: #562

Blocked by:
https://github.com/SwissDataScienceCenter/renku-graph/issues/97

**Comment by rokroskar** [comment]
Isn't this finished @vfried?
