### ISSUE TITLE
Improvements to help access & content

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#607]
# Description

We want to make several improvements to the help page.

# To Do

### Display version information

It would make sense to show the version information somewhere in the UI. GitLab does this in the help page, which would make sense for Renku as well.

# Implemented:

* Rename "Discourse" to "Forum"
* Easier access to help in menu
* Easier access to Forum and GitHub from bottom menu

# Under Consideration

* Rename "Gitter" to "Chat"

**Comment by ciyer** [comment]
From where can we acquire version information? I think it would make sense for the gateway to provide it.

**Comment by ableuler** [comment]
Hmm, I'm not sure if it would make sense to display version information just for Renku or also for the components?

**Comment by ciyer** [comment]
I think we would display information for all the components.

**Comment by rokroskar** [comment]
That needs a service with access to the k8s API

**Comment by emmjab** [comment]
My POV: 

maybe along the lines of adding "help" to the names for things: 

### rename "Discourse" to "Help Forum"

and I vote for adding `Help` to the top navbar where gitlab has it, but explicitly write "Help"

**Comment by ciyer** [comment]
This is what is currently implemented:

![image](https://user-images.githubusercontent.com/1196411/78031539-f8b83600-7363-11ea-92cc-16478e9d8f4d.png)

**Comment by ciyer** [comment]
Closing as out of date.
