### ISSUE TITLE
bug: forking project pop-up spinning wheel forever

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#610]
The issue: Tried to fork a project in SV, but the UI pop-up showed a spinning wheel that seemed to be stuck. I visited the project in GitLab and it turned out to have been successfully forked, so I force-refreshed the Renku UI and was able to see the files. However, the GitLab CI/CD was never triggered.

Questions
1. Why was the wheel spinning forever? From a user's perspective it seems like the fork is not working.
2. Why wasn't the pipeline triggered?

I exported the project from SV to dev and seems to show the same behavior, so you can test forking it: https://dev.renku.ch/projects/e.jablonski/from-sv-testing-fork

**Comment by ciyer** [comment]
Do do not see the project linked to above. Is it possible that it is private?

**Comment by vfried** [comment]
I will check on this

**Comment by vfried** [comment]
Addressed in #615
