### ISSUE TITLE
Improve the pipeline functionality after a project is forked.

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#617]
We should add a button that allows the user to re-run the pipeline after a fork if the pipeline run fails. 

We could also add a button/checkbox to run the pipeline in all branches to address #589 .

**Comment by lorenzo-cavazzi** [comment]
I believe the first case is already covered. If the pipeline fails, the user should get notified as soon as he tries to start a new interactive environment (it considers only `master`)

**Comment by vfried** [comment]
yes, i know you can do that, but I think we could also put this button in the fork project window

**Comment by lorenzo-cavazzi** [comment]
Done
