### ISSUE TITLE
Add a force parameter to `Model.setObject`

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#631]
The `Model.setObject()` function allows setting different properties at the same time, triggering a single refresh to the UI (a single `UPDATE` actions goes through the redux store).

Anyway, since it doesn't touch/overwrite properties of an object that are not explicitly added to the object, it's sometimes needed to split it one or multiple `Model.set()` calls.
E.G. reset `filter.commit` data
> `Model.get("filter.commit")`
> { id: 1234, author: xxx, active: true }
>`Model.setObject("filter.commit", {})`
> { id: 1234, author: xxx, active: true }
>`Model.setObject("filter.commit", { active: false })`
> { id: 1234, author: xxx, active: false }
>`Model.set("filter.commit", {})`
> { }

Since `Model.set()` works on a single variable, it's desirable to have a mechanism to force overwriting the involved objects when using `Model.setObject()`.
> `Model.get("filter.commit")`
> { id: 1234, author: xxx, active: true }
>`Model.setObject("filter.commit", { active: false }, true)`
> { active: false }
>`Model.setObject("filter.commit", { }, true)`
> { }

**Comment by ciyer** [comment]
Would
```model.setObject(key, obj, overwrite)``` be a better API?

**Comment by lorenzo-cavazzi** [comment]
I agree, that would be better. I updated the initial post to use the `setObject` function with an extra parameter instead of a new function

**Comment by lorenzo-cavazzi** [comment]
Unfortunately, the examples in the first post are wrong. The syntax for `.setObject()` requires a single object as a parameter `Model.setObject({filter: { commit: { active: false }}})`.
This makes it more difficult trying to guess at which level the `overwrite` parameter should intervene -- most probably in the above example I don't want to remove all filter's siblings attributes.

A naive idea could be specifying the overwrite depth level  -- e.g. `1` for cleaning every sibling of `active`, `2` for siblings of `commit`, ... This is not very flexible though.

Another approach, since we already use `immutability-help` under the hood, would be to allow using its powerful syntax https://github.com/kolodny/immutability-helper#available-commands
