### ISSUE TITLE
re-use already-run build pipeline from forked project

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#634]
When you fork a project via the renku web interface, the build pipeline is triggered. If this is a long running build, if you immediately try to start a notebook you will see the build icon. However, it is often the case that there is already a build in the forked project.

Gitlab's default behavior when you fork a project (using the gitlab interface) is that the pipeline is already built, and if you view this project in renku, you are able to use this image when you spawn a notebook.

**request**
Replicate gitlab's default behavior when forking projects -- i.e. keep the build pipeline from the forked project -- so that we can immediately use the docker image when starting a notebook.

**Comment by rokroskar** [comment]
I don't think this is the default gitlab behavior - typically when you fork a project there are no CI pipelines, you have to trigger one. Closing for now - please reopen if this is not the case and there are some details I've overlooked.
