### ISSUE TITLE
Incorrect username displayed when creating a new project [Buhler]

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#635]
**Description**
Incorrect username displayed when creating a new project and when forking a project [Buhler]

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://renku.buhler-datascience.ch/ and login
2a. Go to Project --> New Project
2b. Go to a project --> Fork 
3. See error in screenshots, name displayed is incorrect for current user: `{user}`
4. The project is created successfully despite the display 

Alternatively selecting "Pamela Delgado" from the dropdown menu also creates the project successfully.

**Expected behavior**
The correct username should be displayed, just as in the user's homepage.

**Screenshots**
Display when forking a project:
![userid-display-fork](https://user-images.githubusercontent.com/43743260/65892075-f4579400-e3a5-11e9-8132-2560f6bd5607.jpg)

Display when creating a new project:
![userid-display-new](https://user-images.githubusercontent.com/43743260/65892085-f9b4de80-e3a5-11e9-8382-c6672f464fcd.jpg)

Home page display:
![home-username](https://user-images.githubusercontent.com/43743260/65892089-fd486580-e3a5-11e9-8e9c-0cdb5253cc14.png)

**Additional information**
Gitlab version `12.3.1`. We could ask to grant temporary access to debug that deployment, otherwise I could create a deployment with that gitlab version (would take more time).

**Comment by lorenzo-cavazzi** [comment]
We found out that in Buhler's Gitlab deployment the information returned by `/namespaces` API is slightly different than all the other environments (gitlab.com included).
Here is an example
```
// gitlab.com
[
    {"id":2834103,"name":"renku","path":"renku"},
    {"id":4007797,"name":"pameladelgado","path":"pameladelgado"}
]

// Buhler
[
    {"id":39,"name":"Pamela Delgado","path":"delgadop"},
    {"id":66,"name":"sdsc-sysadmin","path":"sdsc-sysadmin"}
]
```
In the second case, `name` and `path` are different. A possible solution to address this issue is to use `path` instead of `name` when filtering the list of valid namespaces.
