### ISSUE TITLE
Display a meaningful error when project can't be created

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#636]
**Description**
When user can't create new projects on Gitlab, Renku displays error `namespace: is not valid`

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://dev.renku.ch/ or any other Renku deployment and login with a user that doesn't have the rights to create new projects
2. Go to Project --> New Project
3. See error in screenshots, project can't be created because user can't create new projects on gitlab but error message is incorrect `namespace: is not valid`

**Expected behavior**
A more meaningful error should be displayed `user reached the project limit`, see second screenshot.

**Screenshots**
Error message when creating a new project on Renku:
![limit-namespace-display](https://user-images.githubusercontent.com/43743260/65942038-b94c7380-e42c-11e9-95d9-e25d7368445b.png)

Warning message on Gitlab:
![limit-gitlab-error](https://user-images.githubusercontent.com/43743260/65944523-2f070e00-e432-11e9-85e5-7a2bdfa1cd3a.png)

**Additional information**
This happens in any Renku deployment.

**Comment by lorenzo-cavazzi** [comment]
The error message you see is actually very close to the one currently returned by the `POST /projects` GitLab API

> `{"message":{"namespace":["is not valid"],"limit_reached":[]}}`

We currently filter error messages without explanation, this is why no reference to the reached limit is displayed. I suggest to do as follows:

* Display all error message, even without explanation. In this case it will display something like
![Screenshot_20191029_144107](https://user-images.githubusercontent.com/43481553/67772469-66c99b80-fa5a-11e9-8f70-475ed626fc2b.png)
* If this is a common error, we can easily display something more informative to the user. I'll create a PR with a proposed solution

**Comment by pameladelgado** [comment]
Ok I see.
Although it would be nice to get a meaningful error for the user, I understand that it is not practical to translate all GitLab errors into user friendly feedback.
For me, having all the errors displayed including the ones without explanation is better than filtering them. For instance, `limit_reached` would have definitely make me think that something else than the gitlab version was the cause of the problem.
 
In addition to your suggestion I think we could specify that where/when the error comes from. In this case is Gitlab and not the user or Renku. For errors in GitLab we could maybe even refer the users to test creating/forking a project in GitLab to see more details.

Thanks for looking into this issue.

**Comment by lorenzo-cavazzi** [comment]
You are right, handling all the errors is practically impossible, but we can still display something more user-friendly for the most common cases.

I am not sure if we want to suggest users trying out things in GitLab for debugging errors. Anyway, the process of creating a new project in the UI will change soon as part of SwissDataScienceCenter/renku#611 and we will make sure to make errors more understandable.
