### ISSUE TITLE
UI support for personal environments

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#639]
# Description

Add UI for creating the repository with the user personal preferences. The user settings options should include a link to the repo that contains the personal preferences (the exact name of this repo is determined in the "Inject user preferences" issue). If the repo does not exist, give the user an option to create this repo.

**Comment by rokroskar** [comment]
The backend side is being implemented in https://github.com/SwissDataScienceCenter/renku-jupyter/pull/65

I suggest we stick to a hard-coded name for now unless there is some strong reason to leave this up to the user.
