### ISSUE TITLE
Opt-in project into Renku

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#640]
# Description

Not all projects in a GitLab instance are Renku projects. Even some projects that are for Renku might be internal projects (templates, personal preferences). We should have an explicit mechanism for displaying a project in the project search. Maybe a tag.

**Comment by lorenzo-cavazzi** [comment]
Renku 2.0 will disentangle Projects and Repositories. This removes the need to have a filtering system for non-Renku repositories
