### ISSUE TITLE
UI Support for Instance-Level Templates

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#641]
# Description

When creating a new project, the UI displays a list of templates that come from a helm-configurable repository. We should add a second such configuration for instance-level templates. This configuration would contain the URL to a repository that contains templates for the instance. This project should have the same structure https://github.com/SwissDataScienceCenter/renku-project-template with a manifest.yml and folders for each template. If this value is configured, we should show the instance-level templates together with the global templates in the UI.

# Documentation

We should document how to create instance-level templates. Otherwise, this feature isn't really useable.

**Comment by rokroskar** [comment]
Should this be a list of potential template sources rather than a single repo?

**Comment by lorenzo-cavazzi** [comment]
As discussed, it makes sense to wait for the service endopint for project creation to be ready
