### ISSUE TITLE
lineage display for multi-project workflows

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#642]
**Problem**
Users want to be able to view the lineage of a workflow that spans multiple projects (i.e. in the simplest case: data in one project, analysis run in another project).

(1) The lineage view should let you click links between projects. For example currently, when an input to a `renku run` is a renku dataset stored in another project, you cannot click on its icon in the lineage view. ~The same applies when viewing the lineage of the dataset from the dataset project -- you cannot click on scripts/outputs belonging to another project.~ --> moved to #644 

(2) on the lineage view, there is no information regarding the project where files are "imported" from. For instance, if an input belongs to another project, the name of the input file appears, but not the name of the project it belongs. In practice, this kills the traceability of files across projects.

**Comment by lorenzo-cavazzi** [comment]
Thanks for reporting this, it was already on our to-do list but we didn't have a formal issue yet. If you don't mind I will split the issue into 2 since the dataset specific part should be treated separately.

**Comment by lorenzo-cavazzi** [comment]
The Lineage feature won't be further expanded since it won't be part of the new version of the Renkulab platform ([more info on Renku 2.0](https://blog.renkulab.io/renku-2)).
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
