### ISSUE TITLE
Add files to a dataset

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#650]
# Description

The UI should let users add files to datasets. The user can either upload individual files, upload a directory tree or add files that are already in the repo.

![image](https://user-images.githubusercontent.com/1196411/67273750-5bf19280-f4bf-11e9-9091-9e016eea7c86.png)

![image](https://user-images.githubusercontent.com/1196411/67271201-5d6c8c00-f4ba-11e9-80e7-8f1f712f5c57.png)

# Details

When uploading a directory tree, the contents will need to be converted into an archive (zip or tar, e.g.) and uploaded as a single file. The dataset service should have an option to unarchive an uploaded file.

**Comment by vfried** [comment]
This was closed with #744
