### ISSUE TITLE
Copy button for project URLs and file paths

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#653]
# Description

Project URLs should have a copy button

![image](https://user-images.githubusercontent.com/1196411/67568378-5c429580-f72c-11e9-8280-2dfe7e94a6b6.png)

**Comment by rokroskar** [comment]
also file paths: 

![image](https://user-images.githubusercontent.com/3353586/67568661-176b2e80-f72d-11e9-9d46-b2035ea2d0f7.png)
