### ISSUE TITLE
Enable changing a Renku project's title

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#661]
**Kind** 
Feature request

**Description**
Currently there is no way of changing the title of a project in Renku.
A project's title can be changed in GitLab, in which case there are two project titles: the one on GitLab and the one on Renku which are different (we probably want to keep them in sync?).

**UPDATE** the project title is correctly updated, what did not change was the project's path. We might want to avoid doing this as it has unintended consequences (see Gitlab rename path warning screenshot). Furthermore, if there's some image in the registry, GitLab would not allow the renaming of the path (see last screenshot).

**Screenshots**
* Renku project title display
![changed-name](https://user-images.githubusercontent.com/43743260/67860635-a8bc1580-fb1e-11e9-8b9d-c859768d97c6.png)

* GitLab rename path warning
![rename-warning](https://user-images.githubusercontent.com/43743260/68014169-0bccba00-fc8f-11e9-986c-642fc17b7d50.png)

* GitLab rename path error
![rename-project-error](https://user-images.githubusercontent.com/43743260/68014175-0f604100-fc8f-11e9-88ac-0d6e354296cf.png)

**Comment by lorenzo-cavazzi** [comment]
In the description, it seems that the title on GitLab and on Renku are different. We verified that modifying the title on GitLab results in a different title also on Renku. On the other hand, changing the project's path is a bit trickier. For that, It's probably easier to fork your own project on a different path.

**Comment by pameladelgado** [comment]
There's also no functionality to change the project's name from the Renku UI. If changing the project's name does not have a consequence on the lineage, we could provide this functionality and discourage changing the project's path.
![project-settings](https://user-images.githubusercontent.com/43743260/67931793-ec685b00-fbc2-11e9-967f-a3aae6c804e8.png)

**Comment by pameladelgado** [comment]
Another thing that is a bit confusing when changing the project's name and not the path is that is harder to find it in the list of projects (where only the path and not the name is shown). Maybe we can add the project's name there as well?

**Comment by ciyer** [comment]
Related to #130.

**Comment by rawlik** [comment]
I just found myself in the need of changing the project's title. It was originally the same as the intended title of the associated publication, but our reviewers requested the tile to be changed.

It would be much nicer to have the project the same title as the publication.

The project is: https://renkulab.io/projects/stamplab/phase-contrast-beats-attenuation-for-breast-ct

**Comment by lorenzo-cavazzi** [comment]
[Renku 2.0](https://blog.renkulab.io/renku-2) will disentangle Projects and Repositories.
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
