### ISSUE TITLE
Notebooks in issue comments should be connectable to an environment

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#677]
# Description

A notebook that is displayed in an issue should offer a button to connect to an interactive environment.

See https://dev.renku.ch/projects/virginiafriedrich/zurich-bikes-2/collaboration/issues/9/

**Comment by ciyer** [comment]
This will be made obsolete if pursue #1330

**Comment by lorenzo-cavazzi** [comment]
See previous comment
