### ISSUE TITLE
Techblog on Renkulab

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#695]
# Description

We want to highlight some of the new features in greater detail that is appropriate in the main documentation. For this purpose, it would be nice to have a tech blog that would be available on Renkulab.

**Comment by lorenzo-cavazzi** [comment]
We now have a  Renku blog https://blog.renkulab.io :tada: 
Further issues on that can be opened in the respective repository https://github.com/SwissDataScienceCenter/renku-blog
