### ISSUE TITLE
bug: create new project on renkulab uses old template sometimes

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#701]
When creating a new project on renkulab.io after the release, sometimes the old template is used. I couldn't determine how to consistently reproduce this, but here's the sequence of events:

0. Created a new project yesterday assuming it was the new template on new renkulab, and got the old one.
1. I ctrl-shift-R and created a new project, it was still the old template.
2. I logged out and logged in again, created a new project and got the new template.
3. Then created another new project, assuming the problem was fixed, and got the old template again.
4. Following day, I re-logged in (had been logged out) and made a new project, was the old one again.
5. Ctrl-shift-R without logging out and in again and got the new one. 

Old project: https://renkulab.io/projects/emma.jablonski/permafrost-art-nouveau
New project: https://renkulab.io/gitlab/emma.jablonski/permafrost-refresh

**Comment by ciyer** [comment]
This problem will be resolved when we start using the renku service to create projects instead of doing it ourselves in the UI. Closing as this is addressed in #703.

**Comment by rokroskar** [comment]
But is it still going to result in buggy projects being created until that is done?

**Comment by ciyer** [comment]
Possibly, but we do not understand exactly how this happened, and we cannot recreate it. I think the best course of action is to implement #393 and then keep an eye out for it again.

**Comment by emmjab** [comment]
I should add that in testing a different bug, the issue came up again for the release on `limited`, this time with firefox (initial issue was on chrome). The case being: a hard refresh was done on `limited`, followed by seeing the new UI, followed by logging in a few days later and finding the old UI again. (@pameladelgado )
