### ISSUE TITLE
bug: unable to fork project and rename

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#704]
In the latest release, the ability to change the name of a forked project was added, so you can fork a project more than once (🎉), however it doesn't seem to be working.

Users want this feature so that they can create & use templates from the same initial project (i.e. a project called `pipeline-project` could get forked several times to create `pipeline-project-1`, `pipeline-project-2` which all rely on the same template.

**Steps to reproduce**
1. Create a new project
2. Press the `fork` button
3. Change the title in the fork in the pop-up that appears
4. Press the `fork` button
5. Error results

Here's a screenshot of the issue (project originally called `renku-env`):
<img width="1288" alt="unable_to_fork" src="https://user-images.githubusercontent.com/1056472/70037122-56a35f80-15b6-11ea-81e0-a15a45b454ec.png">

**Comment by emmjab** [comment]
Note: it *does* work on `dev`, but not on renkulab.io or limited

**Comment by lorenzo-cavazzi** [comment]
Thanks for this info! I see the gitlab version is different, maybe that's related. We will check

**Comment by pameladelgado** [comment]
yes, the version of gitlab is different. I will try upgrading on limited first and let you know

**Comment by pameladelgado** [comment]
Confirmed, with a newer version of GitLab this functionality works as expected. Closing the issue.

**Comment by rokroskar** [comment]
@pameladelgado are you upgrading gitlab on renkulab then as well?

**Comment by pameladelgado** [comment]
yes, I will upgrade GitLab on renkulab this evening. Made a PR for a bugfix on the release https://github.com/SwissDataScienceCenter/renku/pull/714
