### ISSUE TITLE
The "Go to source" button for datasets projects leads to nothing at the moment (for datasets created inside renku)

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#729]
The go to source button inside datasets leads to nothing for datasets created inside renku, we need to find a way of checking which datasets are created in renku and imported datasets, so we only display this button for the datasets imported from different sources.

![image](https://user-images.githubusercontent.com/42647877/72916038-8ca4ca80-3d41-11ea-91f7-673f31e4963a.png)

**Comment by vfried** [comment]
I think we can close this... the button takes the user to the dataset itself...  if the user clicks from inside a project it thakes the user to the general dataset view (outside the project)

**Comment by ciyer** [comment]
I think we can at least remove the button if it would take the user back to the page the user is on.
