### ISSUE TITLE
Can't scroll in start environments screen (not always)

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#734]
Christine detected a problem in the start environments page, sometimes she can't scroll down.

This is with Chrome up to date.

**Comment by ciyer** [comment]
To recreate, change the Appearance settings and make the font size "Very large." Make the window small enough that the "Start Environment" button is not visible. It is not possible to scroll down to it.

![image](https://user-images.githubusercontent.com/1196411/73251661-a5860380-41b9-11ea-90b0-d4a3a658c1e9.png)

![image](https://user-images.githubusercontent.com/1196411/73251716-c2bad200-41b9-11ea-9a1f-6aa4be3081a9.png)

**Comment by lorenzo-cavazzi** [comment]
This doesn't seem to happen anymore on the new components
