### ISSUE TITLE
bug: checkbox to fetch gitLFS for interactive env

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#736]
**Issue**

The checkbox configuration option to include gitLFS objects upon starting an interactive environment doesn't seem to work.

1. start a new environment https://renkulab.io/projects/emma.jablonski/dataverse-import/environments with the checkbox checked
2. check if data is a pointer or real data (it's just a pointer)
```
$ cat data/l1688_dust_temperature_a_1/tau350um_L1688_meisner.fits 
version https://git-lfs.github.com/spec/v1
oid sha256:b1e9e7b64cdef1ffcd81537d72676c0791ce1e4dbdf400d4d49702fdadcc15f0
size 167040
```
3. check if I can `git lfs checkout` (the ui checkbox said it "fetches", so if it's already fetched I should be able to `checkout`) -- could not, "content not local":
```
$ git lfs checkout
Skipped checkout for "data/astropy/:persistentId", content not local. Use fetch to download.                                          

Errors logged to /work/dataverse-import/.git/lfs/logs/20200128T103405.353602163.log
Use `git lfs logs last` to view the log.
Skipped checkout for "data/l1688_dust_temperature_a_1/T_L1688_meisner.fits", content not local. Use fetch to download.

Errors logged to /work/dataverse-import/.git/lfs/logs/20200128T103405.360533998.log
Use `git lfs logs last` to view the log.
Skipped checkout for "data/l1688_dust_temperature_a_1/tau350um_L1688_meisner.fits", content not local. Use fetch to download.

Errors logged to /work/dataverse-import/.git/lfs/logs/20200128T103405.361946879.log
Use `git lfs logs last` to view the log.
Skipped checkout for "plots/T_L1688_meisner.png", content not local. Use fetch to download.

Errors logged to /work/dataverse-import/.git/lfs/logs/20200128T103405.363357663.log
Use `git lfs logs last` to view the log.
Skipped checkout for "plots/tau350um_L1688_meisner.png", content not local. Use fetch to download.

Errors logged to /work/dataverse-import/.git/lfs/logs/20200128T103405.364692201.log
Use `git lfs logs last` to view the log.
Checking out LFS objects: 100% (5/5), 569 KB | 0 B/s, done
```

**Solution**
update the functionality of the checkbox to do the `git lfs pull` (combination of fetch and checkout).
**however** -- along the same lines of `dataset import`, if it's possible to display *how much* data will be pulled, or get a list of the files with how big each one is, and allow users to check specifically which files they want pulled, that would be even better!

**Comment by rokroskar** [comment]
Thanks for reporting! You should never use that check box anyway :D 

This is most likely a notebook service problem, but maybe @lorenzo-cavazzi can have a look in case the solution requires changes on both sides.

**Comment by ableuler** [comment]
I came across the same issue and I quickly checked the body of the POST request which correctly sets `lfs_auto_fetch: true`. I'm therefore closing this issue and creating a new one in https://github.com/SwissDataScienceCenter/renku-notebooks.
