### ISSUE TITLE
Notebook display cosmetics

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#743]
# Description

The notebooks styling is not will integrated into the rest of Renku.

![image](https://user-images.githubusercontent.com/1196411/73439941-c2087400-4350-11ea-81a0-369086f1944e.png)

Notebooks should use the same typefaces that are used elsewhere in Renku and we should use the Bootstrap styling on tables.

**Comment by lorenzo-cavazzi** [comment]
Style is now consistent
![image](https://user-images.githubusercontent.com/43481553/224028812-35a33140-0d12-4556-aa38-a217f003d7bb.png)
