### ISSUE TITLE
Dataset search

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#757]
The dataset search feature has a couple of issues to address.

* Clicking on `search` invokes the `/datasets` API twice
* Page number is not reset when searching for a different dataset. If the second search has fewer results, it may show the user a blank page.
E.G. Assume the user searches for a dataset and the result has >1 pages (like the generic `*`). If the user goes to page >=2, then searches for a different dataset with less results, the page number is too high and it shows no results even if there are some (manually change to url to `&page=1` to see them).

**Comment by rokroskar** [comment]
I would also add another one: if you search, click on a dataset and then click the back button, the query is resubmitted. I would expect just to see the cached results.

**Comment by lorenzo-cavazzi** [comment]
We could cache on the UI and keep the content valid. In that case, we should add a timeout, let's say 1 minute? Then we invalidate the content and we query again.
A better solution would be handling this on the backend, returning a `304` response for the same query if the content won't change, but I believe it's more challenging to implement

**Comment by rokroskar** [comment]
Not sure - @jachro ?

**Comment by jachro** [comment]
Personally, I'd leave the caching for now. At least I wouldn't do it as part of that bug as caching could be a bit of evil quite often and requires a bit of thinking. Why not to try what's the user experience with the improved queries? It looks now that they are ready after ~500ms (reduced from 6s+)

**Comment by rokroskar** [comment]
> Why not to try what's the user experience with the improved queries? It looks now that they are ready after ~500ms (reduced from 6s+)

seems reasonable!
