### ISSUE TITLE
404 error flashing upon new project creation

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku-ui#766]
## Description

A 404 error appears quickly upon project creation. It is non-blocking and lasts for a split second.

![Screenshot 2020-02-17 at 09 27 55](https://user-images.githubusercontent.com/1531968/74639140-a503db80-516d-11ea-8dc8-7777f4b0ce72.png)

## Reproduce

1. Go to create a new project
2. Upon hitting the button, pay attention to your screen

## Context

- URL: https://renkulab.io (reproducible elsewhere, too)
- operating system and version: irrelevant (used MacOSX 10.14)
- browser and version: irrelevant (I used Chrome mainly)

**Comment by lorenzo-cavazzi** [comment]
related to #716
