### ISSUE TITLE
Add "back to renku" button on gitlab/jupyter

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#769]
## Motivation

Users sometimes struggle to get back to Renkulab when they open a page in GitLab or JuypiterLab. It would be great to have a "Back to Renkulab" button.
@emmjab 

## Proposal

Instead of redirecting to the "real" GitLab/JupyterLab page, we may try creating an extra layer with an `iframe` (or `embed`) to the target page plus a navbar on top that allows the user to go back to RenkuLab.
This requires tinkering a bit the Cross-Origin policy.

**Comment by ciyer** [comment]
Decided against this, as using iframes will fix some problems, but cause others and make the UI potentially more confusing. Back to Renku from JupyterLab will be addressed in #1121.

**Comment by ciyer** [comment]
[index.html.zip](https://github.com/SwissDataScienceCenter/renku-ui/files/5820501/index.html.zip)

The attached HTML file provides a workspace for playing with iframes.
