### ISSUE TITLE
change projects link on menubar

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#771]
## Motivation

There's a mismatch between which projects you're expecting to be searching over. For instance, many students in a class that were looking for the course material to fork couldn't find the the project.

**currently**
https://renkulab.io/projects: YOUR projects - link in the menu bar after the search box and first tab in the submenu for a user's view; should be all projects
https://renkulab.io/projects/search: ALL projects - first search box in the menu bar and third tab in the submenu for a user's view

at the very least they should be consistent.

## Proposal

https://renkulab.io/projects/user=[username]: YOUR projects
https://renkulab.io/projects/: ALL projects

and search boxes that correspond

## Context

currently:
<img width="841" alt="Screenshot 2020-02-19 at 15 13 53" src="https://user-images.githubusercontent.com/1056472/74842410-a8909180-532a-11ea-801a-5c26d1169786.png">

**Comment by emmjab** [comment]
The main thing I'm hoping for is that it's more clear which search box and which button correspond to searching over *your* projects vs searching over *all public* projects.

Things that could change: text (e.g. from "Search" to "Search over *all* Projects" v. "Search over *your* projects"), but also from a UX workflow standpoint, when you're just starting out and you don't have many projects, it's confusing to see a search bar. 

**Simplest solution, do the following three things**
1. Change "Search" to "All Projects":
```
Your Projects | Starred Projects | All Projects
```

2. Change "Projects" in the top menu bar to "Your Projects"
(But more likely, when we have "first class citizen" users, this will just be "Home")

3. In the search box in the menu bar, change the text:
From "Jump to or search..." to "Search all public projects..."

**Comment by rokroskar** [comment]
I like this suggestion! I only have one comment:

> From "Jump to or search..." to "Search all public projects..."

you're technically searching over all projects which you can access if I'm not mistaken.

**Comment by emmjab** [comment]
Ok maybe just “Search all projects” then, and the subtleties can be sorted out with some kind of “cant find what you’re looking for? Project may be private”

**Comment by ciyer** [comment]
Good catch! The labels made sense when they were initially set, but as more features were added, the similarities increased, and now I agree that the situation is a bit confusing. This is my suggestion:

<img width="355" alt="image" src="https://user-images.githubusercontent.com/1196411/75434853-7991a580-5952-11ea-934e-d3f89ed5efa0.png">

<img width="820" alt="image" src="https://user-images.githubusercontent.com/1196411/75434889-86ae9480-5952-11ea-93d9-e96be3104df2.png">

(There will be similar modifications to the "Starred Projects" tab)

**Comment by ciyer** [comment]
And I think you suggestion of changing the url from `/projects/search` to `/projects/all` also makes sense. 

I'm not as sure about how to handle the url for Your Projects. The "user" projects could have several interpretations -- projects that the user is a member of (this is what "Your Projects" shows), projects that are in the user's namespace (these can be found by searching, but there is no one-click listing for them ATM), or projects were the user is the Maintainer (no way to search just for these ATM).

**Comment by emmjab** [comment]
Sweet! Thanks @ciyer, I think your visual proposal makes sense!

> I'm not as sure about how to handle the url for Your Projects.

Yeah I agree, I think the url for "your projects" is also being discussed in another issue, so we can talk about it in conjunction with https://github.com/SwissDataScienceCenter/renku-ui/issues/784 ?

**Comment by vfried** [comment]
> Ok maybe just “Search all projects” then, and the subtleties can be sorted out with some kind of “cant find what you’re looking for? Project may be private”

Do you mean when the result for the search returns no projects?
