### ISSUE TITLE
Add user and group page

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#784]
(this is a follow up of #750 and #780 )

It would be nice to provide a meaningful page for users / groups at a proper url `/user/<namespace>` `/group/<namespace>`

This issue should be expanded with ideas and mocks (should it be an epic?)

**Comment by rokroskar** [comment]
I think this is a much larger challenge at least for the user part - we should discuss the full scope and definitely make an epic as it will certainly also involve the graph and the gateway.

**Comment by lorenzo-cavazzi** [comment]
This comes 4 years later, but we will soon have user and group pages :tada: 
The task has been moved to a ShapeUp pitch, currently available at this link for internal use https://www.notion.so/renku/User-and-Group-Homepages-b43f877259584a30aaac4e5ea93b3e47
More specific issues will be opened by the build team picking up this task. I'm closing this generic issue
