### ISSUE TITLE
Add new fields to dataset creation

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#790]
Dataset Creation should have the following fields:

|field|type|autogenerated| already there | comments |
|-----------| ----------- | ----------- | ----------- | ----------- |
|id| - | x | x | |
|date_published| dateTime | x | | we should create a publish action, not sure if there shuld be a publish action from within the create |
|description| free text (HTML) | |x | |
|identifier| | x | x  | this should be a DOI or something similar |
|keywords| array of keywords/strings | | | |
|basedOn| | | | not sure about this field |
|license| | | | not sure about this field |
|name| text | | | right now is there but there is a bug when sending names with spaces so the name is the sort name |
|url| url text |x |x | on the create this is the renku url of the dataset |
|version|  | | | |
|created| dateTime | x |x | |
|short_name| |could be autogenerated | | is the same as name and shouldnt |
|_project| renku project | x | x | when a dataset is created it is created from inside a project |
|creator| array of creators | | | we should allow the user to input the full array of creators/authors of the dataset, possibly a creator could be an organization |
|in_language|  | | | |
|files| | | x | |
|tags| ? | ?  || not sure what this means|
|same_as| | | |  not sure we need this in creation |

**Comment by ciyer** [comment]
Does description have to be HTML?

**Comment by vfried** [comment]
It's what we are getting from the imported datasets...

**Comment by vfried** [comment]
I am quoting google because they are also based in schema.org and seem to have the clearest documentation. https://developers.google.com/search/docs/data-types/dataset

**Comment by rokroskar** [comment]
This is great, thanks for putting it together @vfried! 

We want to be careful with `creators` - there are a few edge cases /issues to consider:

* verify the email formatting
* if a name is given, we should check if we have this name already in the KG. If the name is there, make sure the email that is provided is the same. If not, ask the user if they are sure about this and if it is the same person. If it is the same person but a different email we should a) handle this somehow in the KG or b) ask the user to use the email we have already in our KG. 

Is there a corresponding issue to support this in the backend already? cc @jsam

**Comment by ciyer** [comment]
From today's discussion:
- Use Markdown  instead of HTML for *description*
