### ISSUE TITLE
Underline parent node in the lineage graph whenever needed

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-ui#797]
## Motivation

When visualizing the lineage for a file inside a folder used as input for a Renku command, the graph is correct but the parent folder node is not underlined. This makes it harder for the user to understand which is the main node since the current file doesn't appear.

## Proposal

NEW (from the comments): we may add a new node for the file and bind it with the directory
OLD: We should underlay the parent folder's node. It may require extra information from the lineage API

## Context

E.G. the file `2019_verkehrszaehlungen_werte_fussgaenger_velo.csv` is the selected one on the following link, and the lineage refers to `/data/zhbikes/` that is the parent folder, but it is not clear
https://dev.renku.ch/projects/lorenzo.cavazzi.tech/zurich-bikes-tutorial/files/lineage/data/zhbikes/2019_verkehrszaehlungen_werte_fussgaenger_velo.csv

**Comment by rokroskar** [comment]
Not sure in this case it should be underlined because it probably won't really clarify things for the user - perhaps an explicit link between the file and the directory needs to be made?

**Comment by lorenzo-cavazzi** [comment]
That seems a good solution
