### ISSUE TITLE
View in Gitlab dropdown

### ISSUE THREAD

**Issue by pameladelgado** [SwissDataScienceCenter/renku-ui#798]
## Description

The `View in Gitlab` dropdown is visible and empty when looking at a project without necessary rights.

## Expected

Dropdown should not be shown in this case.

## Reproduce

1. Go to https://dev.renku.ch without logging in
2. Click on `View in Gitlab` dropdown
3. Dropdown is empty (see screenshot)

Same happens when accessing any project without the necessary rights.

## Screenshot

![view-in-gitlab](https://user-images.githubusercontent.com/43743260/75675996-a6aec280-5c88-11ea-8b07-b6a84b0f6d52.png)

**Comment by lorenzo-cavazzi** [comment]
This was fixed at some point but the issue was not closed.
We don't show anymore the dropdown menu if it's not relevant for the user.

![Screenshot_20200729_164229](https://user-images.githubusercontent.com/43481553/88814578-91e44580-d1ba-11ea-8540-9444dba29f90.png)
