### ISSUE TITLE
Maybe a Close button on the start env logs window

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-ui#804]
I've just found out that it was a bit confusing to me that there's no `Close` button on the Interactive Environment Logs window somewhere close to Download and Refresh buttons. It's a super tiny thing but I was a bit surprised there's no button which I'm looking for and which you kind of have to press in order to proceed.

**Comment by ciyer** [comment]
No longer relevant due to changes in the UI.

![image](https://user-images.githubusercontent.com/1196411/132707120-596a9469-5a4d-48db-9214-f235ea0fbb74.png)
