### ISSUE TITLE
Improve UX after dataset creation

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#814]
## Motivation

After a dataset is created it takes some time until the dataset is fully recognized in the KG, and the UI detects that the dataset can fetch it but it's not there, the KG returns a 404 to the UI and the UI displays a message that could make the user feel like the dataset it's not there.

## Proposal

We should wait a few seconds to give time to the KG to fully add the dataset to the graph. If this time is not enough then we should display a message saying to the user that the dataset is still being processed. 

In the future it would be nice to receive information about the status of a new dataset from the core service.

**Comment by lorenzo-cavazzi** [comment]
closed by #815
