### ISSUE TITLE
Paging list of datasets has jumps in the number of pages

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#821]
## Description

When paging a list of datasets, the number of pages jumps around.

On page 4, I see:

![image](https://user-images.githubusercontent.com/1196411/76527439-8690b780-646f-11ea-911f-46089e17267d.png)

After moving to the next page, I see:

![image](https://user-images.githubusercontent.com/1196411/76527492-99a38780-646f-11ea-829a-65a476040b2c.png)

## Reproduce

1. Go to https://sekhar.dev.renku.ch/datasets?q=*&page=4&orderBy=projectsCount&orderSearchAsc=false 
2. Scroll down to the bottom and click to get the next page

At step 1, you will see that there are a total of 6 pages, at step 2, you will see that there are only 5 pages.

## Context

- sekhar.dev.renku.ch
- macOS Catalina 
- Chrome 80.0

<details><summary>Browser Output</summary>
<pre>
If possible, paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by emmjab** [comment]
I think there might be another open issue somewhere that I can't find that someone was asking to see PREV < 1 2 ... 79 80 > NEXT --> can we do this? it would be useful even just to see that we have pages and pages of projects now.

**Comment by ciyer** [comment]
This seems to have been fixed in the meantime. Closing.
