### ISSUE TITLE
Deleted files show up in dataset's UI page

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-ui#828]
## Description

Files that are deleted in the project still show up in dataset's UI page.

## Reproduce

1. Go to https://stable.dev.renku.ch/projects/renku-qa/corona-pandemic/datasets/06735ea2-7e27-44d3-a60d-28d67e54e333/
2. `.gitignore` and `README.md` are deleted in the project, but show up here.

**Comment by vfried** [comment]
I think this is a KG bug since we are getting this info from the knowledge graph.

**Comment by ciyer** [comment]
This needs to be fixed in the KG. This will probably fixed together with https://github.com/SwissDataScienceCenter/renku-graph/issues/137.
