### ISSUE TITLE
Adding dataset or issue results in 404

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-ui#829]
## Description

In a project page, adding a dataset or an issue by click on the plus button on the top right results in a 404 error.

## Reproduce

1. Go to https://stable.dev.renku.ch/projects/renku-qa/corona-pandemic/files
2. Click on `+` button on top right
3. Select `Dataset` or `Issue`

**Comment by rokroskar** [comment]
Could we verify that this is still a problem? Otherwise lets close the issue. Note that stable may be in a very different state from where it was in March (i.e. it might not work/exist).

**Comment by lorenzo-cavazzi** [comment]
This was fixed.
