### ISSUE TITLE
Disable KG after activating it

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-ui#832]
## Context

There is no option in the project page to disable KG generation once it was activated for a non-public project.

**Comment by ciyer** [comment]
This could easily be added to the *Settings* tab.

**Comment by rokroskar** [comment]
It would need to trigger an action with the KG to remove the existing triples - cc @jachro

**Comment by jachro** [comment]
Yes, once we play issues about extracting the Event Log service, such operation should be possible.

**Comment by lorenzo-cavazzi** [comment]
KG cannot be disabled anymore for private/internal projects since it's used by the cross-entity search.
