### ISSUE TITLE
LoggedInHome improvements

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-ui#835]
1. Link to create a new project is at the very bottom of the page; it should be first thing up in the list.
2. Right pane (help section) should have a fixed width and should be smaller (perhaps with smaller fonts too). Left pane (links to projects) should have a bigger portion of the screen.
3. Starred projects should show up before all projects (it would be ideal to find a way to mix these two together).

**Comment by ciyer** [comment]
Made obsolete by #1447.
