### ISSUE TITLE
Handle simple merge requests across forks through UI

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#837]
The following scenario is quite frequent during a course setting: 
- Participants fork a repo
- The main repo gets updated (let's say adding solutions to exercises)
- Participants would like to update their repo too

I suggest to enable simple conflict-free merge requests from forked repo to fork (master to master) through the renku UI, referring to the correct gitlab page for more complicated actions.

**Comment by rokroskar** [comment]
A downstream merge request? Does that even exist?

**Comment by ciyer** [comment]
I understood it as being a straightforward request.
- User navigates to *forked project*
- User clicks on "Check for Updates" (or something)
- UI checks if the upstream is ahead of fork
- If so, an MR is created for the user to process.

Seems doable.

**Comment by rokroskar** [comment]
Actually the gitlab API probably tells you if the project is behind the upstream master. The request is simple, but I'm wondering why this isn't implemented by e.g. gitlab and github already. For courses you would need to be extra careful about project structure to avoid conflicts, but I guess it should be doable.

**Comment by emmjab** [comment]
Just chiming in to say there's interest in this from other courses & labs!

Also i'm not sure how different this is from mirroring: https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html

**Comment by ableuler** [comment]
> A downstream merge request? Does that even exist?

Yes. In order to achieve it through GitLab, I have to initiate the MR from the upstream repo, then I can select the downstream repo as target.

**Comment by rokroskar** [comment]
Aha! I didn't know that was possible. :)

**Comment by ableuler** [comment]
> Just chiming in to say there's interest in this from other courses & labs!
> 
> Also i'm not sure how different this is from mirroring: https://docs.gitlab.com/ee/user/project/repository/repository_mirroring.html

Hmm, our use case is definitely not what mirroring was designed for (sending updates to/ getting updates from repositories which are kept outside of GitLab). Without having tested this I would expect the mirroring of the two master branches to fail as soon as the downstream master branch has changed, therefore needing a merge commit.

I think like the workflow suggested by @ciyer and I believe that this can be implemented using the gitlab merge request API.

**Comment by emmjab** [comment]
dropping this link here as well because it still sounds like our use case: https://about.gitlab.com/blog/2016/12/01/how-to-keep-your-fork-up-to-date-with-its-origin/

**Comment by ableuler** [comment]
@emmjab hmm, I admit that this is against my above statement:

> Hmm, our use case is definitely not what mirroring was designed for (sending updates to/ getting updates from repositories which are kept outside of GitLab).

Would you mind trying if this can also do non fast-forward merges on the downstream repo? If yes, mirroring could indeed be an option to activate when forking.

**Comment by rokroskar** [comment]
Another solution might be to automatically add an `upstream` remote to interactive sessions - then users can handle the merging themselves (I know most people don't know how to do this, but the workflow for the 90% case is not difficult to document?)

**Comment by ableuler** [comment]
> Another solution might be to automatically add an `upstream` remote to interactive sessions - then users can handle the merging themselves (I know most people don't know how to do this, but the workflow for the 90% case is not difficult to document?)

I think this would be a generally useful feature for forked projects, yes. But I'd still like to have the UI button for the simple case :)

**Comment by lorenzo-cavazzi** [comment]
We recently came up with a possible solution for the issue here https://github.com/SwissDataScienceCenter/renku-ui/issues/2168#issuecomment-1329448674
I'm closing this since the other has a couple of screenshot that provide bit more context on the current UI
