### ISSUE TITLE
Hide input cells of notebooks by default

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#838]
## Motivation

Many notebooks are designed to be viewed by a public that might not care about the code. It should be possible to show notebooks with input cells hidden.

## Proposal

All notebooks should have a radio-button-type interaction to select whether the input cells are shown or not. For the default behavior, there are two options:

* Option 1:  Have a setting a for each notebook: show or hide input cells as default
* Option 2: For notebooks in the "notebooks" folder, show input cells, for notebooks everywhere else, hide input cells

Option 1 is more powerful, but a bit more work to implement, and adds more cognitive load on the user
Option 2 is very easy to implement, but could seem a bit arbitrary unless it is clearly documented and explained.

**Comment by rokroskar** [comment]
This is a really good idea - would it be possible to do 1. with defaults set as described in 2.? Also, if for the public, it would be nice to have some mode in which most of the rest of the project can be hidden and just the notebook content displayed.

**Comment by ciyer** [comment]
After a little investigation, I realized that this is already possible. Our notebook render looks for notebook and cell metadata to control this.

If the **notebook** has `metadata.hide_input == true`, then all inputs will be hidden. If a **cell** has `metadata.inputHidden == true` or `metadata.hide_input == true`, then the cell's input will be hidden. See [source](https://github.com/nteract/notebook-render/blob/master/src/index.tsx)

Further, papermill has flag `--report-mode`. When this is used, it will set the **cell** metadata field `metadata.jupyter.source_hidden: true`. However, our renderer does not recognize this. We could do one of the following:
1. Fork the notebook-render project to support this behavior 
2. Scan all cells and, if we see `metadata.jupyter.source_hidden == true`, also set `metadata.hide_input: = true`, which is understood by our renderer.

My vote is for 2.

**Comment by lorenzo-cavazzi** [comment]
+1 for solution number 2

**Comment by rokroskar** [comment]
Can we make the hiding on by default but provide an option to un-hide? Often it is useful and desirable to see the code.

**Comment by ciyer** [comment]
We could, but I want to keep the UI and possible interactions as simple as possible. I do not want to have the ability to show/hide each individual cell. I think this should be a setting for the whole notebook.

1. Respect what is in the notebook metadata (user may need to look at file or launch environment to view code)
2. Allow user to switch between shown/hidden code. *If* any cells are marked hide_input, then the switch defaults to`hide`, otherwise, switch defaults to `show`

What I like about 1 is that it keeps the UI clean and lets the notebook author have full control over this behavior. I do understand the utility of 2., but I wonder what % of our users will benefit from this.

**Comment by rokroskar** [comment]
I fully agree that the default should be up to the author. But allowing the user to override it if they want seems not that far-fetched (on the notebook-level, not cell-level). Otherwise if I want to quickly copy-paste a snippet I have to 1. find the notebook, 2. realize I can't see the code, 3. clone the project or open the notebook in gitlab. 2. & 3. seem unnecessary.
