### ISSUE TITLE
Merge Request suggestions include merged branches

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#841]
## Description

The branches that are offered as candidates for merge requests include merged branches. 

![image](https://user-images.githubusercontent.com/1196411/76864137-dfda5b80-6860-11ea-8ad6-1c8a641650ed.png)

The problem seems to be with GitLab, since the response to the request for branches looks like:
```
  {
    "name": "update",
    "merged": false,
    "protected": false,
    "developers_can_push": false,
    "developers_can_merge": false,
    "can_push": true,
    "default": false
  }
```

We need to keep track of GitLab updates and check if this is fixed by upgrading.

## Reproduce

1. Create a merge request
2. Merge the merge request
3. See that the already merged branch is still suggested as a candidate for a MR

## Context

- dev.renku.ch (does not happen on renkulab.io)
- GitLab Version: GitLab CE 12.6.8 (compared to 11.9.11 on renkulab.io)

<details><summary>Browser Output</summary>
<pre>
If possible, paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by lorenzo-cavazzi** [comment]
Merge requests were removed as in the older format, and now we use the GitLab page for that
