### ISSUE TITLE
select gitLFS files to pull into interactive environment

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#848]
## Motivation

Users struggle with gitLFS. Mainly they struggle for the following two reasons:
1. we put stuff into LFS without explaining what it is or why, and they have no problem working with their files the first time but when they close and then open a new environment the files are "missing". 
2. they add data that is too big for git to git sometimes, and then we have to help them get it back out; or they (or we help them) add stuff to git lfs.

The checkbox for adding everything from git lfs to the environment might kill the node, so it's not the best solution to just let people check this box. at the same time they will need their data to do analysis in the notebook; the idea would be to help them deal with this data as they need it.

## Proposal

- inform users that all files added with `renku dataset`, the dataset UI, or created during `renku run` will be in git LFS (and what this means)
- inform users that their LFS files in the interactive environment will be pointers unless they check following boxes
- let users check boxes to select which files will be pulled into the interactive environment
- interactively control for how much data they can pull into the interactive environment (with each selection, update a count of how many GB is being added, and if it exceeds a threshhold, turn red and make them uncheck other ones to check others)
- explain that they can still add files in the interactive environment with `renku storage pull <file>`
- come up with a good way of replacing the files they added into the interactive environment back to pointer files so they can save space
- first message that spits into the terminal in the interactive environment should explain how to pull lfs files into the environment or return files to pointers.

## Context

I've gotten many user questions about where their files are, scripts failing because data is actually just the pointer file and they didn't notice, etc.

While it would help to put a threshhold for which files go into LFS, i agree with the "let's just put them all in" mentality because a user could have lots of small MBs of files that collectively add up into a huge git project, and no one knows that in advance.

We should also make it clear that datasets are different from gitLFS, and that they can manually add files to gitLFS using `git lfs track` if they want.

Other considerations: sometimes all the data is zipped together in one huge file that might be too big for the enviroment. We should also help them break it into pieces.

**Comment by lorenzo-cavazzi** [comment]
We now have alternatives to Git LSF for getting external data into sessions, and Git LFS won't be a first-class citizen with a dedicated UI.
I'm closing this issue. Feel free to open a new one if you think there are still reasons to consider a similar functionality.
