### ISSUE TITLE
Collaboration Streamlining

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#850]
## Motivation

Working a lot with the collaboration features has made a few improvements obvious.

## Proposal

See the issues that are part of this epic.

**Comment by lorenzo-cavazzi** [comment]
All the issues here have been closed.
We are removing the Collaboration tab for now (https://github.com/SwissDataScienceCenter/renku-ui/issues/2256 ) and we will re-think it in the future if necessary
