### ISSUE TITLE
Show commit messages in renkulab

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#852]
## Motivation

Seeing the commit log is helpful to understand what has been happening in a project. I find myself often going to GitLab to see this, so we should integrate it into Renkulab directly.

## Proposal

Add a tab "Commits" to the overview page and show the commit log there. They should be grouped by date -- there should be a header with the date and all commits in that date should be there. See mockup below.

### Interactions

Initially, 

- It should be possible to diff a diff of the commit to its immediate parent
- It should be possible to navigate to the commit in GitLab
- Link to start environment at commit

Other interactions can be done later.

## Context

![image](https://user-images.githubusercontent.com/1196411/77298849-d4b57e80-6ceb-11ea-819f-8080dd641190.png)

## Notes

* There is already code to get commits in the Notebook component (Notebook.state.js probably). This should be moved up to a shared location.
* May want to consider adding this a project submodel of the main redux store

**Comment by rokroskar** [comment]
Will this also then allow the user to select a commit to look at?

**Comment by ciyer** [comment]
Good point. Just clarified this in the issue desc.

**Comment by emmjab** [comment]
Also along the lines of commits -- it would also be nice to see the first N chars of the commit message in the Environments tab when you're selecting a commit with which to start an environment! It would help users decide which commit to select and provide positive feedback for making descriptive commit messages

cc @vfried
