### ISSUE TITLE
Top navbar '+' button options do not work

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#858]
## Description

There are several problems with the '+' menu:

* The items are not highlighted on mouseover
* The new issue does not work
* The new data set does not work

![image](https://user-images.githubusercontent.com/1196411/77407886-2840ce80-6db7-11ea-9c8e-07d8556eb284.png)

## Reproduce

1. Go to any project
2. Click on the plus menu
3. See the problems listed above

## Context

- dev.renku.ch
- macOS / Chrome

<details><summary>Browser Output</summary>
<pre>
If possible, paste the output from your browser Javascript console here.
</pre>
</details>

**Comment by rokroskar** [comment]
The first bullet point has an issue open somewhere from a long time ago I think...
