### ISSUE TITLE
Remove autosave branches when forking a project

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-ui#866]
Currently, when forking a project, the forked project also contains all autosave branches. Consequently, a first notebook launch on the forked project will try to recover from the autosave branch. I think it would be nice if the UI would delete all autosave branches through the API after forking a project.

**Comment by rokroskar** [comment]
I agree - not sure it's a bug though...

**Comment by ciyer** [comment]
It is sort of a bug in that you end up in an environment with different code than you think you should when you start it. This only happens per user, right? (I.e., , it only happens if *I* launched an environment on the original project and then fork and launch a new environment.)

**Comment by rokroskar** [comment]
It's not a bug because the fork works as intended... but I agree that it's confusing for the user.

**Comment by ableuler** [comment]
I was hesitant to give it the bug label in the first place... :)

**Comment by lorenzo-cavazzi** [comment]
We are dropping autosaves soon -- this will be fixed "for free"
