### ISSUE TITLE
link to gitlab from renkulab nav bar

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#867]
## Motivation

It's hard for users to find the link to gitlab when they haven't created any projects yet, and this is a thing they have to do to be able to push existing projects to renkulab (because they have to set up an ssh key from gitlab).

## Proposal

put the link to gitlab in the nav bar (or somewhere else global)

**Comment by ciyer** [comment]
I think the user menu would be a natural place for this. Does that make sense?

**Comment by emmjab** [comment]
Conceptually that sounds ok! What's the user menu? (is that something we have already or the thing we'll have soon?)
