### ISSUE TITLE
Use GitLab Events to populate "Your Projects"

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#888]
## Motivation

The projects I'm most interested in are probably those that I have recently done something on. It would be nice to highlight those in "Your Projects"

## Proposal

Use the GitLab Events api https://docs.gitlab.com/ee/api/events.html to determine which projects the user has worked on most recently. Those should be shown first in *Your Projects*. If there are not enough projects there, then show more projects using the same logic we currently use.

**Comment by lorenzo-cavazzi** [comment]
We implemented something along these lines for populating the Dashboard. We rely on KG to establish the importance of the projects
