### ISSUE TITLE
Show project "events" in the project page

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#889]
## Motivation

It's not easy to keep up with the activity that has been happening on a project. The GitLab events API provides some information that can be used to show a user what has been going on.

https://docs.gitlab.com/ee/api/events.html

## Proposal

Show activity in a tab on the overview page.

**Comment by rokroskar** [comment]
I was about go open an issue about this! It's the Nr. 1 problem for me when trying to collaborate on a project.

**Comment by lorenzo-cavazzi** [comment]
[Renku 2.0](https://blog.renkulab.io/renku-2) will disentangle Projects and Repositories. Considering getting events from the Repository management systems requires longer discussions. I'm closing this issue; it might worth it opening a ShapeUp project for this -- if it's still desired
