### ISSUE TITLE
After KG is built the ui displays a message like there are no datasets when there are

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#895]
## Description

After kg is built the UI displays a message like there are no datasets:
![image](https://user-images.githubusercontent.com/42647877/78672841-7ee2f800-78e1-11ea-8a4d-5f378c68f7e1.png)

When there are datasets:
![image](https://user-images.githubusercontent.com/42647877/78672883-902c0480-78e1-11ea-9962-43afbdfea7d7.png)

## Reproduce

Activate the KG for a project with datasets and wait to see the message

**Comment by rokroskar** [comment]
I thought this has been fixed?

**Comment by vfried** [comment]
I think it's been fix by some other change but i want to check to make sure that it's fixed 100%

**Comment by ciyer** [comment]
Closing this because it is made obsolete by #977.
