### ISSUE TITLE
Wrong creation of dataset 

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-ui#896]
I am trying to create a dataset in Renkulab by importing the zip file `ABdataset.zip` with the following hierarchy:

├── ABdataset
│   ├── 1900
│   │   └── 06_collectedinformation.pickle
│   ├── 1901
│   │   └── 06_collectedinformation.pickle
│   ├── 1902
│   │   └── 06_collectedinformation.pickle
│   ├── 1903
│   │   └── 06_collectedinformation.pickle
│   ├── 1904
│   │   └── 06_collectedinformation.pickle
│   ├── 1905
│   │   └── 06_collectedinformation.pickle

After uploading the zip file in the UI of Renku, it prompted that there was an error with the naming, and it was changed:
![Screenshot 2020-04-07 at 15 08 53](https://user-images.githubusercontent.com/8778401/78673204-19dbd200-78e2-11ea-80e3-1c110a6c0c7c.png)

But it did not provide any more information. However, when finally clicking on Create Dataset, this was the final result:
![Screenshot 2020-04-07 at 15 13 16](https://user-images.githubusercontent.com/8778401/78673378-57d8f600-78e2-11ea-91db-7ef076a49587.png)

I replicated this error in the following repo:
https://renkulab.io/projects/luis.salamanca/test_importdataset

And here I am in case I can help further 😄 

Thanks!
Cheers

**Comment by vfried** [comment]
Luis, thanks for submitting this issue.

Can be replicated with this folder:
[myzipped-08-04-2020-10-35-58.zip](https://github.com/SwissDataScienceCenter/renku-ui/files/4449307/myzipped-08-04-2020-10-35-58.zip)

**Comment by lusamino** [comment]
This was fixed already! Thanks @vfried !
