### ISSUE TITLE
Wrong message when a zip file has un-allowed chars inside

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#897]
#  Description

The message here is

![image](https://user-images.githubusercontent.com/42647877/78763249-2f560800-7985-11ea-861b-816d1787660f.png)

But should be something like:
*Some names inside the zip file have disallowed characters and have been renamed. (If possible list the names)

## Reproduce
[myzipped-08-04-2020-10-35-58.zip](https://github.com/SwissDataScienceCenter/renku-ui/files/4449584/myzipped-08-04-2020-10-35-58.zip)

It happens when uploading that file and unziping it in the backend

**Comment by ciyer** [comment]
I think this was fixed by #898

![image](https://user-images.githubusercontent.com/1196411/81449859-76503c80-9181-11ea-934d-10d3a159f663.png)
