### ISSUE TITLE
Unify listing page UIs

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#908]
# Description

We have several pages where we have a list/new interaction.

1. Project
![image](https://user-images.githubusercontent.com/1196411/79748084-1ba78b80-830d-11ea-82f2-9d1113fdccda.png)

2. Collaboration/Issues
![image](https://user-images.githubusercontent.com/1196411/79748133-34b03c80-830d-11ea-9a3c-ace0f98fa61d.png)

3. Collaboration/Merge Requests
![image](https://user-images.githubusercontent.com/1196411/79748166-4396ef00-830d-11ea-9352-41495eddded7.png)

4. Datasets
![image](https://user-images.githubusercontent.com/1196411/79748198-50b3de00-830d-11ea-9a82-c882efba3270.png)

5. Environments
![image](https://user-images.githubusercontent.com/1196411/79748222-5c9fa000-830d-11ea-8863-60d71357e64d.png)

They are all similar, but all work slightly differently. We should unify the interaction to make them all work the same.

# Proposal

They should all work on the Projects/Issues model:
* Main display is a listing which includes short name and summary
* Main display contains a "New" button
* Clicking on an item takes you to the details
* Clicking on "New" takes you to a page to create a new thing
* If empty, the list should indicate that it is empty and tell you how to create something new (like Environments)

**Comment by lorenzo-cavazzi** [comment]
We harmonized the way we show buttons to add items
