### ISSUE TITLE
When one dataset fetch fails dataset's aren't displayed

### ISSUE THREAD

**Issue by vfried** [SwissDataScienceCenter/renku-ui#924]
## Description

When one of the datasets inside a project fails instead of displaying the "non-failed" datasets everything fails and it looks like the project has no datasets.

![image](https://user-images.githubusercontent.com/42647877/80968019-91384f00-8e17-11ea-9d0d-367bb9cc5e56.png)

## Reproduce

It happens here... https://renkulab.io/projects/covid-19/covid-19-public-data/datasets

**Comment by rokroskar** [comment]
Is this going in `0.10.1`?

**Comment by vfried** [comment]
I think so... It needs to be reviewed
