### ISSUE TITLE
Download files in renkulab

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#928]
## Motivation

The renkulab UI should allow downloading files.

* Download should be available both in the file browser and in the dataset file view
* Download should be available for files in the git repo and LFS files

## Proposal

(coming soon)

**Comment by emmjab** [comment]
Downloading should also be possible for full datasets!

**Comment by ciyer** [comment]
This has been implemented in the meantime. Closing.
