### ISSUE TITLE
Add a button for (renku) cloning a project

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-ui#929]
Currently it's not too clear what url to use with the `renku clone` command and many users might not even be aware that this is an option that allows them to copy a project locally (e.g. for when they go somewhere with no internet access).

For this reason it'd be nice to have a button in the UI that streamlines this process, similar to the `Clone or Download` button on github
![image](https://user-images.githubusercontent.com/664486/81912703-3baa3200-95cf-11ea-89e7-2dac58ec1ed7.png)

This could be next to the "Take me to gitlab" button we already have on the project page.

With content like:

> **Clone with Renku:**
> Install renku locally (link) then run
> `renku clone ...`

I'm not sure if we also want instructions to just clone with `git` or if we want to discourage that

**Comment by ciyer** [comment]
A button is probably to prominent for this feature for our users, but we can add a short explanation to the settings page for how to clone the project.
