### ISSUE TITLE
Maintenance 

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#938]
## Motivation

#894 created a page for showing maintenance information, but this is very rigid. We would like to be able to dynamically show information to the user.

## Proposal

Use renku.statuspage.io/api to get the information to show here. See the comments below.

### UI Change -- Help

Add a tab to the help page showing the status page information.

![image](https://user-images.githubusercontent.com/1196411/84915657-60596400-b0bd-11ea-945f-8b98f9340510.png)

### UI Change -- Landing/Welcome

Add any scheduled maintenance information to the welcome screen on the landing page.

![image](https://user-images.githubusercontent.com/1196411/84990703-d5707c00-b145-11ea-8fc3-0defc19af1e9.png)

![image](https://user-images.githubusercontent.com/1196411/84990716-dacdc680-b145-11ea-81a5-916a69a3229e.png)

**Comment by rokroskar** [comment]
We should use the statuspage status embed - either use the one they provide or roll our own: https://support.atlassian.com/statuspage/docs/build-your-own-status-embed/

**Comment by lorenzo-cavazzi** [comment]
The APIs provided by statuspage are really useful and apparently straightforward to integrate
https://renkulab.statuspage.io/api
E.G: this contains all the data we need https://5bcn9bqff4qt.statuspage.io/api/v2/summary.json but we may query something more specific after the first time (`status.json`?)

We may use this information to:
1. Notify new scheduled maintenance on the Landing page
2. Check for the current status of single components periodically (simpler) or  when something is not working as expected (better, E.G. when a `renku-graph` API times out or return a `5xx` response we check the graph component status)
