### ISSUE TITLE
inconsistent rendering of jupyter notebooks

### ISSUE THREAD

**Issue by schymans** [SwissDataScienceCenter/renku-ui#946]
## Description

The rendering of jupyter notebooks in renkulab has a problem that is not present in gitlab. Compare https://renkulab.io/projects/stanislaus.schymanski/essm_egu_2020/files/blob/notebooks/Priestley-Taylor_equation.ipynb with https://renkulab.io/gitlab/stanislaus.schymanski/essm_egu_2020/blob/master/notebooks/Priestley-Taylor_equation.ipynb

## Reproduce

1. Open https://renkulab.io/projects/stanislaus.schymanski/essm_egu_2020/files/blob/notebooks/Priestley-Taylor_equation.ipynb in firefox
2. In a new tab, open https://renkulab.io/gitlab/stanislaus.schymanski/essm_egu_2020/blob/master/notebooks/Priestley-Taylor_equation.ipynb
3. Go to first tab and scroll down to Section Eq. 3 and look at the markdown field below. You find lots of black bars and whitespace.
4. Go back to second tab and scroll down to the same place. You find a not-rendered equation in the markdown field, but the rest displays fine.

Probably an issue with mathjax rendering.

**Comment by lorenzo-cavazzi** [comment]
Thank you @schymans for reporting this, and sorry for considering the issue so late.
Apparently, the library we are using for rendering the notebooks is not maintained anymore and some failing parts (e.g. rendering components for mathematical formulas) are likely not to be fixed. We will try to find an alternative solution in one of the following sprints.

P.S. Another reference project for this failure: https://renkulab.io/projects/dslab-ethd/dslab20-w1-exercises/

**Comment by ciyer** [comment]
We should investigate if https://www.npmjs.com/package/@nteract/notebook-render is still the best solution for displaying notebooks, or if we need to look for an alternative.

**Comment by andre-code** [comment]
Hi @schymans we have already implemented the fix which will be ready for the next release for Renku UI.
This is how the file would look like after the changes, you are welcome to confirm if this is the expected solution for this case.

![display math code](https://user-images.githubusercontent.com/43388408/142025759-4aaa6747-1d10-48a0-bd9a-97a7a8ff04e1.gif)

**Comment by schymans** [comment]
This looks great, thank you!
