### ISSUE TITLE
Datasets search to work with match relevance instead of projects count

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-ui#948]
As a Renku user, I'd like to see the datasets matching my search criteria sorted by relevance.

Acceptance criteria:
* the Datasets Search page to allow sorting the results by matching relevance;
* the Datasets Search page NOT to allow sorting by projects count;
* the found datasets to highlight the matching phrase - to be confirmed if we're going to do that as part of this issue.

A corresponding issue on the backend API is [#306](https://github.com/SwissDataScienceCenter/renku-graph/issues/306)

**Comment by ciyer** [comment]
I disagree with the second bullet point. I think users will want to be able to sort by project count (though I do not think it should be the default sort).

**Comment by jachro** [comment]
I thought we reached a sort of agreement yesterday that because of the complexity and difficulty of fetching the `projectsCount` we'd drop it in favour of the `relevance`. If you don't think that's a good idea, we can leave things as they are and close the issue.

**Comment by ciyer** [comment]
I think we should do the following:
* The default sorting should be by relevance, but projectsCount should be an option
* projectsCount should be stored as a field in elastic search and all queries should be against elastic search alone

**Comment by jachro** [comment]
That's an interesting option definitely worth exploring. Unfortunately, I don't think it's a 5 min change as we'd need to update the value during triples generation based on some query finding the current projects count.

**Comment by ciyer** [comment]
Yes, I agree that it will require updating the projects count in elastic search whenever the triple store is updated.

**Comment by lorenzo-cavazzi** [comment]
KG has implemented this solution and the UI is relying on KG search
