### ISSUE TITLE
renku-ui should give users a cookie opt-in/out dialog

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-ui#949]
## Motivation

renkulab should comply with the Cookie Law and let users know that we are using cookies to make the site function. This should be part of the privacy policy text. Ideally, this text should be modifiable by an admin so that other renku deployments can provide their own text easily. 

## Proposal

A standard "we use cookies, click OK" dialog somewhere and a link to the privacy policy.

### UI Changes -- Footer

![image](https://user-images.githubusercontent.com/1196411/84992015-97745780-b147-11ea-9285-68ec5aabdf1f.png)

## Context

https://gdpr.eu/cookies/

**Comment by ciyer** [comment]
We should use web storage to remember that the user has accepted the cookie policy. We should store the date of acceptance as well, so that we can re-request approval if we change the cookies we use.
