### ISSUE TITLE
Updates to project's setting is not saved on dev.renku.ch

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-ui#951]
When updating a project's setting (tag or description), clicking on the Update button has no effect and nothing happens. Reloading the page shows that nothing is saved. This happens on `dev.renku.ch` but on `renkulab.io` it works fine.

## Reproduce

1. Go to https://dev.renku.ch/projects/renku-qa/corona-pandemic/settings
2. Update either tags or description
3. Click on the appeared Update button
4. Nothing happens

**Comment by lorenzo-cavazzi** [comment]
Thanks for reporting this! It happens when updating a project without the permissions to change the project name. I thought we fixed this already, but it probably got lost :shrug:
