### ISSUE TITLE
data upload size limitations

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#973]
## Motivation

Working with a user, took longer than we had patience for to upload 1GB so found an alternate way.

## Proposal

in small text in the upload box, it would be nice to specify the maximum size of the data upload. if there's no maximum, we could write that as well. we should also test to make sure a few large sizes are possible, and indicate about how long it might take to upload a few different sizes.

## Context

Some users had issues uploading larger (1GB+ data)

**Comment by ciyer** [comment]
The UI does include a note about this, but it is vague. We could make that more precise.

![image](https://user-images.githubusercontent.com/1196411/86443721-f624fe00-bd0f-11ea-9e8a-e58d2d96132c.png)
