### ISSUE TITLE
display file size in renkulab file browser

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-ui#974]
## Motivation

When users are starting an interactive environment they have to decide whether to include all LFS files or none using the check box. But unless they go to gitlab (or already know how much data is in the project because they recently added the data and it's their own project), they don't know how much data will be pulled into the session.

## Proposal

include the total LFS file size vs the project file size, and the file sizes on the file browser for each file.

## Context

This could also make it easier for us to point out when someone accidentally added large data to their project.

**Comment by ciyer** [comment]
This information is available at the project granularity on the project stats page.

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1196411/86235907-77a65000-bb99-11ea-8720-86ff5213130a.png">

For the use case you describe, this is probably the right level of information, but I agree that it would be nice to see these stats at the file level in the file browser.

**Comment by ciyer** [comment]
For LFS files, we should read the pointer file and figure out how large it is.
