### ISSUE TITLE
Retrieve dataset information from core-service

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#977]
# Description

The UI gets information about datasets from the knowledge graph. Not all projects are in the knowledge graph, though, and for those projects, no UI interactions with datasets are possible.  Issue https://github.com/SwissDataScienceCenter/renku-python/issues/1334 will provide an endpoint in the core-service for getting information about datasets in a project (without cloning the project). The UI should use this endpoint to get information about datasets, so datasets will be usable from the UI even if the project is not in the KG.

# Implementation

- Add an adaptor layer which can switch between getting dataset information from the core-service or the KG (since components are shared, sometimes they will get info from the KG, sometimes from the core-service)
- For displaying datasets, remove the check that the project is in the KG -- this is not needed for displaying datasets
- Remove the banner that warns when a project is not the KG -- this can be placed in the settings page.

**Comment by ciyer** [comment]
We will need to make dataset display code more modular, since there are cases where the information comes from the KG (dataset search) and cases where it will come from the core-service (project).

**Comment by vfried** [comment]
Closed by #1029
