### ISSUE TITLE
User notification/alert system

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-ui#991]
# Description

_Originally posted by @lorenzo-cavazzi in https://github.com/SwissDataScienceCenter/renku-ui/pull/989#issuecomment-662431005_

> An interesting idea would be adding a global notification system so that we can popup info/ warning messages when something not too critical goes wrong.
> E.G: errors in fetching starred projects currently result in .catch(error => []) without further actions. It's not easy to add visual feedback since it's invoked in many different places, and throwing an error is not desirable since the impact is limited. I would like to notify the user with a popup, possibly with a re-execute button. Ideally, I would add the warning to a global queue with a function like this: this.model.addNotification("cannot get the starred projects", "Type.WARNING", functionToReInvoke).
> If this makes sense, I'll create an issue. We probably need anyway an extensive notification system when we have a web socket backend, this could be the first step.

We can look for places that use console.log as potential candidates for using notifications. I have also added `TODO: #991` to code as well.

**Comment by lorenzo-cavazzi** [comment]
Here is my proposal for having a flexible notification/alert system

I would add these 3 elements
1. A toast notification system to make the user aware of what happend (display duration ~5sec)
2. A permanent notification icon in the top navbar with a number for the unread important notifications
3. A full page with the notifications history

The first 2 elements would be available in all pages (see mockup below), while the 3rd is a dedicated page.

![Screenshot_20200811_151839](https://user-images.githubusercontent.com/43481553/89903386-e12d6b80-dbe7-11ea-814b-7f0f1b8522cc.png)

I would set 4 levels for the notifications. All will appear as toast and in the full page, only the relevant ones in the notifications, some will have a link to follow up.
- info: something completed, no user action expected (no notification, no link)
- success: something completed, user may want to follow up (+1 notification, link expected)
- warning: something failed, no user action expected (+1 notification, no link)
- error: something failed, user may want to follow up (+1 notification, link expected)

Another possible level is "fatal" for unexpected errors that make the application unstable. It should briefly explain what happend and invite the user to reload the page or contact us.

**Comment by ciyer** [comment]
Not yet entirely sure that this is what we will want in the end, but I think it is a good start and will give us the components we need. Fine-tuning the UX can happen later.

**Comment by lorenzo-cavazzi** [comment]
close by #1036
